### ISSUE TITLE
Change Group Policy

### ISSUE THREAD

**Issue by kirstenht** [microsoft/o365-moodle#1549] opened 2021-01-21 00:07 UTC
When we create courses on Moodle, the Group Privacy is already set to HiddenMembership group with Teams with the group already hidden from the global address list. We are unable to change the Group Privacy through the Admin side. 

Is it possible to set the Privacy and General Settings for the site before the Groups and Teams are created?

**Comment by weilai-irl** [comment] 2021-01-21 11:05
Hi @kirstenht,

This is caused by an inconsistency in the Microsoft Graph API functions and resources, and there are a number of discussions on various communities and even GitHub about the issue. We have tried to solve this issue before but failed. There's nothing that the Moodle plugin can do unless some changes are made to the Graph API function by Microsoft.

The root of the issue is, Moodle uses [a Microsoft Graph API function](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http) to create class Teams. The actual call is similar to example 6 and 7 on that page. While "visibility" is a parameter accepted by the API function, what we found is custom template (in this case, education template, which would result in a class Team rather than a standard Team) and "visibility" cannot be provided together, otherwise it would result in an error in response. This effectively means that all class Teams created using the Graph API call will end up having the default visibility setting, which happens to be "HiddenMembership".

The fact that the privacy settings of groups created cannot be changed from Microsoft 365 admin centre is a separate issue, clearly out of the scope of this project, and should be reported to Microsoft separately.

For a bit of more background - "HiddenMembership" is listed as a possible value for the visibility attribute of a [group](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0), but is not listed as a possible value for the visibility of a [Team](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0). Microsoft doesn't provide more documentation on why Teams created by Graph API call using custom template would end us using "HiddenMembership" visibility settings, unfortunately.

I'll mark this issue closed as there's nothing can be done here.

Regards,
Lai

**Closed by weilai-irl** 2021-01-21 11:05 UTC
