### ISSUE TITLE
Clicking the OIDC login button redirects to the moodle homepage

### ISSUE THREAD

**Issue by upats** [Microsoft/o365-moodle#251] opened 2018-06-26 19:19 UTC
If I enable the OIDC Auth plugin, then click the login button on the login page, I simply get redirected back to the Moodle home page. No auth redirect flow happens. 

I am using the Authorization Code Flow method. The redirect URI is set properly in Azure AD and all of the endpoints are set up correctly.

The one thing I have not set up is the "local_o365 | adminconsent" option since I don't think that's strictly necessary for just OIDC authentication. The Azure AD Application has all of the other necessary permissions set properly.

If you don't have the local_o365 | adminconsent set, will the OIDC login button not work correctly? I'm not sure why this won't work :(

I'm on Moodle 3.4.3+ and the latest Moodle 3.4 stable branches of the o365 plugins.

**Comment by jamesmcq** [comment] 2018-08-27 20:06
Hi @upats - are you logged in when you return to the Moodle homepage? If not, can you verify the entire request chain you're seeing? Sometimes redirects happen in the background without being visible. If you're using Chrome, you can verify using the "Network" tab of your browser's developer tools. Be sure to check "Preserve Log".

**Comment by KibosJ** [comment] 2018-10-03 14:17
I'm getting this too, but only when someone tries to log in after clicking on a link in Moodle.

Deleting all and any cookies relating to Moodle allows the user to then sign in.

**Comment by KibosJ** [comment] 2018-10-05 07:36
Until this issue can be resolved I have added this code to the /login/index.php file and that has sorted it.


`// Delete MoodleSession Cookie
if (isset($_COOKIE['MoodleSession'])) {
    unset($_COOKIE['MoodleSession']);
    setcookie('MoodleSession', '', time() - 3600, '/'); // empty value and old timestamp
}`

**Comment by jamesmcq** [comment] 2018-10-25 21:54
Hi all - I'm closing this as it doesn't appear to be something caused by the plugins themselves - possibly is a Moodle core issue. If you have any more information I'd be glad to continue investigation.

**Closed by jamesmcq** 2018-10-25 21:54 UTC
Labels: triaging
