### ISSUE TITLE
Microsoft 365 Teams Theme error with Moodle 4 error

### ISSUE THREAD

**Issue by michaelsmith1234** [microsoft/o365-moodle#2045] opened 2022-05-10 13:05 UTC
error: exception- class'mod_assign_render' not found
Stack trace
line 37 of /theme/boost_o365teams/renderers.php:Error thrown

**Comment by michaelsmith1234** [comment] 2022-05-10 13:06
Microsoft 365 Teams Theme error with Moodle 4 error: exception- class'mod_assign_render' not found
Stack trace
line 37 of /theme/boost_o365teams/renderers.php:Error thrown

**Comment by weilai-irl** [comment] 2022-05-10 13:51
Hi @michaelsmith1234, 

This is duplicate of issue #2032.
It will be fixed when the plugins are upgraded to officially support Moodle 4.0, which is expected in the coming weeks.

Regards,
Lai

**Closed** 2022-05-16 13:35 UTC
Labels: Issue type - enhancement request, Status - PR ready / pending release, Plugin - theme_boost_o365teams
