### ISSUE TITLE
Issue: When attempting the "Azure AD Tenant" we see "Error in API call: The identity of the calling application could not be established."

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1182] opened 2019-12-12 13:25 UTC
We have just deployed the script to create an app in our production environment, then given the admin consent, but when we "Detect" against the "Azure AD Tenant", we see the following error on the GUI:

```
Error in API call: The identity of the calling application could not be established.
```

Initially we made a mistake so deleted the Azure App and re-ran the script, then updated the App-ID and Secret, and reapplied admin consent. The permissions look fine on the Azure App and match our demo tennant permissions. 

In the Moodle logs, we see the follow 2 API errors:

```
local_o365\rest\unified::get_tenant:160: Error response received. Data: Array ( [code] => Authorization_IdentityNotFound [message] => The identity of the calling application could not be established. [innerError] => Array ( [request-id] => bf8cb988-b4e0-471f-a939-2fafdf853c8f [date] => 2019-12-12T13:22:03 ) )
```

```
detect aadtenant graph: Error in API call: The identity of the calling application could not be established. Data: Array ( [file] => /var/www/moodle/local/o365/classes/rest/o365api.php [line] => 288 [message] => Error in API call: The identity of the calling application could not be established. [debuginfo] => [errorcode] => erroro365apibadcall_message [module] => local_o365 )
```

**Comment by swinster** [comment] 2019-12-12 13:30
I guess this is still a permission issue, but I don;t understand how or why, or what we might be able to do to resolve

**Comment by swinster** [comment] 2019-12-12 14:17
Well, amazingly it fixed itself after lunch and a cup of tea :)

I guess there was something that was cached from the previous attempt, but this is not at all clear, so I guess there could be something done to help clear out settings.

**Comment by weilai-irl** [comment] 2021-01-08 16:44
Hi @swinster,

I haven't seen an issue like this myself, fortunately (or unfortunately, pending on where you look at it from).

A possible cause of the issue is the delay on the Microsoft side? The message "The identity of the calling application could not be established" kind of suggests the Graph API doesn't recognise the application details provided. This could be a temporary error.

I'm going to close this one if you don't mind :)

Regards,
Lai

**Closed by weilai-irl** 2021-01-08 16:44 UTC

**Comment by vuknovakovicctd** [comment] 2023-01-23 12:13
Hey guys, I'm having this issue as well, and it IS due to some slow process on azure side.

To reproduce this, delete application from authorised enterprise, wait _some time_(no concrete delay here, I'm waiting about 2 hrs), then authorise api and **immediately** try to call any API by using this app and you will get this error. Then wait _some time_ (again, no concrete delay here either, seems to differ from time to time, but around 30s to a minute seems to work), try calling some API and it will succeed.

However, does anybody know proper sleep interval between authorising the app and using it? Or is there some event that we can subscribe to so we know for sure app has been fully authorised and we can start using it?

Maybe @weilai-irl has encountered this error in the meantime?
