### ISSUE TITLE
Moodle-AzureAD-Script  Error

### ISSUE THREAD

**Issue by jorfernando66** [microsoft/o365-moodle#1262] opened 2020-05-25 21:34 UTC
Hello everyone
I am currently trying to do the integration with Office 365, however when I send the Moodle-AzureAD-Script script to run, I have the error:

Set-AzureADApplicationLogo: Error occurred while executing SetApplicationMainLogo
Code: Request_ResourceNotFound
Message: Resource '8f94d224-48da-411f-8489-68f8c3c5c59e' does not exist or one of its queried reference-property objects are not present.
RequestId: 4955277d-1cd7-4567-9e93-272caf94aa60
DateTimeStamp: Mon, 25 May 2020 16:48:18 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed

Can someone please help me

**Comment by rakidey123** [comment] 2020-05-25 22:48
Set-AzureADApplicationLogo : Error occurred while executing SetApplicationMainLogo
Code: Request_ResourceNotFound
Message: Resource 'a124ed85-7eda-42ed-b7c5-2db5308cb2b0' does not exist or one of its queried reference-property
objects are not present.
RequestId: fc41e115-a500-4b80-b485-e3fc615e938b
DateTimeStamp: Mon, 25 May 2020 22:27:02 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
I get the same error while executing the script, have checked all the Api permission in azure. Kindly help.

**Comment by jorfernando66** [comment] 2020-05-25 23:18
> Set-AzureADApplicationLogo : Error occurred while executing SetApplicationMainLogo
> Code: Request_ResourceNotFound
> Message: Resource 'a124ed85-7eda-42ed-b7c5-2db5308cb2b0' does not exist or one of its queried reference-property
> objects are not present.
> RequestId: fc41e115-a500-4b80-b485-e3fc615e938b
> DateTimeStamp: Mon, 25 May 2020 22:27:02 GMT
> HttpStatusCode: NotFound
> HttpStatusDescription: Not Found
> HttpResponseStatus: Completed
> I get the same error while executing the script, have checked all the Api permission in azure. Kindly help.


Could you fix the error?
I'm going to check the permissions, it seems strange to me, because some time ago I did the same procedure with other Moodle sites, and I had no problem.
Thank you very much for your answer

**Comment by avegys** [comment] 2020-05-26 07:55
Hi @jorfernando66,

Thank you for reported issues. From quick look it seems that the issue is due to delays on Graph API side. We will investigate in more details to see if this is the case.

Best regards,
Andrius

**Comment by rakidey123** [comment] 2020-05-26 10:33
Hello,

I dont know if this will help. 

When executing the script, it returns the above error but returns the client and secret keys. although i went ahead added the keys and when i click on 
"Provide admin consent"  in Local plugin> Microsoft Office 365 Integration as suggested in documentation, it returns "Invalid Endpoint URI received." Of course i understand executing the script in power shell is returning error hence understandable.  

I have also tried adding the app manually in azure active directory, all api permission set "Provide admin"consent" returns a different error code 
"Exception - Call to undefined method auth_oidc\oidcclient::use_chinese_api()".

This has been bugging, Kindly provide a solution. I shall be very thankful.

**Comment by jorfernando66** [comment] 2020-05-26 17:41
> Hi @jorfernando66,
> 
> Thank you for reported issues. From quick look it seems that the issue is due to delays on Graph API side. We will investigate in more details to see if this is the case.
> 
> Best regards,
> Andrius

Thank you very much everyone for the responses
The problem in my opinion is generated by the Microsoft Graph Api, however I have tried to create the application manually, even with the same permissions as those applications that have previously worked with other implementations, but I still have the same error. I do not know what else to do.
I will keep trying.
Please keep us informed.

**Comment by weilai-irl** [comment] 2021-07-26 20:20
Hi all,

The PowerShell script was upgraded in the 3.9.5/3.10.2 release in June 2021. Please upgrade your plugins and confirm if the issue has been fixed in the new version of the script.

I'll leave the issue open for a month, and if no more issue reported, it will be closed.

Regards,
Lai

**Closed** 2021-09-03 21:05 UTC
Labels: Issue type - help wanted, Plugin - local_o365, Status - released / will close soon
