### ISSUE TITLE
Multi tenancy Addition Error Exception - Argument 1 passed to local_o365\rest\o365api::__construct() must be an instance of local_o365\oauth2\token, null given, called in [dirroot]/local/o365/classes/observers.php on line 101

### ISSUE THREAD

**Issue by sam-suresh** [microsoft/o365-moodle#1835] opened 2021-10-08 03:24 UTC
I'm trying to add a new tenant in Moodle.

However, I got an error when adding student tenant:

Steps Followed:

1. Setup Moodle Azure App using PowerShell in STAFF tenant.
2. Enable multi-tenancy in Azure App. 
3. Add MPN ID (as per new requirements) in Azure App. 
4. Add tenant (STAFF) in Moodle 365 setup => OK
5. Add tenant (STUDENT) in Moodle 365 setup => error

`Exception - Argument 1 passed to local_o365\rest\o365api::__construct() must be an instance of local_o365\oauth2\token, null given, called in [dirroot]/local/o365/classes/observers.php on line 101`

Appreciate any input on this matter.

**Comment by sam-suresh** [comment] 2021-10-21 01:29
Moodle 3.9.9+  20210827
OpenID Connect 3.9.5  2020071506
Microsoft 365 Integrationlocal_o365 | 3.9.6. 2020071509

**Comment by nenorojas** [comment] 2021-11-05 10:06
Hi @sam-suresh, 

Thank you for reporting this and apologies for the delay. We confirm that there is an issue with Moodle 3.9 onwards with the steps to add more tenants via the page the /local/o365/acp.php?mode=tenants. We have confirmed that the process is still working for the version of plugin in Moodle 3.8. I will close this issue as this is for Moodle 3.9 and we will provide more details and fix on this issue for Moodle 3.11 https://github.com/microsoft/o365-moodle/issues/1863. 

Regards

Oswaldo

**Closed by nenorojas** 2021-11-05 10:06 UTC
Labels: Plugin - local_o365

**Comment by weilai-irl** [comment] 2021-11-05 22:12
Hi @sam-suresh,

I'm not 100% sure if this is caused by the issue reported in #1863, but there's a large chance that they are related. Let's see if the related issue can be fixed by the proposed solution, and we can revisit this issue afterwards.

Regards,
Lai
