### ISSUE TITLE
Poor error when attempting to log in as an administrator

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1177] opened 2019-12-10 23:33 UTC
Just noted that some cached credentials from my Azure or O365 admin login caused a horrible error:

---

There was a problem logging you in. Please contact your administrator for assistance.

More information about this error
Debug info: 2
Error code: errorauthgeneral
Stack trace:

    line 494 of /auth/oidc/classes/loginflow/authcode.php: moodle_exception thrown
    line 269 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handlelogin()
    line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
    line 105 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
    line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect() 

![image](https://user-images.githubusercontent.com/8142964/70578369-6b2ebb80-1ba5-11ea-8e6e-08e69a8fbb69.png)

The link directs you to https://docs.moodle.org/36/en/error/auth_oidc/errorauthgeneral, which doesn't exist.

**Comment by swinster** [comment] 2020-10-18 12:05
Still seeing this

**Comment by swinster** [comment] 2020-10-18 12:17
I tried to create a new admin user , but can't seem to unlink the old one. Therefore we are now getting:

```
Output buffer: <div class="notifytiny debuggingmessage" data-rel="debugging">Error: mdb->get_record() found more than one record!<ul style="text-align: left" data-rel="backtrace"><li>line 1599 of /lib/dml/moodle_database.php: call to debugging()</li><li>line 400 of /auth/oidc/classes/loginflow/authcode.php: call to moodle_database->get_record_sql()</li><li>line 452 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->check_objects()</li><li>line 269 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handlelogin()</li><li>line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()</li><li>line 165 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()</li><li>line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()</li></ul></div>

Checking out the `MS365 pluggin --> Manage User Connections` we see:

![image](https://user-images.githubusercontent.com/8142964/96367210-4cde0880-1144-11eb-9d5a-7183349e47e4.png)

**Comment by swinster** [comment] 2020-10-18 12:40
I could not seemingly unlink the original default admin user from the OpenID login no matter what I did. I eventually deleted the new user, renamed the old admin user account to the name of the Azure AD user, resynced, then finally could log in.

**Comment by weilai-irl** [comment] 2022-02-23 16:12
Hi @swinster,

Sorry for taking so long to get back to you.

Could you explain how this issue can be reproduced please. I suppose it's not specific to admin account, rather it's about the ability to unlink any account? I'm wondering how these accounts are connected in the first place.

Regards,
Lai

**Comment by swinster** [comment] 2022-02-23 19:27
Unfortunately, I can't reproduce as we were forced to move away from Moodle.

**Comment by weilai-irl** [comment] 2022-02-23 21:27
Sorry to see you moved away from Moodle.
I'll close this issue in that case as I can't reproduce it either.

**Closed by weilai-irl** 2022-02-23 21:27 UTC
Labels: Issue type - bug, Plugin - auth_oidc, Status - queued / not yet started
