### ISSUE TITLE
M365 Group Membership User Restriction Not Working

### ISSUE THREAD

**Issue by r1chm0** [microsoft/o365-moodle#1818] opened 2021-09-20 08:29 UTC
OpenID Connect - auth_oidc - 3.9.5 - 2020071506
Microsoft 365 Integration - local_o365 - 3.9.6 - 2020071509

When the user restriction is set to "Microsoft 365 Group Membership", synced AAD users that are non-existent in Moodle are not being created.  The task log error says "Cannot create user because they do not meet the configured user creation restrictions."

Affected users are indeed members of the specified M365 dynamic group.  The group DisplayName is used as the value.  When ObjectId or EmailAddress are used, errors appear in the Moodle "site errors" log, so it appears to be recognizing the group when referred to correctly.

No restrictions have been set in in auth_oidc.

Creation behaviour is as expected when another user restriction type is chosen, such as "Username (UPN)."

Any ideas?  Thanks.

**Comment by mmulrthelp** [comment] 2021-09-20 08:38
@r1chm0 is this because of the issue I spotted https://github.com/microsoft/o365-moodle/issues/1719 are you using nested groups, if yes there's a fix which is not yet in the core release code.

**Comment by weilai-irl** [comment] 2021-09-20 08:40
Hi @r1chm0,

As @mmulrthelp pointed out, this is the same as the linked issue. The solution will be release in the coming weeks, or you can apply the fix in the pull request linked to the related issue.

Regards,
Lai

**Comment by r1chm0** [comment] 2021-09-20 08:43
@mmulrthelp, @weilai-irl , this is not a nested group.  The group is dynamic and therefore cannot have nesting.  I tried a static M365 group with no nesting and observed the same results.

**Comment by weilai-irl** [comment] 2021-09-20 08:48
Hi @r1chm0,

The "Microsoft 365 Group Membership" user creation restriction expect the exact case-sensitive group name to be used, without wildcard or regex. Could you check the the settings please. Also, assuming you are using "application access" connection method, could you ensure at least of the following permissions is granted for the Azure app please:
- GroupMember.Read.All,
- Group.Read.All,
- Directory.Read.All,
- Group.ReadWrite.All,
- Directory.ReadWrite.All

Regards,
Lai

**Comment by j3ffb** [comment] 2021-09-27 16:19
I can across this issue as well.

To fix it I had to change this line https://github.com/microsoft/o365-moodle/blob/130d3e3a9e96158000b1f1457282b9ab4c86d3b6/local/o365/classes/feature/usersync/main.php#L633

To
`if ($group['id'] === $usergroup['id']) {`

**Comment by thebenkahn** [comment] 2021-09-29 17:46
Hi Wei

I can confirm the same behavior on a test site/Azure instance. I've created an basic MS 365 Group and added a single user to it as a member. Then copied the name of the Group into the User Creation Restriction field and run the sync. I see the user skipped because they do not meet the restriction.

This is on Moodle 3.10.5 and O365 plugins version: 3.10.3 2020110904

We are using Application Access and  have these permissions granted:

Group.ReadWrite.All
Directory.Read.All
Group.ReadWrite.All
Directory.ReadWrite.All

Please let me know if we can help test anything. We can probably try @j3ffb's fix on this site. 

Log out put (removed domain info)

```
........ Syncing user steve.bennet@********
......... User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.

```

![Snag_596b162](https://user-images.githubusercontent.com/30783598/135320112-4db66fe9-1860-47fd-a927-213f087e76c6.png)

![Snag_5986fac](https://user-images.githubusercontent.com/30783598/135320391-3f45113c-f2c6-4d46-ad5e-1878f972f445.png)

**Comment by thebenkahn** [comment] 2021-09-29 18:06
Just a quick addendum: we ended up applying @j3ffb's fix to a client site that was having this issue with a Dynamic 365 Group and that resolved the issue.

**Comment by weilai-irl** [comment] 2021-09-29 21:18
Hi all,

This is a bug in the current version of the plugin. The cause of this bug is we merged two very similar functions that get list of groups for the given user AAD ID in the last release, without realising that one function returned only ID of the group, while the other returned an object representing the complete group resource type.

There are two symptoms of the issue:

1. Group user creation restriction doesn't work if the user is the member of a child group of the configured group. This was reported #1719.
2. Group user creation restriction doesn't work on dynamic groups, which is reported here.

The fix that @j3ffb proposed would fix issue 2, but will not fix issue 1; however, the change in the linked pull request would solve both issues.

Technically, the pull request uses a different Graph API https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=http to get the groups of an AAD user, and returns only group IDs (fixing issue 2). The API is transitive by nature as well (fixing issue 1).

I hope I explained it clear enough. The solution will be merged, tested, and included in the next release in October.

Regards,
Lai

**Closed** 2021-12-06 14:52 UTC
Labels: Issue type - bug, Feature - user sync, Plugin - local_o365, Status - released / will close soon
