### ISSUE TITLE
Users being told the must change password 

### ISSUE THREAD

**Issue by rmeske** [microsoft/o365-moodle#1616] opened 2021-03-10 01:04 UTC
We were able to successfully sync our AD to Moodle, but when a user attempts to log in they are receiving the error:

> You cannot proceed without changing your password, however there is no available page for changing it. Please contact your Moodle Administrator.

We are not finding any settings in Moodle to force a password reset.  

We are using: 
Moodle 3.9.4
Open ID Connect 3.9.3
Microsoft 365 Integration 3.9.3

We did modify unified.php to ignore roles so that we could get a successful sync.

**Comment by kkiiskin** [comment] 2021-03-25 09:00
Hi

is the user older one that used to have a different auth method previously?

We have had cases where some users have had force password change enabled before changing them to using oidc.
We then just change the setting to database table mdl_user_preferences (set value = 0 where name = 'auth_forcepasswordchange').

**Comment by rmeske** [comment] 2021-03-25 17:28
All accounts were new.  We only found the one account that had this, all the others came through successfully.  

Still don't know why that user came across that way, but no one else reported an issue yet.

**Comment by weilai-irl** [comment] 2021-03-29 16:31
Hi @rmeske,

I don't think this is caused by auth_oidc plugin. It's more to do with how the user accounts were created.

Normally Moodle would ask user to change password if there's a record in mdl_user_preferences table with userid = USERID and name = "auth_forcepasswordchange" and value = "1", so to solve the issue, you will need to find these records, and delete them from the table.

auth_oidc doesn't support changing password, and doesn't have a logic to set this field. However, if the field for the user was set by other sources, e.g. by CSV user upload, or if the user was set to be required to change password when using auth_manual, then the user's account was changed to use auth_oidc, auth_oidc doesn't have logic to delete it either.

In any case, this wouldn't have been set by auth_oidc, and can't be solved by auth_oidc. The preference needs to be cleaned manually or using scripts from the database.

Regards,
Lai

**Comment by rmeske** [comment] 2021-03-29 16:37
I would like to make it clear, there were no user accounts other then the admin account registered in Moodle.  This was the initial load of user accounts so it could not have been set by Moodle.  So something happened during that initial sync that caused this, but so far it has not occurred for any other users.

**Comment by weilai-irl** [comment] 2021-03-30 09:01
Hi @rmeske,

After a review in the code, I confirm there is actually a logic in the user sync task that may, in very rare cases, set the force reset password preferences for the newly created user. The code is at https://github.com/microsoft/o365-moodle/blob/6a210db3779a6da9db544139ccb4e0d12873d199/local/o365/classes/feature/usersync/main.php#L706, and the code looks like this:
```
        if (!empty($CFG->{'auth_'.$newuser->auth.'_forcechangepassword'})) {
            set_user_preference('auth_forcepasswordchange', 1, $user);
        }
```
It basically says, if $CFG->auth_oidc_forcechangepassword is set and contains a value that's not false, null or 0, the user will get preference set to force reset password on the next login.

I checked the code and there's no logic to set $CFG->auth_oidc_forcechangepassword in any plugin, so it should never be triggered. Could you check on your site to confirm if this configuration variable is set please (either in config.php, or in the mdl_config table). If it's set, please unset it.

I also confirm that this part of code was copied directly from the create_user_record() function in lib/moodlelib.php. While the logic makes sense in original function, it doesn't in our case because auth_oidc doesn't support resetting user password. I'm going to remove it in the upcoming release in May 2021.

Regards,
Lai

**Comment by rmeske** [comment] 2021-04-12 22:11
Hi Lai,

I checked the configuration file and that variable did exist in it.  So to further debug I setup a test server to create the sequence.  What I found is:

  1.  Prior to setting up OpenID and Office 365 Integration I had created a few users with the manual authentication method to test the sync matching.  Some of those users had never logged in to Moodle and those accounts had “Force password change” enabled.
  2.  I then installed the OpenID Connect and Office 356 Integration plugins and configured them
  3.  When the sync completed the users that had the “Force password change” enabled still had it set.
  4.  When those users logged in they received the message they had to change their password but could not as I had reported previously.

So it seem that the issue is in the sync code.  If an existing user is matched with an Azure user, the “Force password change” it should likely be disabled.  The sync ync settings that I had set are:

  *   Match preexisting Moodle users with same-named accounts in Azure AD
  *   Switch matched users to Microsoft 365 (OpenID Connect) authentication
  *   Assign users to application during sync

Best regards,
Ron

From: Lai Wei ***@***.***>
Reply-To: microsoft/o365-moodle ***@***.***>
Date: Tuesday, March 30, 2021 at 2:01 AM
To: microsoft/o365-moodle ***@***.***>
Cc: Ron - TSD ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/o365-moodle] Users being told the must change password (#1616)


Hi @rmeske<https://github.com/rmeske>,

After a review in the code, I confirm there is actually a logic in the user sync task that may, in very rare cases, set the force reset password preferences for the newly created user. The code is at https://github.com/microsoft/o365-moodle/blob/6a210db3779a6da9db544139ccb4e0d12873d199/local/o365/classes/feature/usersync/main.php#L706, and the code looks like this:

        if (!empty($CFG->{'auth_'.$newuser->auth.'_forcechangepassword'})) {

            set_user_preference('auth_forcepasswordchange', 1, $user);

        }

It basically says, if $CFG->auth_oidc_forcechangepassword is set and contains a value that's not false, null or 0, the user will get preference set to force reset password on the next login.

I checked the code and there's no logic to set $CFG->auth_oidc_forcechangepassword in any plugin, so it should never be triggered. Could you check on your site to confirm if this configuration variable is set please (either in config.php, or in the mdl_config table). If it's set, please unset it.

I also confirm that this part of code was copied directly from the create_user_record() function in lib/moodlelib.php. While the logic makes sense in original function, it doesn't in our case because auth_oidc doesn't support resetting user password. I'm going to remove it in the upcoming release in May 2021.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-05-26 16:22
Hi @rmeske,

Thank you for your explanation. I confirm in the case you described is quite valid. I have updated the pull request to force unset password change preference when converting a user to use auth_oidc during user sync.

The change will be included in the next release of the plugin in June 2021.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-06-29 11:57
Hi all,

@rmeske, the code change mentioned in my previous comments has been included in the latest release.

I'll close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 11:57 UTC
Labels: triaged
