### ISSUE TITLE
AD Users won't sync if "Perform a full sync each run" is disabled

### ISSUE THREAD

**Issue by rodrigolangella** [microsoft/o365-moodle#1322] opened 2020-07-20 02:49 UTC
I'm just getting a new Moodle instance done but it seems I'm not able to sync users from AzureAD unless I check Perform a full sync each run. 

Got all **Setup** tab done and green,  checked "Perform a full sync each run" and setup "User Creation Restriction" to a specific group in AD and it sync all users from this group just fine, no problems.  Then I unchecked "Perform a full sync..." to only sync users modified in AzureAD and it seems when it syncs its not finding new users of the group.

Here is the log....

Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 12:00:16. Current memory use 23.8MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
... used 6 dbqueries
... used 6.7201969623566 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)

I'm running Moodle 3.9 and Office 365 plugin version 2020071500

**Comment by rodrigolangella** [comment] 2020-07-20 02:53
Update 1 -  When I create new users it syncs just fine, however it wont sync if a existent user is added to the sync restriction group

**Comment by weilai-irl** [comment] 2020-07-20 08:36
Hi @rodrigolangella 

We will try to reproduce the issue and get back to you soon.

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-04 21:35
Hi @rodrigolangella,

Sorry for not getting back to you sooner.

The root of the issue is, group membership of an Azure AD user is not a "property" of the user resource, therefore changes made user group membership will not be returned in a delta sync. This is how delta sync is designed, and the Moodle plugin wouldn't have other ways to get delta user changes.

References:
 - Description of user resource type, in particular, its properties: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
 - User delta: https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http
 - General information on delta sync in Graph API: https://docs.microsoft.com/en-us/graph/delta-query-overview

As there's nothing we can do here, I'm going to close this issue.

Regards,
Lai

**Closed by weilai-irl** 2020-11-04 21:35 UTC
