### ISSUE TITLE
All day events in Outlook spanning 2 days in Moodle

### ISSUE THREAD

**Issue by ghost** [microsoft/o365-moodle#1434] opened 2020-10-12 12:15 UTC
Moodle 3.8.3 (Build: 20200511)
Microsoft Office 365 Integration local_o365 | 3.8.0.4 (2020020306)
Office 365 Integration local_office365 | 3.8.0.4 (2020020304)
OpenID Connect auth_oidc | 3.8.0.3 (2020020303)
Microsoft block block_microsoft | 3.8.0.3 (2020020303)

Creating an all day event in Outlook
![o365_all_day_event_1](https://user-images.githubusercontent.com/57189646/95744132-e008d100-0c60-11eb-9d44-f7618907957b.png)

results in an event spanning 2 days in Moodle
![o365_all_day_event_2](https://user-images.githubusercontent.com/57189646/95744176-f1ea7400-0c60-11eb-806e-3332a9a2ac7e.png)

from 8pm the previous day until 8pm on actual day
![o365_all_day_event_3](https://user-images.githubusercontent.com/57189646/95744211-fd3d9f80-0c60-11eb-948c-92f4eb4bec3b.png)

Moodle default and user timezone set to America/New York
User Outlook calendar timezone set to Eastern Time

**Comment by weilai-irl** [comment] 2021-07-26 22:51
This could be caused by timezone. I'll need to investigate and try to reproduce it.

**Comment by chrisoconnor** [comment] 2022-04-06 10:44
Hi
This has has been merged into the release 3.9.9, 3.10.6, 3.11.3 on 06/04/2022.
All events are added in moodle using using the start and end date of the moolde user timezone.

I'll close this ticket.

**Closed by chrisoconnor** 2022-04-06 10:44 UTC
Labels: Issue type - bug, Plugin - local_o365, Feature - calender sync
