### ISSUE TITLE
"Clean up OIDC state and invalid token" Task Issue

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#1679] opened 2021-05-15 02:27 UTC
There is an issue with "Clean up OIDC state and invalid token" schedule task. It runs but always get failed. Please check the attached pictures.

![task_issue](https://user-images.githubusercontent.com/18500882/118345585-306d4780-b53e-11eb-9452-2b846e0234db.png)
![auth_oidc_task_error](https://user-images.githubusercontent.com/18500882/118345586-32370b00-b53e-11eb-9571-6bc9ea3c2f04.png)

**Comment by grantcolin** [comment] 2021-05-17 07:39
Fix is here:

https://github.com/microsoft/o365-moodle/commit/27cd3b72a748849a81f16c16071b153a1c64c823

**Comment by weilai-irl** [comment] 2021-05-28 08:44
This is duplicate of #1638 and will be fixed when the pull request linked to the issue are merged, in the June 2021 release.

**Comment by weilai-irl** [comment] 2021-06-29 16:36
Hi all,

The issue is fixed in the latest release. I'll close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 16:36 UTC

**Comment by aboarken** [comment] 2021-10-02 09:57
@weilai-irl Thank you.
