### ISSUE TITLE
Quick question in regard to SDS?

### ISSUE THREAD

**Issue by bradnielsen2981** [microsoft/o365-moodle#1263] opened 2020-05-26 06:36 UTC
It's been a while since I set up School Data Sync. For some reason I don't see any schools available in School Data Sync. I do on our Production Server, but not on our Staging Server.

They are both connected to our Office 365 environment, and there is an Registered App set up for both Moodle sites. What am I doing wrong?

Do you need to do anything within School Data Sync to make it available?

**Comment by ArtAcademyofCincinnati** [comment] 2020-07-17 02:40
Same here, SDS is setup and shows ready for data, and we have test data present.  Logs show the sync runs but nothing is written.

**Comment by cbrherms** [comment] 2020-07-27 09:50
I've just been getting ready to start syncing our new modules for the next year and come to find "You do not have any schools available in School data sync" in the SDS preview panel on moodle.... strange, and also slightly worrying. 
Did any of you get this sorted in the end?

**Comment by cbrherms** [comment] 2020-07-27 09:56
Just checking through logs, and when SDS sync tasc is run output is as follows:

```
Execute scheduled task: Sync with SDS (local_o365\feature\sds\task\sync)
... started 03:15:01. Current memory use 17.1MB.
Could not construct system API user token for SDS sync task.
Could not construct API client for SDS task, so exiting.
... used 0 dbqueries
... used 0.0078070163726807 seconds
Scheduled task complete: Sync with SDS (local_o365\feature\sds\task\sync)
```

Has recent changes to the teams sync integration broken SDS?

**Comment by bradnielsen2981** [comment] 2020-07-27 10:02
Do you have the SDS application on Office 365 linked to the test server? It should show up in the SDS tab on Moodle. This works for me but using moodle 3 5. I havent tried later versions I actually want to develop the code for the SDS but my institution wont set up another SDS to test with, and apparently the SDS application on Office 365 can only point to one external server which is my production server. I really need to set up a test office 365 environment but I dont know how...



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ArtAcademyofCincinnati** [comment] 2020-07-29 03:48
@bradnielsen2981 when you say "Do you have the SDS application on Office 365 linked to the test server", where exactly do you perform this action?  No where in the SDS portal that I can tell indicates a linked or connected external server (i.e. the Moodle server).

**Comment by bradnielsen2981** [comment] 2020-07-29 04:12
Sorry I didnt set it up, so Im just assuming the SDS application has a reply url set up for it. It's definitely been linked somewhere to our Moodle Production site.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by cbrherms** [comment] 2020-07-29 07:35
I documented my issue and findings in https://github.com/microsoft/o365-moodle/issues/1330 in the end. 
May have been slightly different to others. 
Are you all updated to the latest version of o365-moodle? (3.7.0.7)

**Comment by bradnielsen2981** [comment] 2021-01-19 00:34
For anyone who would like SDS updated code: I have fixed it up on my github repository. Im not ready to make a pull request - I'm a bit of an amateur, and there are still some tests for me to run. But it seems to work fine for me.
https://github.com/bradnielsen2981/o365-moodle

**Comment by weilai-irl** [comment] 2021-11-11 10:42
Hi all,

I can confirm the original issue reported was caused by the existing SDS integration feature makes use of the legacy SDS API, and depend on System API user connection method.

This will be fixed in the upcoming December release. More details will be made available in the release note.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-12-07 16:28
Hi all,

We have just made a release (3.9.8, 3.10.5, and 3.11.2) of the plugins which contains major changes in the SDS feature. Please refer to documentation at https://docs.moodle.org/311/en/Microsoft_365#School_Data_Sync_.28SDS.29 for feature details.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai

**Closed** 2022-01-06 15:36 UTC
Labels: Issue type - bug, Issue type - help wanted, Plugin - local_o365, Status - PR ready / pending release, Feature - SDS
