### ISSUE TITLE
Multitenant: Provided Authorization Code is intended to use against other tenant

### ISSUE THREAD

**Issue by sam-suresh** [microsoft/o365-moodle#1863] opened 2021-10-29 04:49 UTC
Dear team,

I'm having an issue with the Multitenancy setup. So today I tried using the latest version and a fresh install to test it out. 

Moodle: moodle-3.11.3
0365 / oidc Plugin: 3.11.3

Steps Followed:

1. Configure the Azure app using powershell (Success)
2. Enable multitenancy in the app (success)
2. Configure 0365 plugin in Moodle (success)
3. Add new tenant failed:

`Error in OpenID Connect: AADSTS700005: Provided Authorization Code is intended to use against other tenant, thus rejected. Trace ID: 367ec50b-a4ac-4fb3-9d0a-6a417fc91400 Correlation ID: f890ba8b-8476-40ce-85f6-7590c1b173d4 Timestamp: 2021-10-29 04:25:27Z`

After clicking Add new tenant, I logged in using Global Admin of the SECOND tenant. Tried too many times with no way out. 

Appreciate any help on this matter.

**Comment by sam-suresh** [comment] 2021-11-02 01:10
Any updated on this issue? Thanks in advance

**Comment by weilai-irl** [comment] 2021-11-05 22:07
Hi @sam-suresh,

We have found the root of the issue, and a fix has been prepared in the linked pull requests. They will be tested and included in the next release, scheduled for December.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-12-07 15:55
Hi @sam-suresh,

New version of the plugins that contain the fix to the multi tenant issue has just been release. Please upgrade your plugins and confirm if they fix your issues.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai

**Comment by sam-suresh** [comment] 2021-12-09 05:08
@weilai-irl 

Tested and working now. 

Thank you

**Comment by sam-suresh** [comment] 2021-12-10 02:16
@weilai-irl 

I am able to add a new tenant now. However, the users of the new tenant are unable to log in:

`Error in API call: Resource '7f0d1c16-a76b-4b32-8317-dfc2ec5c9cba' does not exist or one of its queried reference-property objects are not present.`

users tenant one (the default) able to login
users from tenant 2 get error

I did some digging but couldn't find what is wrong. Looks like the application in new tenant does not exist? I also added new tenant global admin as a owner of this app in azure.

**Comment by weilai-irl** [comment] 2021-12-10 09:18
Hi @sam-suresh,

Could you turn debugging on and see on which line the error was thrown please.

Regards,
Lai

**Comment by sam-suresh** [comment] 2021-12-11 00:55
@weilai-irl Here it is;
<img width="1125" alt="Screenshot 2021-12-11 at 8 54 30 AM" src="https://user-images.githubusercontent.com/5198092/145657816-f6977564-e1f2-4334-80c2-9a73b02354d7.png">

**Comment by sam-suresh** [comment] 2021-12-13 13:33
@weilai-irl After a bit of digging this is what I found. 

Authentication and sync with the first ( default ) tenant working fine. 
Authenticating using a second tenant (which successfully added) return this error:

`Error in API call: Resource '32000718-b519-4fb1-a9c9-4b8cdf8dde1c' does not exist or one of its queried reference-property objects are not present.`

The resource above `32000718-b519-4fb1-a9c9-4b8cdf8dde1c` is the user id that trying to log in using the second tenant. So technically it doesn't exist in the first tenant but this user only exists in the second tenant. 


This is the debug data
`{
   "moodlecfg":{
      "dbtype":"mysqli",
      "debug":32767,
      "debugdisplay":"1",
      "debugdeveloper":true,
      "auth":"oidc",
      "timezone":"Asia\/Kuala_Lumpur",
      "forcetimezone":"99",
      "authpreventaccountcreation":"0",
      "alternateloginurl":"",
      "release":"3.9.11 (Build: 20211108)",
      "version":"2020061511",
      "localo365forcelegacyapi":0
   },
   "plugin_data":{
      "auth_oidc":{
         "version":"2020071541",
         "enabled":1,
         "authendpoint":"https:\/\/login.microsoftonline.com\/common\/oauth2\/authorize",
         "tokenendpoint":"https:\/\/login.microsoftonline.com\/common\/oauth2\/token",
         "oidcresource":"https:\/\/graph.microsoft.com",
         "autoappend":"",
         "domainhint":"",
         "loginflow":"authcode",
         "debugmode":"0"
      },
      "block_microsoft":{
         "version":"2020071540",
         "enabled":1,
         "showo365download":"1",
         "settings_showonenotenotebook":"1",
         "settings_showoutlooksync":"0",
         "settings_showpreferences":"1",
         "settings_showo365connect":"1",
         "settings_showmanageo365conection":"0",
         "settings_showcoursespsite":"1"
      },
      "filter_oembed":{
         "version":"2019112600",
         "enabled":1,
         "o365video":null,
         "officemix":null,
         "sway":null,
         "provider_docsdotcom_enabled":null
      },
      "local_microsoftservices":{
         "version":"null",
         "enabled":0
      },
      "local_msaccount":{
         "version":"null",
         "enabled":0
      },
      "local_o365":{
         "version":"2020071540",
         "enabled":0,
         "aadsync":"create,update,suspend,delete,reenable,disabledsync,match,matchswitchauth,appassign,photosync,photosynconlogin",
         "aadtenant":"sdtaylorsedu.onmicrosoft.com",
         "azuresetupresult":"O:8:\"stdClass\":3:{s:9:\"legacyapi\";O:8:\"stdClass\":2:{s:12:\"missingperms\";a:4:{s:30:\"Windows Azure Active Directory\";a:3:{s:18:\"Directory.Read.All\";s:19:\"Read directory data\";s:26:\"Directory.AccessAsUser.All\";s:42:\"Access the directory as the signed-in user\";s:13:\"User.Read.All\";s:29:\"Read all users' full profiles\";}s:28:\"Office 365 SharePoint Online\";a:6:{s:13:\"AllSites.Read\";s:34:\"Read items in all site collections\";s:14:\"AllSites.Write\";s:44:\"Read and write items in all site collections\";s:15:\"AllSites.Manage\";s:54:\"Read and write items and lists in all site collections\";s:20:\"AllSites.FullControl\";s:41:\"Have full control of all site collections\";s:12:\"MyFiles.Read\";s:15:\"Read user files\";s:13:\"MyFiles.Write\";s:25:\"Read and write user files\";}s:26:\"Office 365 Exchange Online\";a:1:{s:19:\"Calendars.ReadWrite\";s:29:\"Read and write user calendars\";}s:7:\"OneNote\";a:2:{s:15:\"Notes.ReadWrite\";s:33:\"View and modify OneNote notebooks\";s:12:\"Notes.Create\";s:33:\"Create pages in OneNote notebooks\";}}s:8:\"haswrite\";b:0;}s:7:\"appdata\";O:8:\"stdClass\":1:{s:8:\"replyurl\";O:8:\"stdClass\":3:{s:7:\"correct\";b:1;s:8:\"detected\";s:186:\"https:\/\/times-dev.taylors.edu.my\/local\/o365\/sso_end.php, https:\/\/times-dev.taylors.edu.my\/auth\/oidc\/, https:\/\/token.botframework.com\/.auth\/web\/redirect, https:\/\/times-dev.taylors.edu.my\/\";s:8:\"intended\";s:43:\"https:\/\/times-dev.taylors.edu.my\/auth\/oidc\/\";}}s:10:\"unifiedapi\";O:8:\"stdClass\":4:{s:6:\"active\";b:1;s:15:\"missingappperms\";a:2:{s:18:\"EduRoster.Read.All\";s:30:\"Read the organization's roster\";s:18:\"Member.Read.Hidden\";s:27:\"Read all hidden memberships\";}s:8:\"apptoken\";b:1;s:12:\"missingperms\";a:0:{}}}",
         "chineseapi":null,
         "createteams":"off",
         "debugmode":null,
         "enableunifiedapi":null,
         "disablegraphapi":null,
         "odburl":"sdtaylorsedu-my.sharepoint.com",
         "photoexpire":null,
         "usersynccreationrestriction":"a:3:{s:11:\"remotefield\";s:0:\"\";s:5:\"value\";s:0:\"\";s:8:\"useregex\";b:0;}",
         "sharepoint_initialized":null,
         "task_usersync_lastskiptoken":null,
         "unifiedapiactive":"1"
      },
      "local_office365":{
         "version":"2020071540",
         "enabled":0
      },
      "local_onenote":{
         "version":"2020071540",
         "enabled":0
      },
      "assignsubmission_onenote":{
         "version":"null",
         "enabled":0
      },
      "assignfeedback_onenote":{
         "version":"null",
         "enabled":0
      },
      "repository_office365":{
         "version":"2020071540",
         "enabled":0
      },
      "repository_onenote":{
         "version":"null",
         "enabled":0
      }
   }
}`

**Comment by sam-suresh** [comment] 2021-12-14 08:57
Dear @weilai-irl 

Did you get a chance to look into this issue? This has been a pressing issue for now.

**Comment by weilai-irl** [comment] 2021-12-14 12:08
Hi @sam-suresh,

You may be affected by an issue that we spotted last week after the latest release. The issue is documented in #1918. 

Could you provide the userprinciplename (UPN) of the user from the additional tenant (just the domain part), and the tenant name listed on the multitenancy configuration page (https://url.to.moodle/local/o365/acp.php?mode=tenants) please.

Once confirmed it's the same issue, I can provide you a temporary solution before the issue is properly fixed.

Regards,
Lai

**Comment by sam-suresh** [comment] 2021-12-15 00:08
@weilai-irl 

I was reading that issue yesterday and changed the tenant name in SQL from acme.onmicrosoft.com to acme.edu.my. 
The UPN is foo@acme.edu.my and its working now. Yet to test syncronization.

**Comment by weilai-irl** [comment] 2021-12-15 11:22
Hi @sam-suresh,

Thank you for your confirmation. It all makes sense now.

FYI, if you expect profile field mapping in the auth_oidc plugin configuration to work on users from additional tenants, I'm afraid you will be disappointed. The Azure app created for the integration is for the hosting tenant only, and it will not have any permission in the additional tenants configured. Therefore the integration will have no permission to make any request in the additional tenants to get user profile data. The only user profile details that Moodle can obtain for users from additional tenants are those claims in the ID token on successful login, i.e. first name, last name, upn, ID number, and email. If you have field mapping configured for any of these fields, they will be mapped on user login (and not the user sync task).

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-01-06 15:38
Hi @sam-suresh,

Happy New Year.

Could you confirm if you are happy to close this issue please. 

Regards,
Lai

**Closed** 2022-02-08 16:30 UTC
Labels: Issue type - bug, Plugin - auth_oidc, Plugin - local_o365, Status - PR ready / pending release, Feature - multi tenants
