### ISSUE TITLE
Moodle Tab open links within Teams

### ISSUE THREAD

**Issue by StevenC365** [microsoft/o365-moodle#1149] opened 2019-09-11 08:37 UTC
When using the Moodle tab opening any link (e.g. to an attached document) will open a web browser (and so require re-authentication from the desktop app). Please provide an option to remain in Teams.
The website tab does keep these within the Teams experience so provides a better experience, but without SSO.

**Comment by jamesmcq** [comment] 2019-11-08 10:48
@weilai-irl Do you know if links (like an attached document as mentioned) can be opened in the desktop app? I'm not sure this is something that we can solve but I'd like your opinion.

**Comment by weilai-irl** [comment] 2021-07-07 20:42
Hi @StevenC365,

I know this was reported long time ago, and I'm sorry for not getting back to you sooner.

I'm afraid the required behaviour may not be possible. A teams tab in the mobile/desktop app works like an embedded browser, but it certain actions such as download cannot be supported in it. In fact, to maintain the unification of Moodle tab UI in Teams tab, only mod_assign and mod_quiz are designed to show inside the Moodle tab; all other activity types will be opened in external browsers. This is by design on request from the Microsoft Education team.

I'll close this issue for now.

Regards,
Lai

**Closed by weilai-irl** 2021-07-07 20:42 UTC
