### ISSUE TITLE
Sync users with Azure AD task (token problems?)

### ISSUE THREAD

**Issue by sgodbehere01** [microsoft/o365-moodle#1324] opened 2020-07-23 13:56 UTC
Hi there,

We have an office 365 integration set-up with the sync settings set to as follows:
Perform a full sync each run
Match preexisting Moodle users with same-named accounts in Azure AD
Assign users to application during sync 

The integration seems to be working, users can both be manually linked via "user matching" in the advanced area of the office integration plug-in or they can manually do this themselves via the "Microsoft" block, however trying to get the sync to do this automatically seems to fail, with "Matched with existing user. Awaiting completion." appearing for the matched users for their connection status. Logging in as one of these users has the Microsoft block state they are simply "not connected" rather than "almost connected". I believe this means the "Assign users to application during sync" part of the sync is failing?

Running the o365 sync task manually results in the following output repeatedly for each user: 

......... Syncing user (username)
......... Assigning Moodle user 20622 (objectid 31627631-c0ae-4466-88aa-4ec0f1a503fb) to application
**......... Could not assign user (username) Reason: No token available for usersync**
......... Found a user in Azure AD that seems to match a user in Moodle
......... moodle username: (matching username), aad upn: (username)
......... User is already matched.
......... User is now synced.

Checking the Moodle logs also produces a similar token related error repeatedly 
![Screenshot_2020-07-23 Moodle Logs Page 4](https://user-images.githubusercontent.com/31889885/88294308-fce1d800-ccf3-11ea-8520-c0e3bea165e0.png)

This looks similar to the issue raised here: https://github.com/microsoft/o365-moodle/issues/1300 however in this case it seems the issue occurs from the beginning, rather than working for the initial 100 users. We're also not looking to change the authentication method to OIDC, just have the link established. 

Does anyone have any ideas what the problem may be? Let me know if you need any more details or would like me to try anything. 

Kind regards,

Sam

**Comment by nenorojas** [comment] 2020-07-23 17:15
Hi @sgodbehere01, 

What's the Moodle version and local_o365 plugin version being used? 
What's the connection being used: application access or system api user?
When you click on very setup /admin/settings.php?section=local_o365, does it return that all items are correct?

Regards

**Comment by CarrieNZ** [comment] 2020-07-24 04:22
I'm also experiencing this after upgrading to 3.7.0.7 last night, application assignment fails, user token renewal fails.
Our Azure guru has been through the config and all statuses at both ends show as good.

**Comment by weilai-irl** [comment] 2020-07-24 12:49
@sgodbehere01 

Hi Sam,

Thank you for reporting the issue.

I see there are two issues in your report:
1. Cannot assign user to application when running the "Sync users with Azure AD" task, for which it shows error "No token available for usersync".
2. For users who don't have "auth_oidc" authentication type, but matches profile details, the Microsoft block is showing "not connected" to them.
I'll answer the two questions separately.

### Regarding issue 1
I confirm this is caused by some legacy logic in the plugin, where it forces using "System API user" connection method settings to set up API client when trying to assign user to application.

It looks like to me that the API function to assign user to application was originally only available in the legacy ["AzureAD Graph API"](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api), but not in the ["Microsoft Graph API"](https://developer.microsoft.com/en-us/graph). The legacy "AzureAD Graph API" can only be called using system API user, but not application access. Therefore the implementation of the feature in local_o365 plugin contains a logic to force creating an API client using "System API user" connection method settings. If "Application access" is chosen to the connection method, the API client would be empty, and resulted in an error saying "No token available for usersync".

I checked the latest documentation of the API function in "Microsoft Graph API" and it does support application access now. I developed a simple code change to allow API client to be created using application access settings for the API call to add user to application, and it worked in my test. The code change is the pull requests related to this issue, and will be included in the next release.

### Regarding issue 2
The message "You are almost connected to Office 365" and the button to complete the connection is only visible to the user when matching the following conditions:
 1. A match is found for a Moodle user who isn't connected to any Office 365 users in the Office 365 AD,
**AND** any of the two following conditions are met:
 2.1 The Moodle user gets capability to manage OpenID connections from auth_oidc plugin.
**OR**
 2.2 The Moodle user gets capability to manage OpenID connections from local_o365 plugin.

The auth_oidc capabilities related are:
 - Allow OpenID Connection and Disconnection (auth/oidc:manageconnection)
 - Allow OpenID Connection (auth/oidc:manageconnectionconnect)
The local_o365 capabilities related are:
 - Manage Connection Link (local/o365:manageconnectionlink)

By default, none of the capabilities above is allowed for "Authenticated users" role. So that's to say, if you want users to be able to self connect, you will need to give them any of the permissions listed above.

I hope this answers your question. Please let us know if you have updates.

Regards,
Lai

**Comment by sgodbehere01** [comment] 2020-07-30 13:25
Hi Lai and nenorojas, 

Thanks for your help, I've added the change made to main.php and that appears to be allowing the application to be assigned to the users now automatically. I will have some testing done and get back to you if we see any problems. 

Kind regards,

Sam

**Comment by weilai-irl** [comment] 2020-09-29 11:02
@sgodbehere01 ,

Hi Sam, FYI, the fix to the issue 1 in my note has been included in the latest release of the plugins for 3.7, 3.8, and 3.9. Please check it out.

Regards,
Lai

**Closed** 2020-11-04 16:00 UTC
Labels: triaged
