### ISSUE TITLE
Student login gives internal error

### ISSUE THREAD

**Issue by js10855** [Microsoft/o365-moodle#244] opened 2018-04-29 04:37 UTC
Hi,

Our site was working for number of years, suddenly it was started giving error as below on student login. Login url is:http://moodle.<base address>/auth/oidc/

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Action Taken till now:
1) I have set 777 change permission for all files and folders.
2) .htaccess does not have any directives. it has just one line as below:
Redirect /index.php http://<base address>/site
3) Error log shows below error:
PHP Fatal error:  require_once(): Failed opening required './DBClasss/DB_Connection.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home16/agiacnz/public_html/faqp.php on line 2
I have set correct path here but it does change anything.
4) My version.php shows version as below:
 $release  = '3.0.1+ (Build: 20151231)'. Should I upgrade or downgrade it?

I am out of clue now. Please suggest.

**Comment by jamesmcq** [comment] 2018-05-01 21:00
Hi @js10855 - I'm not familiar with the files mentioned - "./DBClasss/DB_Connection.php' or '/home16/agiacnz/public_html/faqp.php' - I don't believe these are Moodle files. Do you have another application installed that might be getting in the way?

**Comment by jamesmcq** [comment] 2018-08-27 20:33
Closing this issue for now because it doesn't seem to be caused by this project. If you can provide additional information, please re-open or create a new issue. Thanks!

**Closed by jamesmcq** 2018-08-27 20:33 UTC
Labels: need more info, triaging
