### ISSUE TITLE
Getting ERROR1 for some users after update

### ISSUE THREAD

**Issue by gunnar-restorff** [microsoft/o365-moodle#1096] opened 2019-02-13 16:17 UTC
I recently (last week) updated our moodle software to the latest stable branch of 3.5.4+. I had 3.5 earlier, but haven't updated for a while. 

Now a few users cannot login (newly synced and trying to log on for the first time through Office 365). They just get at page with the text "ERROR1", and an easy grep of the moodle software leaves me with the following unique snippet (of auth/oidc/classes/loginflow/authcode.php ): 
        $tokenrec = $DB->get_record('auth_oidc_token', ['oidcuniqid' => $oidcuniqid]);
        if (!empty($tokenrec)) {
            // Already connected user.
            if (empty($tokenrec->userid)) {
                // ERROR.
                echo 'ERROR1';die();
            }
            $user = $DB->get_record('user', ['id' => $tokenrec->userid]);

This seems to be a change to the program made in October causing this - where one tries to use userid instead of username?! I have tried to google and ask other moodle supporters, but after hours of research, I am not getting any furher. Would somebody please help me in the right direction?

**Comment by KMESupport** [comment] 2019-02-14 12:13
I have seen the same problem in my environment, also with a few users. if i remember right, switching the authentication methods of these users did solve this issue...

**Comment by gunnar-restorff** [comment] 2019-02-14 13:30
How do you mean "switching auth methods"? I changed it from OpenID to manual, and then it works fine as a manual account. But that doesn't help the user logging in using the Office 365 credentials. If I change it back to OpenID auth, the problem persists. Also if I unmatch the users and then run the full sync - the user gets matched again, but the problem persist. This user is an old user on the moodle system that recently was created in our Azure AD - thus the user got switched and matched; not created from azure AD.

**Comment by gunnar-restorff** [comment] 2019-02-14 18:55
Ok, now I digged into it. I looked up the table auth_oidc_token in the database og noticed, that for the record with the correct "username" the field "userid" was empty. Looking at the other records in the table, it looked that it matches the unique id in the user table with that username. So I updated the record and magically it work. There were two students that had this problem, and both were originally manual accounts that had never been used and never were created in Azure AD. Recently they got created in AD and thus they got matched in the sync-job. For some reason the auth-method didn't switch, so we did switch it to OpenID manually after the users were matched. 

It seems like there is some bug when a record originally gets created in the table for a manual-account user - the field userid doesn't get set?

**Comment by KMESupport** [comment] 2019-02-14 19:08
Thanks for digging into this. That's right i think it was also a, user which i created manually in Moodle with auth method manual. so you mean it might not be a Problem related to the OID Plugin but to the user creation process? Anyway great to know how to solve this issue now, thanks a lot!

**Comment by vinnystocker** [comment] 2019-02-15 09:07
Thanks, this ERROR1 has caused me hours of frustration. Off to test your fix. Cheers.

**Comment by vinnystocker** [comment] 2019-02-19 04:47
> Ok, now I digged into it. I looked up the table auth_oidc_token in the database og noticed, that for the record with the correct "username" the field "userid" was empty. Looking at the other records in the table, it looked that it matches the unique id in the user table with that username. So I updated the record and magically it work. There were two students that had this problem, and both were originally manual accounts that had never been used and never were created in Azure AD. Recently they got created in AD and thus they got matched in the sync-job. For some reason the auth-method didn't switch, so we did switch it to OpenID manually after the users were matched.
> 
> It seems like there is some bug when a record originally gets created in the table for a manual-account user - the field userid doesn't get set?

Confirmed, this worked for me. Moodle 3.6.2+ / Microsoft Office 365 Integration | 2018051706
 
The "userid" field in xxx_auth_oidc_token had the value of zero for some users. Changing this to the "id" value for the user found in xxx_user table fixed the issue. They then used the msft block to manage their connection and login - no need to change over auth method.

**Comment by vinnystocker** [comment] 2019-02-26 02:03
Just to note, this ERROR1 issue occurred on a new / clean installation of the O365 plugins - not an upgrade of an existing site with the plugins already installed. Moodle 3.6.2+ / Microsoft Office 365 Integration | 2018051706

**Comment by jamesmcq** [comment] 2019-02-27 22:16
Hi all - yes a recent release included a "userid" column in the auth_oidc_token table to better link user entries in that table to a Moodle user record - they had previously been linked based on username, which caused problems when usernames were changed in either Moodle or AzureAD, in a specific case. The error exists because without a userid in this column, the user cannot be linked. However, there should not be a case in regular operation where this column is empty.

@gunnar-restorff You mentioned these users were matched in the cron sync job - does this seem to be a consistent occurrence with matched users? @vinnystocker any consistency with what @gunnar-restorff described in how users got into that state?

**Comment by vinnystocker** [comment] 2019-03-06 03:53
Thanks for the comment @jamesmcq I can't see any obvious patterns. It still happens from time to time on the site. We have different email domains for staff and students, so far this only affects staff, but only a few. Other than that everything else is the same, all initially set up as manual auth. Additionally the user matching misses many users even though the username is the same in both Moodle and AAD, so those had to be matched by the upload users method. If you have any suggestions or can point me in the right direction, I'm happy to help investigate the cause. I did notice that if an AAD user without a Moodle account (or not linked to one) tries to access Moodle, a record is created in that table with (obviously) the field "userid" set to 0. I'm now wondering if that record is not being updated after the account is linked and the auth changed. But I would need to investigate that scenario further.

**Comment by gunnar-restorff** [comment] 2019-03-12 12:28
@jamesmcq Sorry for the late reply! I have one new occurrence since last time I wrote. This is a user that was matched on febr. 2:
Syncing user 2010.204@student.setur.fo
```
......... Assigning Moodle user xxxx (objectid yyyy) to application
......... User assigned to application.
......... Found a user in Azure AD that seems to match a user in Moodle
......... moodle username: zzzz, aad upn: zzzz@student.setur.fo
......... Matched user, but did not switch them to OpenID.
......... Adding o365 object record for user.
......... User is now synced.
```
A few times a day the sync job says 
```
Syncing user zzzz@student.setur.fo
......... Found a user in Azure AD that seems to match a user in Moodle
......... moodle username: zzzz, aad upn: zzzz@student.setur.fo
......... User is already matched.
......... User is now synced.
```
The token expiry field in the token record is 1550658175 and the user has never tried to log in (neither before the match nor after). This is the only user that has been match in this period - but a lot of users have been created and they do not have this problem. So yes, it does seem to be a consistent occurrence with matched users (although, I usually do not like to make a general conclusion from 1-3 occurrences). Hope this helps?

**Comment by jamesmcq** [comment] 2019-03-29 07:16
Thanks all - in the meantime updating the userid value in the auth_oidc_token table is a workaround. I've had a few reports of this so looking in to possible triggers for this condition - I'll keep you updated as that work develops.

**Comment by cbrherms** [comment] 2019-07-23 23:53
I've had two instances of this happen today that had to be manually corrected in the auth_oidc_token table.

The first occurrence was during a first login of a user that had already been synced from AAD. I believe this user had an IP change half way through logging in (which takes from 5-10 seconds) which ended up incomplete. The second time they tried it failed due to the userid field being 0.

The second instance was from a user that had tried logging in before their aad account had been synced to moodle (added to our sync group which also applies the enterprise application perms so it appeared in their O365 dashboard before sync had been done).
As we have create account on sign in turned off it showed ERROR1 and we had an entry in auth_oidc_token that wouldn't correct without manual intervention once they were finally synced and a moodle account created for them to match to.

This is a relatively fresh install and our first batch of staff being assigned to add content for the next academic year. 
Hope that gives a bit of further insight.

**Comment by jamesmcq** [comment] 2019-07-24 05:41
Thanks @cbrherms - we have a change scheduled for the next update that should address this - I'll post again here when it's released.

**Comment by jamesmcq** [comment] 2019-07-29 21:35
Hi all, the latest release should resolve this issue. Please open a new issue if you continue to experience issues. Thanks!

**Closed by jamesmcq** 2019-07-29 21:35 UTC
Labels: bug, triaged

**Comment by naldo-gomes** [comment] 2020-11-25 16:04
Hello guys!

I have a problem to macht users in moodle.

When trying to access with the user we received the message that "OpenID Connect, you'll need to use the Microsoft block" needs to be configured
However, the user is an end user and does not have access to the Microsoft block.
We have already changed the user id directly in the bank, linking to the id that was previously 0.
I need help to solve this problem.

**Comment by naldo-gomes** [comment] 2020-11-25 17:15
Hello guys!

I have a problem to macht users in moodle.

When trying to access with the user we received the message that "OpenID Connect, you'll need to use the Microsoft block" needs to be configured
However, the user is an end user and does not have access to the Microsoft block.
We have already changed the user id directly in the database, table - **mdl_auth_oidc_token**  linking to the id that was previously 0.
I need help to solve this problem.
This is the error that is occurring

![image](https://user-images.githubusercontent.com/75033869/100260469-2f147800-2f28-11eb-8cba-3258c0b5eb31.png)
