### ISSUE TITLE
Could not get app or system token using application access

### ISSUE THREAD

**Issue by upats** [microsoft/o365-moodle#1271] opened 2020-06-09 01:02 UTC
Moodle 3.7.6+ (Build: 20200529)
auth_oidc: 3.7.0.5 2019052005
local_o365: 3.7.0.6 2019052006
repository_office365: 3.7.0.0 2019052000

Hi, I'm trying to set up a new Moodle install with the 365 plugins. I'm connecting to an Azure app that was created via the PowerShell script. I've gone through the set-up process, selected Application access and provided admin consent. I manually entered my OneDrive and Azure tenant URLs and they show as usable, but if I hit the auto-detect button I see a message: "Could not get App or System API User token. If you have not yet provided admin consent, please do that first." I gone through the steps to give the admin consent multiple times but still have this indication that an application token isn't working properly.

When I complete the set-up and use the verify function at the bottom of the settings page, I see Microsoft Graph API
The Microsoft Graph API allows communication between Moodle and Office 365.
Could not get app or system token

At this point, and individual user can connect with OIDC authentication. Also, if I manually match a user, they can connect to 365 and use the features in the MS Block, sync calendar, etc. However when I try any system level action like syncing users from Azure or running the create group task, I see this in the debug logs:

local_o365\oauth2\token::instance local_o365\utils::get_app_or_system_token:87: Cannot retrieve a token for the base resource. Data: (null)
--

I haven't tried creating a system user yet and want to see if I can get the app level access working for sitewide functions. Is there a step on the Moodle side I need to allow the application to generate a token? Something else I'm missing?

**Comment by Raswayare** [comment] 2020-06-09 15:22
Hi, I cannot help but I have information to add.
I ran into a similar if not the same issue but with a different built.

Moodle 3.8.3+ (Build: 20200602)
Local_o365 3.8.0.2 (2020020302)
OpenID 3.8.0.1 (2020020301)

The user sync script produces the following in the moodle logs.

**local_o365\oauth2\token::instance local_o365\utils::get_app_or_system_token:79: Cannot retrieve a token for the base resource. Data: (null)**

I went ahead and ran the script by hand in the shell.
 /opt/plesk/php/7.4/bin/php **admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\usersync'**

This produces this error:
......... Syncing user testuser1@xyzxyz.eu
......... Assigning Moodle user 17 (objectid 45da51a8-abe8-4320-add2-aa78e0dca423) to application
......... Could not assign user "testuser1@xyzxyz.eu" **Reason: Error in API call: Invalid version:** xyzxyz.onmicrosoft.com
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.

Both of them go away when I switch off the graph api and use the global admin account.
The rest seems to work except for the profile images, it did sync for my own but my test users not.

**Comment by upats** [comment] 2020-06-09 19:18
In my case, it doesn't seem to be able to even connect since there is no application token. I have created  some users in Moodle with the same usernames as test users in Azure....
Running the full user sync in CLI shows:
**sudo -u www-data php admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\usersync'
Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
...... Starting sync
...... No skiptoken (full) stored.
...... Forcing full sync.
...... Contacting Azure AD...
...... Error in full usersync: Could not get app or system token
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing skiptoken (full) (none received)
...... No users received to sync.
...... Sync process finished.
... used 3 dbqueries
... used 0.032474994659424 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)**

and for the user matching process I get

**sudo -u www-data php admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\processmatchqueue'
Execute scheduled task: Process Match Queue (local_o365\task\processmatchqueue)
... used 2 dbqueries
... used 0.031728982925415 seconds
Scheduled task failed: Process Match Queue (local_o365\task\processmatchqueue),Could not get app or system token
Backtrace:
* line 56 of /local/o365/classes/task/processmatchqueue.php: call to local_o365\utils::get_app_or_system_token()
* line 97 of /local/o365/classes/task/processmatchqueue.php: call to local_o365\task\processmatchqueue->get_api()
* line 157 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\processmatchqueue->execute()**

**Comment by michael-LTS1** [comment] 2020-06-09 22:42
@upats I would suggest checking firewall.  Exact same thing was happening on our setup and firewall ended up being the issue.

**Comment by upats** [comment] 2020-06-10 00:51
@michael-LTS1 - i don't think it's a firewall issue. I have a second Moodle site on the same server and DNS that is using a system user and it works fine. it seems like the problem is related to the token...?
as a note, the moodle sites are installed on a test server on AWS with minimal security groups as there is no real data on the machines and it only talks to our test azure tenant.

**Comment by CasperNaudts** [comment] 2020-06-21 15:17
Any update on this Issue? We are having the same issue with an instalation in Azure.

**Comment by gerpollo2000** [comment] 2020-06-30 18:31
Hi, same problem here about "**Error in API call: Invalid version**" with Moodle 3.9+ (Build: 20200626) on Ubuntu 20 LTS
- Office integration plugin version: 2020020302
- OpenID Connect version: 3.8.0.1

I disabled Application Access but still the same :(

Any ideas please?

**Comment by shaunt-nait** [comment] 2020-07-06 16:02
Moodle Version 3.8.3
O365 Version 3.8.0.2
OIDC Version  3.8.0.1
HIi I'm getting the follow error:
"Could not get app or system token" 

Under the Verify Setup. It works without issue on my 3.6.3 server hosted on the same infrastructure in AWS. So I don't suspect firewall to be an issue. We are hoping to deploy this in our production environment soon any assistant would be greatly appreciated.

**Comment by Raswayare** [comment] 2020-07-07 06:56
After fiddling around some more with it I found that even though I use the Graph API and not the system user; 

I needed to add a system user (disabled) in the modules setup interface and assign the user a licenses, alike a normal user, to create Groups/Teams automatically.

That solved my above issue at least, maybe worth checking for you.

**Comment by weilai-irl** [comment] 2020-07-08 14:25
Hi all, I confirm the issue is caused by the fact that the base "apptokens" was not set correctly, and there is a logic preventing it from being set. We have made a fix to the issue and will be released for 3.7 and 3.8 in the next release in the coming week.

**Comment by weilai-irl** [comment] 2020-07-23 08:22
The issue is fixed in the latest release 3.7.0.7 and 3.8.0.3.
This will be closed.

**Closed by weilai-irl** 2020-07-23 08:22 UTC
Labels: resolved - to be released, triaged
