### ISSUE TITLE
Error when modifying course with local_o365 v3.9.4

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1646] opened 2021-03-31 14:03 UTC
Hi

after updating to latest release, modfying a course in anyway results in the following error:

Argument 1 passed to local_o365\feature\usergroups\coursegroups::__construct() must be an instance of local_o365\rest\unified, bool given, called in [dirroot]/local/o365/classes/observers.php on line 621

This is without Teams course sync or Sharepoint site creation enabled.
Moodle is version 3.9.6 and local_o365 version 3.9.4.

**Comment by weilai-irl** [comment] 2021-03-31 14:25
Hi @kkiiskin,

This error is typically caused by the local_o365 plugin doesn't have a valid app or system token. Could you go to the configuration page of the local_o365 plugin, in the "Setup" tab, click the "Update" button in the "Verify setup" section, and confirm the outcomes of the verification please. The "update" action would get a token if it's missing. After it, the error should be gone.

Please give it a try and let me know.

Regards,
Lai

**Comment by kkiiskin** [comment] 2021-03-31 14:53
Hi

I tried the update and everything checks green. But it did not remove the error.

Still for example user sync from Azure AD works fine.

**Comment by weilai-irl** [comment] 2021-03-31 15:01
Hi @kkiiskin,

Could you try change https://github.com/microsoft/o365-moodle/blob/8fd830d2e934fbb1f1bbea00cc08d6ffb2fc4c09/local/o365/classes/feature/usergroups/utils.php#L502 to
`        $unifiedtoken = \local_o365\utils::get_app_or_system_token($tokenresource, $clientdata, $httpclient);`
and see if it fixes the issue please.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-03-31 15:04
Hi @kkiiskin,

I have updated my last comment after posting it initially. Please check out the latest version.

Lai

**Comment by kkiiskin** [comment] 2021-04-01 07:39
Hi

did not help unfortunately.

I also put this fix in place in case it happened to have something to do with this problem, but no effect
https://github.com/microsoft/o365-moodle/pull/1640/commits/a618001d1f83aafaf87b0453855144cb0fec6a62

**Comment by weilai-irl** [comment] 2021-04-01 08:27
Hi @kkiiskin,

Could you confirm for the connection method settings of local_o365, are you using "application access" or "system API user" please.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-04-01 09:17
Hi @kkiiskin,

To follow up with my last question:
- If you are using application access for connection, could you run this query in your database please:
`SELECT value FROM `mdl_config_plugins` where plugin = 'local_o365' and name = 'apptokens';`
- If you are using system API user, please run the query:
`SELECT value FROM `mdl_config_plugins` where plugin = 'local_o365' and name = 'systemtokens';`

The query should return token records used to call Graph API. If you unserialise the value, (using online unserialise tool, e.g. https://www.unserialize.com/), you should get something like this:
```
Array
(
    [https://graph.microsoft.com] => Array
        (
            [scope] => 
            [token] => ey...
            [expiry] => 1600000000
            [tokenresource] => https://graph.microsoft.com
        )
)
```
The thing I need you to confirm is, there is an array key in "https://graph.microsoft.com" array called "tokenresource", and there isn't one named "resource".

Regards,
Lai

**Comment by phager-at** [comment] 2021-04-02 08:35
It also happens in version 3.9.4 (2020071506) if usergroups feature is disabled, due to instantiating API client and coursegroups feature before checking if the feature's enabled at all. The following change prevent the error if usergroups feature is disabled:

```diff
local/o365/classes # git diff observers.php
diff --git a/classes/observers.php b/classes/observers.php
index a580f09..3022f30 100644
--- a/classes/observers.php
+++ b/classes/observers.php
@@ -617,10 +617,10 @@ class observers {
             $teamsyncenabled = get_config('local_o365', 'team_name_sync');
             $groupsyncenabled = get_config('local_o365', 'group_name_sync');
 
-            $apiclient = \local_o365\feature\usergroups\utils::get_graphclient();
-            $coursegroups = new \local_o365\feature\usergroups\coursegroups($apiclient, $DB, true);
-
             if (\local_o365\feature\usergroups\utils::is_enabled() === true) {
+                $apiclient = \local_o365\feature\usergroups\utils::get_graphclient();
+                $coursegroups = new \local_o365\feature\usergroups\coursegroups($apiclient, $DB, true);
+
                 if (\local_o365\feature\usergroups\utils::course_is_group_feature_enabled($courseid, 'team')) {
                     if ($teamsyncenabled) {
                         $coursegroups->update_team_name($courseid);
```

**Comment by mmulrthelp** [comment] 2021-04-09 08:57
> tokenresource

@weilai-irl We have one in here called resource as well as tokenresource

`'a:2:{s:27:"https://graph.microsoft.com";a:4:{s:5:"scope";s:0:"";s:5:"token";s:1679:"<<<<TOKEN>>>>";s:6:"expiry";s:10:"1617894513";s:8:"resource";s:27:"https://graph.microsoft.com";}s:36:"00000002-0000-0000-c000-000000000000";a:4:{s:5:"token";s:1286:"<<<TOKEN>>>>";s:6:"expiry";s:10:"1617916081";s:5:"scope";s:0:"";s:13:"tokenresource";s:36:"00000002-0000-0000-c000-000000000000";}}'`

**Comment by weilai-irl** [comment] 2021-04-12 10:41
Hi all,

I confirm this is caused a combination of a two factors.
 1. As @phager-at pointed out in https://github.com/microsoft/o365-moodle/issues/1646#issuecomment-812415306, the lack of a check to see if group sync feature is enabled before creating a Graph API client. This would result in any site not having a app token or system user token created to throw the error. A fix to this will be included in the next release.
 2. It looks like the renaming of "resource" to "tokenresource" in the March 2021 release resulted in some token records become invalid. To solve this, please follow these steps:
     - Delete existing token records from DB using the following SQL scripts: `DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' and name in ('apptokens', 'systemtokens');`
     - Purge cache.
     - In the "Setup" tab of the "Microsoft 365 Integration" configuration page, click "Provide admin consent" again.
     - On the same page, click the "Update" button for the "Azure AD setup" setting in the "Verify setup" section, and ensure no error is reported.
This should remove all invalid token records and ensure a new one is created.

Regards,
Lai

**Comment by ross-lovell** [comment] 2021-04-12 11:17
Thank you weilai-irl. I just noticed this error today after updating Moodle and the plugin recently. I came across the error while trying to move a course into another category in my School's Moodle site.

I'll work through the steps you've provided and hopefully this will fix the issues.

**Comment by ross-lovell** [comment] 2021-04-14 11:06
Hi weilai-irl

I've followed your instructions and I'm still getting the below error when trying to edit a course's settings:

**Exception - Argument 1 passed to local_o365\feature\usergroups\coursegroups::__construct() must be an instance of local_o365\rest\unified, bool given, called in [dirroot]/local/o365/classes/observers.php on line 621**

Here's a screenshot of my Microsoft 365 Integration settings in Moodle.

![moodle-office365](https://user-images.githubusercontent.com/2989927/114700273-3989af80-9d19-11eb-941e-772eb6987915.png)

**Comment by thomphi2** [comment] 2021-04-30 14:43
I came accross the same error - In my instance the client secert application key in Azure had exipred. I created a new one pasted it into the Application Key auth_oidc | clientsecret section, hit update and green ticks.

**Comment by Khei-kglakademi** [comment] 2021-05-14 12:27
Hey weilai-irl.

I to ran in to this problem today and tried the fix explained above (Removing the two tables, Purge cash, update consent and update azure AD settings) but no luck.
It looks like you are working on it, so i just wanted to put my ticket in with the lot.

**Comment by Jake-McDonald** [comment] 2021-05-17 02:52
I followed the steps as well and I'm still encountering the same error. I ran through the steps twice.

I ended up just editing the file with the fix in moffe42's commit.

**Comment by shteevy** [comment] 2021-05-17 10:03
The moffe42's fix is working for us too. Many thanks,
Steve

**Comment by weilai-irl** [comment] 2021-05-26 16:08
Hi all,

I wasn't clear enough in my comment at https://github.com/microsoft/o365-moodle/issues/1646#issuecomment-817702557. I have updated it.

To clarify: there are two possible causes for the issue.
 - The most probable cause is the first one, which will be fixed by the linked pull requests. It's essentially the same solution as posted by @offe42. Please try this first. You will need to apply a temporary patch (code change). The pull request will be merged in the next release in June 2021, you can remove the patch on your next upgrade.
 - If you tried the solution to the first one and still have the issue, please try the steps in point 2 to clear tokens.

Sorry for the confusion.

Regards,
Lai

**Comment by thebenkahn** [comment] 2021-06-03 14:53
Although this issue should be resolved via update in the near future, as a quick workaround: 

 Workaround: In the 365 plugin settings under Sync Settings, change local_o365 | createteams  to "Customize" even if you are not using that feature. On the customize page, don't select any courses are to sync.

**Comment by weilai-irl** [comment] 2021-06-29 13:12
Hi all,

The fix to the issue has been included in the latest release of the local_365 plugin. Please check it out.

Sorry for trouble caused in the previous version of the plugin.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 13:12 UTC
Labels: triaged
