### ISSUE TITLE
Moodle 4.2. Issue occurred in server tab after installation of o365 plugin

### ISSUE THREAD

**Issue by santoshrjagtap** [microsoft/o365-moodle#2338] opened 2023-08-07 11:41 UTC
Hello
o365 plugin installed successfully on moodle 4.2. When clicked on server tab under site administration it give error "Exception - Class "external_api" not found".
Please find attached file.
Stack trace:
line 37 of /local/o365/classes/webservices/create_onenoteassignment.php: Error thrown
line 144 of /lib/classes/component.php: call to include_once()
line ? of unknownfile: call to core_component::classloader()
line 61 of /lib/external/classes/external_api.php: call to class_exists()
line 39 of /admin/webservice/documentation.php: call to core_external\external_api::external_function_info()

![server_error](https://github.com/microsoft/o365-moodle/assets/15319449/8595c96d-cd75-4c9e-99fe-215ede7bdf9e)

**Comment by weilai-irl** [comment] 2023-08-17 14:43
Hi @santoshrjagtap 

I cannot reproduce the issue in our environment. Could you clarify the Moodle version in which you saw this error please.

I can confirm that the external_api class is defined as an alias of \core_external\external_api class in lib/externallib.php. We can explicitly require this file in each file using external_api class to avoid the error, but it's good to know why or in which version the class cannot be auto loaded.

Regards,
Lai

**Comment by digidoug** [comment] 2023-08-25 14:57
We just upgraded to Moodle 4.2 and  are getting this error as well.  It is preventing any api calls.

**Comment by loic-crampon** [comment] 2023-08-27 10:07
Same problem with api calls here after installing the local/o365 plugin (on Moodle 4.2).

After uninstalling all microsoft plugins using the local/o365 plugin and the local/o365 plugin itself, api calls are functional again.

Best regards

**Comment by weilai-irl** [comment] 2023-08-31 15:42
Hi all,

A solution has been provided in the PR linked to the issue. I'm struggling to find time to do a release at the moment. Hopefully it will happen in the next few weeks.

Regards,
Lai

**Comment by weilai-irl** [comment] 2023-09-01 08:43
Hi @StevCol1 

The solution is in the linked PR #2350. Before it's merged back to the release version, you will need to apply the changes to your code manually. Please give it a try.

Regards,
Lai

**Comment by weilai-irl** [comment] 2023-10-10 09:43
Hi all,

A solution was provided in the latest release of the plugins (4.2.2). Please check it out. Feel free to reopen the issue if you have questions.

Regards,
Lai

**Closed by weilai-irl** 2023-10-10 09:43 UTC
Labels: Issue type - help wanted, Status - need more info, Plugin - local_o365
