### ISSUE TITLE
Class notebook create fails

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1478] opened 2020-11-25 07:40 UTC
There have been quite a few class notebooks creation tasks that have failed, resulting in extremely long runs of the usergroups task (up to 30 mintutes), and even database timeouts. After adding an mtrace message in the catch block in [replace_group_notebook_job](https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/feature/usergroups/coursegroups.php#L682), I have noticed that the notebooks have not been created, and the reason given was `Error in API call: The request does not contain a valid authentication token.`.

I am not sure when this started to happen, but it may have been some time. Has there been a change in the Microsoft API that causes these issues? Also, I would like to ask to have the message permanently added to the code base, as silent failures are not usually desired.

**Comment by weilai-irl** [comment] 2021-01-08 11:38
Hi @darius-m,

I confirm there is an issue when in the process to get an access token when calling OneNote Graph APIs using application access. The steps to get access token using application access for OneNote Graph API is apparently different from the steps to get access token for the latest Microsoft Graph API. I also confirm that there isn't an API function available in the Microsoft Graph API to create class notebook for a group.

Taking a step back, since the most probable use case for the plugin now is to create Teams instead of groups, the feature to convert a Notebook created for a group into a class Notebook isn't a necessary step any more. Therefore a decision has been made to remove this step in the next release. This should have no impact on the remaining features.

Please try this again when the new version is release later this month, and see if this solve the issues reported.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-01-28 14:04
Hi @darius-m,

As per my last note, the function to convert a Notebook created for a group into a class Notebook has been removed in the latest release 3.9.3 and 3.10.0.

I'll close the issue for now just so that we can mark the milestone closed. Feel free to reopen it if you see any issue caused by this change.

Regards,
Lai

**Closed by weilai-irl** 2021-01-28 14:04 UTC
