### ISSUE TITLE
Mapped Fields not being updated

### ISSUE THREAD

**Issue by aboza** [microsoft/o365-moodle#2064] opened 2022-05-23 20:24 UTC
Hi!!

After an update of our Office365 integration plugin, Im having a little problem with the mapped fields, I had the following fields set to be mapped on login and creation:

![image](https://user-images.githubusercontent.com/3892935/169899859-600d6402-cda3-4655-b08f-2651b6b8398a.png)

bus seems the plugin its not updating the mapped fields on moodle

Office 365 Integration 3.11.3 version
Moodle: 3.11.4+

**Comment by weilai-irl** [comment] 2022-06-08 08:20
Hi @aboza,

Could you confirm the following please:
- The integration between Moodle and Microsoft 365 has been set up and working (e.g. no issue reported when you verify setup in the integration configuration page).
- Profile sync happened on user login and user sync task effectively uses the same function to retrieve user profile data and update Moodle user profiles, could you confirm if the user sync task is running, and check if there are any error message logged in the output please. You may want to turn debugging on for more details.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-06-23 08:25
Hi @aboza,

Sorry for not getting back to you sooner. We have been busy with the June 2022 release of the plugins, which was made available earlier this week.

Unfortunately we don't have an AWS Aurora MySQL database to verify your suspicion, but as long as other database operations (read/write) work, I don't see how the action to update user profiles are different from them and not work.

Pease add the following debugging code at https://github.com/microsoft/o365-moodle/blob/46861cfe86a0cedf2866246f3909faf50de4a3d3/local/o365/classes/feature/usersync/main.php#L544
```
echo '<pre>';
var_dump($fieldmappings);
var_dump($aaddata);
echo '</pre>';
die;
```
When the user sync happens, either on user login or user sync task run, this will print the field mapping settings and the user profile data received from Azure AD on the screen. The combination of the two should reveal why profile sync doesn't work.

If this doesn't print anything, it means the field mapping isn't triggered, so you will need to find out why that's the case.

If you have a non-production test environment, please try it there as this will break user login or user sync task run. Otherwise, please choose a time to run it on production site wisely.

Please paste back the results / findings.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-06-23 21:37
Hi @aboza,

The commented out line basically checks if the logged in user is from the same tenant that in which the Azure app is created. Obviously the Azure app can only get details of users in the tenant it's created in (there are special cases when users are added to the tenant as guests, but I don't think it's relevant in this case).

- The $hostingtenantid is set when Azure admin provides admin consent from the local_o365 configuration page.
- $token->claim('tid') is the tenant ID from the ID token of the logged in user.

If these two don't match, there's a big chance that the Graph API call cannot get user profiles via Graph API call. So the lines shouldn't be commented out in the first place.

Please compare the two values to see if they match. If they don't - please check which value is wrong. To reset the hostingtenantid value, run the following SQL query:
`DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' and name IN ('aadtenantid', 'aadtenant', 'apptokens');`
and provide admin consent from the local_o365 configuration page again. This should fetch ID of the hosting tenant again, update tenant name, and get a new ID token.

Please bear in mind that this is an open source project and the code is subject to customisation by each user. As the maintainer of the plugins, we can only ensure the plugins work in the most common use cases and recommended setup. Many of the issues reported in the community are specific to the individual setup/configuration/customisation of users. We try to provide help in such cases, but please understand this is not the priority of the our work, and sometimes we may not have enough information about the specific situation to provide such help.

Regards,
Lai

**Comment by aboza** [comment] 2022-06-23 22:54
Dude you are the boss!!

Indeed the problem was related with the parameter aadtenantid, it was not present in the database, after running again the tenant consent process, the parameter was created and all work smoothly.

@weilai-irl  so many thanks for your help!!

**Comment by weilai-irl** [comment] 2022-06-24 08:22
Hi @aboza,

I'm glad the issue is resolved. I'll close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2022-06-24 08:22 UTC
Labels: Issue type - help wanted, Status - need more info, Feature - user sync, Plugin - auth_oidc
