### ISSUE TITLE
moodle-block_microsoft on Moodle 4.01 breaks Moodle

### ISSUE THREAD

**Issue by sprezlaus** [microsoft/o365-moodle#2046] opened 2022-05-10 14:38 UTC
We are testing Moodle 4.01 in a safe environment, upon installation of (block_microsoft_moodle311_2021051720.zip) via the "upload-plugin"-page of Moodle, the whole Moodle-installation went fubar and only displays error 500's.

Environment: VPS running freshly installed centos 7, no https enabled, no Selinux
Context: we're mainly adjusting our theme to 4.0, but while at it, we try to install the plugins we had on 3.11.
The VPS is expandable, acces could be given if needed.

**Comment by weilai-irl** [comment] 2022-05-10 14:53
Hi @sprezlaus,

The plugins are not officially supporting Moodle 4.0 yet. We are still in the progress upgrading the plugins to Moodle 4.0, but so far we haven't seen anything like what you described.

Can you check your server access log for error details please. Does remove the plugin solve the issue? Did it happen when uploading other plugins in the suite (auth_oidc and local_o365 in particular)?

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-05-10 16:32
Hi @sprezlaus,

Could you try to install the plugin via other methods? e.g. upload unzipped files to DIRROOT/blocks/microsoft path directly? The error you are seeing is possibly to do with how the server processes the zip file, which is out of the control of the plugin itself.

Also, block_microsoft has a dependency on local_o365 which in turn has a dependency on auth_oidc. You will get an error (it's a different, much more user friendly one than the one you see) if trying to install block_microsoft alone without the other plugins.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-05-16 13:38
Hi @sprezlaus,

We have made a new release of the plugins which officially supports Moodle 4.0. The particular issue that you reported didn't come up in our test, and I'm confident that it was caused by your environment, rather than the plugin itself. I'll close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2022-05-16 13:38 UTC
Labels: Issue type - help wanted, Status - need more info, Plugin - block_microsoft
