### ISSUE TITLE
Azure AD Sync cannot assign users to application no token available for usersync

### ISSUE THREAD

**Issue by upats** [microsoft/o365-moodle#1110] opened 2019-04-09 00:32 UTC
Hello, I have existing users I am trying to migrate to OIDC. I have the Azure AD sync running and OIDC auth set up on the site. In the plugin sync settings, "assign user to application during sync" and "switch matched users to office 365 auth" are both selected. However, when the sync runs users are matched to an Azure user but are not assigned to the Azure application, nor is their auth type changed to OIDC.  Output of the script (replaced real email + user name with generic):

**......... Syncing user email@domain
......... Assigning Moodle user 79651 (objectid 69c92b3c-6de0-4a7f-8321-430dad824183) to application
......... Could not assign user "email@domain" Reason: No token available for usersync
......... Found a user in Azure AD that seems to match a user in Moodle
......... moodle username: user, aad upn: email@domain
......... User is already matched.
......... User is now synced.**

**Comment by michael-LTS1** [comment] 2019-04-09 03:50
Same issue.  Moodle 3.5.5 and o365 plugin 3.5.0.2

Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
...... Starting sync
...... Using skiptoken (full)
...... Forcing full sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing skiptoken (full)
...... 100 users received. Syncing...
.........  
......... Syncing user first.last@domain.com
......... Assigning Moodle user 616 (objectid #############################) to application
......... Could not assign user "first.last@domain.com" Reason: No token available for usersync
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.

**Comment by upats** [comment] 2019-04-09 16:59
I forgot to include, I'm on Moodle 3.4.7 and local_office365 3.4.0.5

Also, I recently switched the Azure app Moodle is pointing at to a new one. Maybe that has something to do with it?

**Comment by mmulrthelp** [comment] 2019-04-13 17:56
I was told in another now closed ticket by the developer that, that is the message that you supposed to get & the sync and change to oidc only completes when the matched user attempts to log in for the first time.. I had set up the sync on our Dev server and didn't check this. I had then ran some SQL on the database to convert the usernames and auth. See my blog post for complete details:

http://notsomany.com/2019/03/23/moodle-azure-active-directory-the-trials-and-tribulations/

Please report back your findings. When we go live with Azure AD authentication in the summer I'll be trying the sync method before changing the username and auth with SQL.

Regards,

Ray.
________________________________

**Comment by dustinbrisebois** [comment] 2019-04-17 20:49
I have to run:

```
UPDATE mdl_auth_oidc_token aot 
JOIN mdl_user u ON aot.username = u.username 
SET aot.userid = u.id 
WHERE aot.userid = 0;  
```

Because for some reason the oidc_token.userid doesn't get update (stays at 0) which means users cannot login. 

3.3 Branch, for Totara 12. Everything else works fine.

**Comment by jamesmcq** [comment] 2019-04-26 06:36
@upats @michael-LTS1 Looking into this - are each of you using a system API user or application access?

**Comment by upats** [comment] 2019-04-26 16:44
Hey @jamesmcq we have system API enabled, although we still have a system user defined from a previous set-up. Wasn't sure if I could/should remove that.

![moodle-o365 settings](https://user-images.githubusercontent.com/7084108/56823109-cde66900-6807-11e9-80bd-9abc182a9dc5.png)

**Comment by cbrherms** [comment] 2019-06-06 11:24
Running in to the same issue here also with synced users not being assigned to the application.

```
......... Syncing user username@domain.ac.uk
......... Assigning Moodle user 4 (objectid ########-####-####-####-############) to application
......... Could not assign user "username@domain.ac.uk" Reason: No token available for usersync
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.
```

Moodle: 3.7
local_office365: 3.6.0.0

**Comment by jtsafran** [comment] 2019-07-09 01:49
I can confirm this behavior on another site with

Moodle 3.6.4 (Build: 20190513)
Local_o365 3.6.0.0 2018120300

Application access is enabled, but System API was in use in the past.  Let me know if there is anything I can do to help here!

Thanks,
Jesse

**Comment by eabcdev** [comment] 2019-09-06 20:17
Hi Team, I had similar problems and my issue was that I did not have default auth_oidc | oidcresource value in 
/admin/settings.php?section=authsettingoidc
(I was using "graph.microsoft.com")
The problem with this value is that resource value is hardcoded with "https://graph.windows.net" value in many scripts, and then some functions like Microsoft block "connected" message did not work.
It becomes with database auth_oidc_token.resource inconsistencies.

You can check
    /**
     * Get the API client's oauth2 resource.
     *
     * @return string The resource for oauth2 tokens.
     */
    public static function get_resource() {
        return 'https://graph.windows.net';
    }
function in local/o365/classes/rest/azuread.php script
Maybe this is also the issue for this error message? cause I had the same message in my cron execution also
best,

**Comment by jamesmcq** [comment] 2019-11-08 10:46
Thanks @eabcdev! Good find. Can anyone else in this issue check this and let me know if this resolves the issue? If that's the root cause we can add an upgrade step to ensure this is correct for everyone. Thanks!

**Comment by jtsafran** [comment] 2019-11-11 22:22
I'm seeing the default value of https://graph.windows.net populated in the config.  Others?

**Comment by tristdac** [comment] 2019-11-27 17:02
Thanks @eabcdev !

This didn't solve the 'No token available for usersync' for me, however it did allow the o365 block to connect and display all available o365 apps. I was having trouble connecting any users (even manually).

Changing the following made the difference for me as it allowed me use 'https://graph.microsoft.com'

public static function get_resource() {
return 'https://graph.windows.net';
}

to:

public static function get_resource() {
return get_config('auth_oidc', 'oidcresource');
}

**Comment by avegys** [comment] 2020-07-23 10:23
Hi All,

Thank you for your input. We have update resource in the latest releases of auth_oidc and local_o365 plugins for Moodle 3.7, 3.8 and 3.9.

Best regards,
Andrius

Best regards,
Andrius

**Closed by avegys** 2020-07-23 10:23 UTC
Labels: triaged
