### ISSUE TITLE
Error when modifying course with local_o365 v3.10.1 (2020110901)

### ISSUE THREAD

**Issue by ChristianVerscheure** [microsoft/o365-moodle#1651] opened 2021-04-07 09:41 UTC
Hi

after updating Moodle to latest release, modfying a course in anyway results in the following error:

Exception : Argument 1 passed to local_o365\feature\usergroups\coursegroups::__construct() must be an instance of local_o365\rest\unified, bool given, called in [dirroot]/local/o365/classes/observers.php on line 621

Moodle is version 3.10.3 and local_o365 version 3.10.1.

Thank you for your analysis of the problem

**Comment by wolfstettler** [comment] 2021-04-08 08:24
Hi,
We have the same issue on moodle 3.9.6 with the local_o365 version 3.9.4 2020071506
Kind regards,
Wolf

**Comment by mmulrthelp** [comment] 2021-04-09 08:39
We are seeing the same.

Do a simple 'Edit settings' and change the 'Course visibility' to 'Hide' and select 'Save and Display' to see the error.

**Comment by weilai-irl** [comment] 2021-04-12 10:49
Hi all,

This is the same issue as in #1646. Please see note https://github.com/microsoft/o365-moodle/issues/1646#issuecomment-817702557 for the cause and solution.

Regards,
Lai

**Comment by dustinbrisebois** [comment] 2021-05-31 16:43
File: local\o365\classes\observers.php
Line #622

Adding:

`            if (!is_a($api_client, '\local_o365\rest\unified')) {
                return false;
            }
`

Does the trick

**Comment by weilai-irl** [comment] 2021-05-31 17:26
Hi @dustinbrisebois,

Please see the related issue in my last note. The pull requests containing the fix to the issue are linked in both issues.

Regards,
Lai

**Comment by digidoug** [comment] 2021-06-25 20:39
> File: local\o365\classes\observers.php
> Line #622
> 
> Adding:
> 
> ` if (!is_a($api_client, '\local_o365\rest\unified')) { return false; }`
> 
> Does the trick

Tried this trick, but no luck. Latest o365 and latest Moodle 3.9. :-(

Here's the full error:
Exception - Argument 1 passed to local_o365\feature\usergroups\coursegroups::__construct() must be an instance of local_o365\rest\unified, bool given, called in [dirroot]/local/o365/classes/observers.php on line 621

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 47 of /local/o365/classes/feature/usergroups/coursegroups.php: TypeError thrown
    line 621 of /local/o365/classes/observers.php: call to local_o365\feature\usergroups\coursegroups->__construct()
    line ? of unknownfile: call to local_o365\observers::handle_course_updated()
    line 155 of /lib/classes/event/manager.php: call to call_user_func()
    line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
    line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
    line 2601 of /course/lib.php: call to core\event\base->trigger()
    line 193 of /course/edit.php: call to update_course()

**Comment by weilai-irl** [comment] 2021-06-29 16:42
Hi all,

The latest release of the plugin (v3.9.5 and v3.10.2) contains the fix to the issue. Please check it out.

I'm closing this issue now.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 16:42 UTC
Labels: triaged
