### ISSUE TITLE
Error in OpenID Connect: AADSTS9002313: Invalid request. Request is malformed or invalid

### ISSUE THREAD

**Issue by quietandy** [microsoft/o365-moodle#1364] opened 2020-09-13 10:56 UTC
We are having an issue which gives the following error:
Error in OpenID Connect: AADSTS9002313: Invalid request. Request is malformed or invalid

When going into the Health Check it suggest that the System API User :Moodle does not have a token to communicate with Office 365 as the system API user. This can usually be resolved by resetting the system API user.

This has a fix it link. When we click the link it asks us to sign in with the API user and grant a load of permissions, then ends up back at the same page with the AADSTS9002313 error.

Any thoughts of what is causing this?

**Comment by randidiot** [comment] 2020-09-13 22:41
Im also having this error and its causing me some headaches any ideas?

**Comment by DrCuriosity** [comment] 2020-09-14 02:04
+1 for me. This just recently started failing within the last 48 hours, and I'm not getting anything useful out of the error log:
```
: Error in OpenID Connect: AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: ec7ca3b5-22ea-4b4b-bc45-897b8f072b00
Correlation ID: 9834e02c-b2de-4d6d-96f4-18477c954663
Timestamp: 2020-09-14 01:35:11Z Debug: 
Error code: erroroidccall_message
* line 54 of /auth/oidc/classes/utils.php: moodle_exception thrown
* line 252 of /auth/oidc/classes/oidcclient.php: call to auth_oidc\utils::process_json_response()
* line 177 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\oidcclient->tokenrequest()
* line 84 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()#012
* line 105 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
* line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()" while reading response header from upstream, client: {{ipv6 address}}, server: {{hostname}}, request: "POST /auth/oidc/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/{{site}}-standalone.sock:", host: "{{hostname}}", referrer: "https://login.microsoftonline.com/"
```

This is a Totara Learn 9 system, so equivalent to a Moodle 3.0, with `auth_oidc` version 30.0.0.15 (2015111916) installed. We're planning on upgrading it to TL12 (Moodle 3.3 equivalent) shortly, but we need to ensure users will be able to log in first.

We're using the recommended "Authorization Code Flow" authentication method. Pertinent settings:
* `auth_oidc|authendpoint`: https://login.microsoftonline.com/common/oauth2/authorize
* `auth_oidc|tokenendpoint`: https://login.microsoftonline.com/common/oauth2/token
* `auth_oidc|resource`: https://graph.windows.net

I've checked with our customer and verified their "client secret" token has not expired.

Any thoughts about what else to check or others means of debugging would be much appreciated.

**Comment by DrCuriosity** [comment] 2020-09-14 02:44
Changing the resource setting to https://graph.microsoft.com doesn't seem to resolve the issue, nor does changing to tenanted endpoints for `oauth2/authorize` and `oauth2/token`.

**Comment by Bananamoon** [comment] 2020-09-14 10:28
+1, we're bumping into the same issue as @DrCuriosity. This only seems to happen on T9 with moodle 3.0. Other clients on different totara versions (and therefore different moodle versions) do not seem to have any issues.

@DrCuriosity, did you manage to solve this issue yet by any chance?

**Comment by DrCuriosity** [comment] 2020-09-14 12:57
Thank you for letting me know that other versions are still working, @Bananamoon. Sadly no, I haven't found a fix for it yet. I asked our clients to see if they could get some feedback/diagnostics from Microsoft to show what wasn't working properly at their end, but I haven't heard back yet.

I'm wondering if maybe the older version of `auth_oidc` relied on some deprecated feature of the OAuth2 v1 API endpoint that has recently been removed or broken?

Tomorrow (UTC+12) I plan to try comparing the codebase against releases for later Moodle versions, and see if I can figure out what has changed. I don't know the OAuth2/OIDC protocols well at all, though, so any help or suggestions from someone who does would be greatly appreciated.

**Comment by Bananamoon** [comment] 2020-09-14 13:55
@DrCuriosity, Good news! We actually had version 3.2.0.1 installed on Totara 9, which is normally for moodle 3.2 (Totara 11 uses moodle 3.2). Clients with Totara 11 and the oidc version 3.2.0.4 did not have any issues. I've just updated the plug-in on the Totara 9 and people are able to log-in again :-).

**Comment by DrCuriosity** [comment] 2020-09-14 20:30
Excellent, I'll give that a try today :-)

**Comment by DrCuriosity** [comment] 2020-09-14 23:43
Okay, fix appears to be working. In order to do this I did the following:
* removed the existing `auth_oidc` plugin and installed [v3.2.0.4](https://moodle.org/plugins/pluginversions.php?plugin=auth_oidc) in its place
* lowered the `$plugin->requires` value in version.php to the version of the site I was using
* changed a use of `$OUTPUT->image_icon()` back to `$OUTPUT->pix_icon()` for TL9 compatibility.

Happy clients now, thank you!

**Comment by praladdesai** [comment] 2020-09-15 15:08
Hi All,
Even I'm getting this error msg.
_**Error in OpenID Connect: AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: d6b0c715-2e52-4903-91bf-509c6a3a5500 Correlation ID: a5912a9c-4703-4229-b7b6-56a131045ef9 Timestamp: 2020-09-15 13:48:25Z**_

I think that there is an issue with office 365 which is causing this error. I can't upgrade my Moodle to 3.2 version as it contains lot of code changes and I fear of losing it. Can someone guide me on how to find a workaround for this(without upgrading moodle and open id connect plugin) ?

**Comment by praladdesai** [comment] 2020-09-16 13:22
Hi,

Did anyone find any solution on how to fix this issue without upgrading Moodle?

**Comment by randidiot** [comment] 2020-09-17 01:14
Im still holding out also, i did try to update the plugin but it didn't work for base moodle 3.0

**Comment by praladdesai** [comment] 2020-09-17 05:39
@randidiot Did you also upgrade moodle main folder from 3.0 to 3.2 ?

**Comment by DrCuriosity** [comment] 2020-09-19 07:50
The steps I took above to upgrade to the 3.2.0.2 version of the plugin did not involve upgrading the core LMS - just the plugin itself, with those two changes: lowering the version number that the plugin requires, and replacing one `image_icon` function call with `pix_icon`.

**Comment by DrCuriosity** [comment] 2020-09-19 07:52
> Im still holding out also, i did try to update the plugin but it didn't work for base moodle 3.0

When you say it didn't work, what happened? Did you get new any error messages that you didn't get with the original plugin?

**Comment by praladdesai** [comment] 2020-09-23 07:34
@DrCuriosity Is oidc plugin 3.2 version still working for you?

**Comment by praladdesai** [comment] 2020-09-23 13:07
@randidiot Did you find any solution for this issue?

**Comment by praladdesai** [comment] 2020-09-23 13:10
@DrCuriosity Can you let me know what is your Moodle version?

**Comment by randidiot** [comment] 2020-09-25 00:47
@praladdesai i ended up just committing and installed an up-to-date version of Moodle, iv lost a lot of the custom code we made over the years but at least students are able to access the work, I was able to export the classes and import them into the new moodle version.

**Comment by DrCuriosity** [comment] 2020-09-25 02:08
@praladdesai as mentioned above:
> This is a Totara Learn 9 system, so equivalent to a Moodle 3.0

We have it working using the 3.2.0.4 plugin, plus the changes I specified above. There were no Totara-specific code changes made.

**Comment by pralad** [comment] 2020-09-25 06:22
I did what @DrCuriosity did and it is working for me now. Did anyone try to figure out what was the root cause of this issue?

**Comment by LearnDevon** [comment] 2020-09-29 12:51
The '_Moodle'_ platform for our organisation was working until last week, until the following message was displayed:

_Error in OpenID Connect: AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: c9df56d3-2c69-4b6a-b0e1-43e5583a2401 Correlation ID: dbda20af-4472-4659-83d6-4d0087fa7d37_

Access to users' '_Moodle_' accounts is by users signing-in to their '_Office 365 for Business_' account and then clicking the '**Moodle**' app in the app launcher.

I've not knowingly made any changes that would've caused this error and the organisation that hosts our '_Moodle_' has reported that everything looks OK from its point of view.

Any suggestions about how I go about regaining access to '_Moodle_' please?

**Comment by pralad** [comment] 2020-09-29 17:03
I did what @DrCuriosity suggested in the above comments and it is working for me now. Please read the above comments by @DrCuriosity . Also, please implement the workaround suggested by @DrCuriosity in the Moodle staging environment before actually implementing it in production environment. Because once you upgrade oidc plugin, you can't downgrade it. It will also upgrade your database tables of oidc. I had taken backup of my moodle site, moodledata folder and mysql database before actually implementing it in production environment. My moodle version is 3.0. I have upgraded oidc plugin to v3.2.0.4. I did not upgrade moodle main source code folder.

**Comment by LearnDevon** [comment] 2020-09-30 08:33
Thanks for your prompt reply **@praladdesai**.  I'll refer the suggestion by **@DrCuriosity** to our '_Moodle_' host, as I don't have direct access to behind the scenes.

**Comment by weilai-irl** [comment] 2021-07-27 10:16
Hi all,

This seems to only happen to old versions of the plugins, which are out of support.

As various comments pointed out, this was mostly related to the "resource" setting in auth_oidc, which is used to get API token. Old version of the plugin had default value https://graph.windows.net/, while it has been changed to https://graph.microsoft.com/. A reset of this value, and deleting / recreating token would normally resolve it.

I'll close this issue now.

Regards,
Lai

**Closed by weilai-irl** 2021-07-27 10:16 UTC
