### ISSUE TITLE
Error in API call

### ISSUE THREAD

**Issue by rezaugg** [Microsoft/o365-moodle#215] opened 2017-06-23 09:20 UTC
We face problems establishing the connection to the sharepointsite.

On our moodle test plattform I installed moodle 3.2 and O365 version v20170511_m32.zip

Everything seems to work exept the course Link to a course sharepoint site.
I get the following Infos/errors in moodle under local_o365 | azuresetup: 
- Could not check reply url.
- Could not check sign-on url. 
- Error in API call: Property 'appId' does not exist as a declared property or extension property.

The moodle log shows the following two API failure infos:
- mode_checksetup:unified: Error in API call: Property 'appId' does not exist as a declared property or extension property. Data: Array ( [file] => /var/www/elearning/htdocs/moodle/local/o365/classes/rest/o365api.php [line] => 284 [message] => Error in API call: Property 'appId' does not exist as a declared property or extension property. [debuginfo] => [errorcode] => erroro365apibadcall_message [module] => local_o365 ) 
- local_o365\rest\unified::get_application_info:995: Error response received. Data: Array ( [code] => Request_UnsupportedQuery [message] => Property 'appId' does not exist as a declared property or extension property. [innerError] => Array ( [request-id] => bcfe6fcb-9965-4fc2-9535-cd60b7727e8a [date] => 2017-06-12T12:13:52 ) ) 

We would appreciate tips that help us to move a step further.

Best regards from Zurich, Regina Zaugg

**Comment by nairial** [comment] 2017-06-27 06:19
I'm seeing the same issue.

**Comment by Kofl** [comment] 2017-06-30 08:12
Same issue for us, when setting up the plugin the first time:

Azure AD Application ==> we clicked on Update

Could not check reply url.
Could not check sign-on url.

Microsoft Graph API (Recommended)
Error in API call: Property 'appId' does not exist as a declared property or extension property.

Office 365 API
Permissions are correct.

**Comment by athasdos** [comment] 2017-07-02 09:57
We are experiencing the same issue after upgrading to Moodle 3.2 last week.

**Comment by francoisbruneau** [comment] 2017-07-25 08:26
I'm experiencing the same issue.

**Comment by Kiosu** [comment] 2017-07-26 06:35
I'm experiencing the same issue.

**Comment by robduncan1** [comment] 2017-09-01 11:12
Experiencing that same issue on Moodle 3.3 with the latest o365. We have to work around by enabling the legacy API's .
'Error in API call: Property 'appId' does not exist as a declared property or extension property.'

Azure AD Application
Verifies the correct parameters are set up in Azure AD.
Could not check reply url.
Could not check sign-on url.
Microsoft Graph API (Recommended)
The Microsoft Graph API replaces the existing application-specific APIs. If available, you should add this to your Azure AD application to be ready for the future. Eventually, this will replace the legacy API.
Error in API call: Property 'appId' does not exist as a declared property or extension property.

**Comment by ellajona** [comment] 2017-10-11 09:57
Hi I just set up Moodle 3.3 and O365 and get the same issue as described above. 
Any solutions ??

**Comment by robduncan1** [comment] 2017-10-11 10:00
Have you tried disabling the graph API - it still only works for me using the legacy API. Options > Advanced Settings > Disable Graph API

**Comment by jamesmcq** [comment] 2017-11-01 06:47
This should now be resolved with the latest version of the plugins - just released. Please update to the latest version and try it out. Going to close this issue - if the problem persists, please open a new issue. Thanks!

**Closed by jamesmcq** 2017-11-01 06:47 UTC

**Comment by wolfstettler** [comment] 2017-12-01 11:54
The version number is still the same (2017051500), so the update is not triggered. Can you please change it or can bad things happen, if I change it myself?

**Comment by anormore** [comment] 2018-08-24 16:30
Hi, hate to open this ticket again but this is still an issue with the very latest plugin version.

**Comment by deblike** [comment] 2018-08-27 13:50
Hi! Indeed this is still occurring, I'm using a blank Moodle campus and brand new Azure App with all the documented permissions, both for Microsoft Graph and Azure AD.

**Comment by robduncan1** [comment] 2018-08-28 10:12
I can confirm, again, that this is still an outstanding bug :-(

**Comment by stabernz** [comment] 2018-08-31 02:45
Can concur - same issue running version 3.5.0.0 on a previously working installation.  Attempting to change API user, providing admin consent results in a "there was a problem logging you in" message.  Verify setup shows "Could not check reply URL" and Error in API call: Resource '*app id*' does not exist or one of its queried reference-property objects are not present.  We cannot run Sync users with Azure AD to set up our new students.

**Comment by jamesmcq** [comment] 2018-08-31 19:02
Hi All - Thanks for the heads-up that you're still experiencing this. @robduncan1 opened a new issue so let's use that one to track any new/remaining occurrences. Looking into this. Thanks!
