### ISSUE TITLE
Autocreation of local user when multi-tenancy logon

### ISSUE THREAD

**Issue by shteevy** [microsoft/o365-moodle#1477] opened 2020-11-24 10:31 UTC
Hello,
I'm using moodle 3.9 and the o365 plugin (Version 3.9.2 (2020071502)
I'm not using the creation of all my users by synchronization. Our users are created at the logon into the local DB of Moodle. Everything is working for my principal tenant.

Three additional-tenant are configured but local users are not created at logon for these tenants and I'm getting the following message : erroro365apibadcall_message
After many tests, I can confirm that the authentication is possible if the the user of the additionnal tenant is manually pre-created into the local database.
The conclusion is : users of additionals tenant are not created locally after good authentication. Is it normal ?
Many thanks for your help,
Steve

**Comment by weilai-irl** [comment] 2021-11-05 22:40
Hi @shteevy,

I know it has been a while since this was reported. I'm sorry for not getting back to you sooner.

The issue you reported might be related to field mapping. If your configured field mapping requires making Graph API calls, any calls to get user details on any users from the additional tenants will fail, because the Azure app used in the Graph API call is created for the host tenant and not the additional tenants, thus the user from the additional tenant doesn't exist in the host tenant.

I only realised this issue recently when testing something else. The solution is to skip the attempt to get user details using Graph API for any user from the additional tenants. This is implemented in the pull requests linked to this issue, and will be included in the next release after test.

Regards,
Lai

**Comment by shteevy** [comment] 2021-11-08 04:57
Hi @weilai-irl, many thanks for your answer. Nice, i will wait the next release. If i can test something for you before that, don't hesitate,
Steve

**Comment by weilai-irl** [comment] 2021-12-07 15:57
Hi @shteevy,

New version of the plugins that contain the fix to the multi tenant issue has just been release. Please upgrade your plugins and confirm if they fix your issues.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai

**Comment by shteevy** [comment] 2021-12-08 11:14
Hi @weilai-irl,

Many thanks. I made the upgrade this morning. I have another strange issue now.

If the authendpoint in my config is "https://login.microsoftonline.com/**mytenant.onmicrosoft.com**/oauth2/authorize" and tokenendpoint is "https://login.microsoftonline.com/**mytenant.onmicrosoft.com**/oauth2/token"  i'm redirected to the login screen of the principal tenant. After a good authentication i get the following message : "
The selected user account does not exist in the “****” client and cannot access the “f9f1aa31-0*****8cd0” application in this client. The account must first be added as an external user in the client. Use another account."

If the authendpoint in my config is "https://login.microsoftonline.com/**common**/oauth2/authorize" and tokenendpoint is "https://login.microsoftonline.com/**common**/oauth2/token"  i'm redirected to the login general login screen of Office365. After a good authentication i get the following message : "

Error call API : Resource 'f70202a*****fb54ea2' does not exist or one of its queried reference-property objects are not present.
Error code: erroro365apibadcall_message
×Trace de la pile 
line 294 of /local/o365/classes/rest/o365api.php: moodle_exception thrown
line 2125 of /local/o365/classes/rest/unified.php: call to local_o365\rest\o365api->process_apicall_response()
line 140 of /auth/oidc/classes/loginflow/base.php: call to local_o365\rest\unified->get_user()
line 210 of /auth/oidc/auth.php: call to auth_oidc\loginflow\base->get_userinfo()
line 3874 of /lib/moodlelib.php: call to auth_plugin_oidc->get_userinfo()
line 514 of /auth/oidc/classes/loginflow/authcode.php: call to create_user_record()
line 278 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handlelogin()
line 116 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
line 168 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
line 31 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()

For your information, i tried to delete the additonnal tenant from the config and re-add it and the problem is still there.

Many thanks for your help,

Steve

**Comment by weilai-irl** [comment] 2021-12-08 15:12
Hi @shteevy,

First of all, I'd like to clarify some points about the multitenancy feature of the plugin.
 - If you want to use multitenancy, you can only use the "common" token and auth endpoints. Tenant specific endpoints will always redirect users to the login page of the main tenant, on which users from other tenants won't be able to login.
 - Before users from other tenants can login, the additional tenant need to be added to configuration first. Login as Moodle site admin, and on the "Microsoft 365 Integration" configuration page, in the "Advanced" tab, click "Configure additional tenants". Follow the instructions on the page to add the additional tenant. It will work for users from additional tenants only after that.

Please give it a try and see if it works for you.

Regards,
Lai

**Comment by shteevy** [comment] 2021-12-10 11:15
Hello @weilai-irl,

It was my configuration. To be sure, i created a new Azure App using the Powershell Script, configured "multi-tenancy" in the Azure App Config. it's working to logon with my principal domain. After that I configured additional tenant and I can see my additionnal tenant in the list.

After many tests, I can tell you that it's working with the login xxx@nameofthetenant.onmicrosoft.com but not the custom domain attached to this Office365 tenant.

With xxx@mycustomdomain.com, i have still the same error at the logon to the the additionnal tenant : 

Erreur lors de l'appel d'API : Resource 'f70202a1-9618-4914-9b24-57944fb54ea2' does not exist or one of its queried reference-property objects are not present.

May I missed something in my config ?

Steve

**Comment by weilai-irl** [comment] 2021-12-10 12:11
Hi @shteevy,

Could you confirm your user with xxx@nameofthetenant.onmicrosoft.com has the same user GUID ID as xxx@mycustomdomain.com please, i.e. they are effectively the same Azure AD account.

Regards,
Lai

**Comment by shteevy** [comment] 2021-12-10 13:02
Hi @weilai-irl 
I'm using Active Directory Synchronisation to create my users. My users with name@customdomain.com has a userprincipal name@customdomain.com and not the equivalent @nameofthetenant.onmicrosoft.com

I tried to create a Cloud User (not synced from AD user) (format : xxx@nameofthetenant.onmicrosoft.com ) and the connection is working. 
I tried to created another Cloud User (not synced from AD user) (format : name@customdomain.com ) and the connection is NOT working. 

Maybe another Azure Right is necessary to read additional custom domains ?

Steve

**Comment by weilai-irl** [comment] 2021-12-10 14:28
Hi @shteevy,

Could you confirm what this the additional tenant that added in the multitenancy page please? Is it customdomain.com or nameofthetenant.onmicrosoft.com? It sounds like to me that you added tenant nameofthetenant.onmicrosoft.com, but the user you tried to login name@customdomain.com is from a different tenant (as the userprincipalname is in @customdomain.com domain). Please ensure this isn't the case.

Once this is clarified, please add the following debug script after the line at https://github.com/microsoft/o365-moodle/blob/9f0e40530982349e13a6b5d2763727cb1864cc62/auth/oidc/classes/loginflow/base.php#L437 in your installation.
`echo '<pre>';var_dump($idtoken);die;`

This will print out the ID token of the authenticated user. Please log in using the account from the additional tenant and perform the following checks. 
 1. The 'upn' claim is as expected. In your case, it should be name@customdomain.com, providing customdomain.com is your tenant, and is the additional tenant being added to the multitenancy configuration page.
 2. The 'oid' claim contains correct user object ID (GUID). You can compare this with the object ID of the user when viewing it in Azure portal.
 3. The 'tid' claim contains the object ID of the tenant that the account belongs to. Ensure this is the same tenant that is configured as the additional tenant, which can be seen in Azure portal as "Tenant ID".

If you can't figure it out yourself, feel free to attach some screenshots of the output on the login page, the multitenancy configuration page, and relevant pages from your Azure portal.

Regards,
Lai

**Comment by shteevy** [comment] 2021-12-10 14:54
Hi @weilai-irl,
I confirm that the domains nameofthetenant.onmicrosoft.com and customdomain.com are on the same Azure AD tenant.
I cannot add customdomain.com as additionnal tenant in moodle. If I add the domain with my admin@customdomain.com, the "nameofthetenant.onmicrosoft.com" is added but not "customdomain.com"

Here are the results of the test with "var_dump" : 

["upn"]=>  string(30) "name@customdomain.com"
["oid"]=>  string(36) "###" = the oid of user name@customdomain.com in Azure portal
 ["tid"]=>  string(36) "###" = samedi ID as my tenant ID

For you information :  if the user name@customdomain.com is manually created in the moodle database before the connection , it works in all cases.

Screen captures (I will delete it later for security ) :

![image](https://user-images.githubusercontent.com/2981456/145593115-0f264806-8728-4cb5-9b07-7cdcd74089ae.png)

![image](https://user-images.githubusercontent.com/2981456/145593217-40348f0d-e442-42a0-92c3-e17083ce6096.png)

Good authentication :
![image](https://user-images.githubusercontent.com/2981456/145593398-363ce88f-b05a-40d7-b57d-9e17b69ea766.png)

![image](https://user-images.githubusercontent.com/2981456/145593630-cf9183c6-e442-4f71-b22a-f2be6fb9f11f.png)

Moodle multitenancy : 
![image](https://user-images.githubusercontent.com/2981456/145593774-7d71f447-3b9a-4bb4-bdf4-3594dfe208d9.png)

![image](https://user-images.githubusercontent.com/2981456/145593760-8b4b58c5-8453-44aa-bced-1041b461b96d.png)

**Comment by weilai-irl** [comment] 2021-12-10 16:17
Hi @shteevy,

I think I see the issue here.

The user from additional tenant was successfully authenticated, but the error happened when Moodle tries to get the details of the user from the additional tenant from the hosting tenant (for field mapping), and because the user doesn't exist in the hosting tenant, it throws the error.

Since the Azure app with the appropriate app permissions is only created in the hosting tenant, it can only get profile data for users from the hosting tenant. Profile field mapping for users from additional tenants is only limited to profile fields available in the ID token (i.e. upn, first name, last name, email and object ID). auth_oidc plugin has a logic to determine if the logged in user is from additional tenant, and the check is at https://github.com/microsoft/o365-moodle/blob/9f0e40530982349e13a6b5d2763727cb1864cc62/auth/oidc/classes/loginflow/base.php#L116-L131. The root of the issue is, this check is performed on the upn of the user from ID token, which is compared to the additional tenant name. It assumes that the upn of users from additional tenants would always contain the additional tenant name, which is not true in your case.

We will try to find a solution to the issue in the next release. A pull request will be made available as soon as the solution is ready so that you can test it.

At the mean time, as a temporary (hacky) solution, you can run the following SQL query in your database to manually add the real domain name to the list of additional domains, so that users from the additional domains will be recognised and excluded from the user profile field sync using Graph API:
`UPDATE mdl_config_plugins SET value = '["hainautpromsoc.onmicrosoft.com","hainaut-promsoc.be"]' WHERE plugin = 'local_o365' AND name = 'multitenants';`

Regards,
Lai

**Comment by shteevy** [comment] 2021-12-10 19:58
Hi @weilai-irl,

Perfect ! It works with your fix. Many many thanks for your patience and your help ! :-)

Have a nice weekend,
Steve

**Comment by weilai-irl** [comment] 2021-12-10 21:39
Hi @shteevy,

Thank you for your confirmation.

I have put the issue that we found in the related github issue. I'll close this issue in that case.

Regards,
Lai

**Closed by weilai-irl** 2021-12-10 21:39 UTC
Labels: Issue type - help wanted, Plugin - auth_oidc, Status - PR ready / pending release, Feature - multi tenants
