### ISSUE TITLE
Extra OIDC-accounts created for linked users 

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1363] opened 2020-09-11 13:04 UTC
We have several cases now where users using e.g. LDAP-authentication get accounts created to Moodle with OIDC-authentication.
OIDC-auth is disabled and only the "Link your Moodle account to an Office 365 account" option is available in Office 365 connection settings.

What causes this? And why is it happening when the OIDC-auth is not even enabled?

**Comment by kkiiskin** [comment] 2020-09-16 08:23
For some reason it logs "Login failed for user 'o365username'. User is suspended (error ID '2')" when the oidc account is created.

**Comment by kkiiskin** [comment] 2020-10-19 12:36
Any comment or advice on this?

I just tested by going to  {moodle}/auth/oidc/ -url with active O365 session in the browser.
It gave error "There was a problem logging you in. Please contact your administrator for assistance" but still created the useraccount to moodle even though OIDC is disabled.

**Comment by kkiiskin** [comment] 2020-11-20 13:17
Any comment on this @weilai-irl ?

Adding a simple is_enabled_auth('oidc') -check to handlelogin() function in authcode.php seemed to stop the extra accounts. 
I have no idea if this is the best solution or if it causes problems elsewhere, but it appears to work.

**Comment by weilai-irl** [comment] 2020-11-20 14:17
Hi @kkiiskin,

Sorry for the delay in the responding to this reporting. We are quite busy recently. I'll take a look at this soon and get back to you.

Regards,
Lai

**Comment by kkiiskin** [comment] 2021-08-11 05:42
Hi @weilai-irl 

is there progress on this issue? 

Like I wrote before, I've used the hack below to prevent creating accounts, but I don't know if it is the best way to go.

/oidc/classes/loginflow/authcode.php, line 452:
```
// Do not continue if auth plugin is not enabled,
if (!is_enabled_auth('oidc')) {
	throw new \moodle_exception('erroroidcnotenabled', 'auth_oidc', null, null, '1');
}
```

**Comment by weilai-irl** [comment] 2021-08-18 08:49
Hi @kkiiskin,

I'm sorry for not getting back to you sooner. I confirm the issue is a quite valid one, and will be addressed in the next release.

Am I right in understanding that there are two issues here:

1. The main issue is Moodle accounts using auth_oidc can be created even when the authentication type is disabled, which can be addressed by the code change suggested in your last notes. This issue is clear to me.
2. The original reporting of the issue seems to suggest that when using the "Link your Moodle account to a Microsoft 365 account" feature to link an existing Moodle account using other auth types to a Microsoft 365 account, sometimes the Moodle accounts are converted to auth_oidc. Could you confirm if this is happening please? If so, I will investigate further.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-08-18 10:03
Hi @kkiiskin,

Please ignore the question in my last note. It's all clear now after a code review.

Regards,
Lai

**Closed** 2021-12-06 14:52 UTC
Labels: Issue type - bug, Feature - user sync, Plugin - auth_oidc, Plugin - local_o365, Status - released / will close soon, Feature - SSO
