### ISSUE TITLE
OIDC Error - "The existing token for this user does not contain a valid user ID"

### ISSUE THREAD

**Issue by elifadida** [microsoft/o365-moodle#1342] opened 2020-08-10 09:43 UTC
**Versions:**
Moodle server version: 3.9.1+ (Build: 20200730)
oidc : $plugin->version = 2020071500; $plugin->requires = 2020061500; $plugin->release = '3.9.0';

**Issue**:
New users from office365 cannot sign in, current users can 
Error on first try: "Error in API call: Insufficient privileges to complete the operation"
Then: " The existing token for this user does not contain a valid user ID"

Checked "auth_oidc_token" table, i see they get userid=0, when checking the "users" table, they are not listed there at all
Clearing the "userid=0" users from the tables dosn't solve the problem.

**Work around** I used - replaced the auth/oidc directory with the older one:
$plugin->version = 2019052005; , $plugin->requires = 2019052000; , $plugin->release = '3.7.0.5';
It works for now (but Moodle prompts for upgrading to newer version & reports a missing dependency  ) 

some **logs** (not sure which is the  more relevant):

Got error 'PHP message: Default exception handler: Error in API call: Insufficient privileges to complete the operation. Debug: \nError code: erroro365apibadcall_message\n* line 288 of /local/o365/classes/rest/o365api.php: moodle_exception thrown\n* line 1781 of /local/o365/classes/rest/unified.php: call to local_o365\\rest\\o365api->process_apicall_response()\n* line 135 of /auth/oidc/classes/loginflow/base.php: call to local_o365\\rest\\unified->get_user()\n* line 205 of /auth/oidc/auth.php: call to auth_oidc\\loginflow\\base->get_userinfo()\n* line 4015 of /lib/moodlelib.php: call to auth_plugin_oidc->get_userinfo()\n* line 465 of /auth/oidc/classes/loginflow/authcode.php: call to create_user_record()\n* line 269 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\authcode->handlelogin()\n* line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\authcode->handleauthresponse()\n* line 165 of /auth/oidc/auth.php: call to auth_oidc\\loginflow\\authcode->handleredirect()\n* line ...', referer: https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=xxxxx

**Comment by AntonT76** [comment] 2020-08-14 11:10
Dear elifadada,
I think I have the same problem. You can fix it if you enter the correct user-ID in the table "auth_oidc_token" (the wrong ID should be "0"). It's also just a workaround. I don't know why sometimes the user-ID will be set to "0". Se also: https://moodle.org/mod/forum/discuss.php?d=396030

best regards, Anton

**Comment by weilai-irl** [comment] 2020-08-14 11:24
Hi @elifadida,

I think the root of the issue is with the Azure app created. It either doesn't have tokens enabled for implicit grant flow, or it doesn't have the required permissions.
 - Implicit grant flow settings can be found in "Authentication" section of the app settings in Azure portal. Please enable both "Access tokens" and "ID tokens".
 - If the app was created manually, you will need to give permissions according to the table in https://docs.moodle.org/39/en/Office365#Configure_application. This is on the "API permissions" section of the app settings in Azure portal. Note some of the permission on the list are about particular features, e.g. Calendar sync, OneNote integration etc, but we would recommend giving them at least at set up phase. Remember you will need to "grant admin consent" for your tenant after making the changes.

After the tokens and permissions are fixed, you will need to clear the existing records from "auth_oidc_token" table in Moodle database, because it would contain previously created tokens with insufficient permission. Login should work straight away after this is cleared.

I hope this helps.

Regards,
Lai

**Comment by elifadida** [comment] 2020-08-16 08:36
> m. You can fix it if you enter the correct user-ID in the table "auth_oidc_token" (the wrong ID should be "0"). It'

Thank you @AntonT76 for your reply , What is the correct user-ID? the user is not listed in users table and dosn't have an ID.
I did see in other forums caes where deleting the bad-token in "auth_oidc_token" helped but it didnt work for me.
Thanks.

**Comment by AntonT76** [comment] 2020-08-17 08:12
@elifadida :
maybe you have to do it like  @weilai-irl mentioned. It could be that your users will not be synchronised from azure to moodle for several reasons (permissions, token, delta-token will not be found, etc.). Did you check your cron-job, if users will be synchonised?

We also have the same problem: since a few weeks new users/changed users will not be synchronised to Moodle. We try to find the problem, but currently without success. It seems to be that the users must exist in Moodle to get a valid entry in "auth_oidc_token". Actually we create missing users in Moodle manually with authenticiation = oidc. It's the only way that users can login in Moodle. Sometimes it happens that the user-ID for existing users in "auth_oidc_token" will be set to "0", so we fixed it manually in the db-table.

best regards, Anton

**Comment by elifadida** [comment] 2020-08-17 13:32
Thank you @weilai-irl and  @AntonT76  
checked the followong:  Azure configuration looks fine, "Access tokens" and "ID tokens both enabled, moreover when copying the older version's folder - it works. so Azure side seems ok I think.
Tried @AntonT76 's technic as well, and created the user as Authentication=Open ID connect, and it stil the same issue..

**Comment by jtsafran** [comment] 2020-08-17 16:51
I will add that we see this as a problem, too.  If an external user creation is in use (manual, ldap, etc) and the user tries to login before the user is created OR synced to an Azure account, the token gets added with userid = 0.

This is not the first time this has been reported.  https://github.com/microsoft/o365-moodle/issues/1133 was marked as fixed?  Maybe it was introduced?

The "Cleanup OpenID Connect Tokens" tool at <site url>/local/o365/acp.php?mode=maintenance gives a way for the Tokens to be deleted from the front end if they look to be bad, but why make that a manual intervention if:

1. It can be handled in the first place by throwing an error if the userid is going to equal 0 with details so it can be tracked down (preferred) 
2. or a scheduled task can clean up those bad entries automatically (not ideal)

Thanks,
Jesse

**Comment by elifadida** [comment] 2020-08-17 17:39
Thank you for the reply. But deleting the bad token (id=0) from SQL
directly does not work. User  gets a bad token again.

בתאריך יום ב׳, 17 באוג׳ 2020, 19:52, מאת jtsafran ‏<notifications@github.com

**Comment by elifadida** [comment] 2020-08-18 15:39
Dear @weilai-irl  - just to add some info
The "Verify setup" tool shows the following:

**Azure AD Application Registration**
Could not check reply url.

**Microsoft Graph API**
The Microsoft Graph API allows communication between Moodle and Office 365.
Error in API call: Insufficient privileges to complete the operation.

**Comment by tim1mw** [comment] 2020-09-16 09:07
I've had an identical problem after rolling out this module on a Moodle with pre-existing users that were then linked to the relevant O365 accounts. I checked the permissions as described above and found no issues. Furthermore, the incidence is inconsistent, most of the time the login was working and the majority of the entries in the auth_oidc_token had the userid correctly recorded. The plugin was also tested on one of our dev systems without encountering any issues, this was a bug that only showed up when we went live. That implies that there is no problem with the App permissions in Azure, I would have expected a permissions problem in Azure to cause this problem for every login.

Manually deleting the record in the database fixes the problem in some cases, but in others a bad token is simply recreated on the next login attempt. The frequency with which this problem occurs (many times a day) made a fix essential, it was creating a lot of support requests.

Digging into the code, the login error comes from this file: classes/loginflow/authcode.php, function handlelogin. The code performs the following test:

if (empty($tokenrec->userid)) {
    // ERROR1
    throw new \moodle_exception('exception_tokenemptyuserid', 'auth_oidc');
}

This will evaluate to true if the userid is 0, so the exception is thrown.

The token records are created in classes/loginflow/base.php file, createtoken function. What mystifies me is that the $userid parameter in this function is optional and no action is taken within the method to look up the userid when the parameter isn't specified. createtoken is called in several places within this plugin, only one of those calls to createtoken specifies the userid as a parameter, the others do not, so all tokens created by one of those other calls will be invalid without some further intervention, which is presumably failing to happen for some users.

It seems to me that either the $userid parameter needs to be made mandatory in createtoken, or the createtoken method needs to look up userids when creating the token record if none is specified in order to avoid creating invalid records in the first place. 

[lookup-userid-patch.txt](https://github.com/microsoft/o365-moodle/files/5231023/lookup-userid-patch.txt)

Perhaps there is something I'm missing here and there is a good reason why some tokens are record with userid=0, if that's the case, then an alternative fix is needed. I also note that there is a pull request here from Feb 2019:

https://github.com/microsoft/moodle-auth_oidc/pull/38

that uses the alternative approach of looking up the correct userid if the record in the token is 0.

**Comment by weilai-irl** [comment] 2020-09-30 15:51
I think the pull request at https://github.com/microsoft/moodle-auth_oidc/pull/38 will indeed help improving things here. I'll merge it in the next release.

**Comment by weilai-irl** [comment] 2020-11-18 14:51
An initial version of the fix has been included in the 3.8.0.5 and 3.9.2 release in November 2020. A updated version will be included in the next release.

**Comment by weilai-irl** [comment] 2021-01-28 14:35
Hi all,

I have included the fix that @tim1mw mentioned in the latest release of the plugin. Please check it out.

Regards,
Lai

**Closed by weilai-irl** 2021-01-28 14:35 UTC
Labels: bug, triaged
