### ISSUE TITLE
"Microsoft 365 Group Membership" user creation restriction doesn't work

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#1719] opened 2021-07-02 09:02 UTC
New users not coming through from Azure AD when using 3.10.2 / 2020110902

In scheduled task it is showing:
```
......... Syncing user 66666677@student.blah.ac.uk
......... User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.
```
All regex user restrictions in auth_oidc have been removed, in case these were now incorrect format and the new user exists in the correct AD group to be pulled in, under **local_o365 | usersynccreationrestriction** 

We are seeing these same new users coming through to our production Moodle instance which is using 3.10.0
/ 2020110900 from January's release.  

Our sync setting are as follows on this UAT instance :

![image](https://user-images.githubusercontent.com/16646247/124250050-62516200-db1c-11eb-98b5-ef70c84ea35e.png)

All other parts seem to working wonderfully, just this isn't.. happy to get you any further logs or debugging if you tell me how it can be gained.

**Comment by weilai-irl** [comment] 2021-07-02 10:07
Hi @mmulrthelp,

I acknowledge the issue.

The bug is caused by the cleanup of Graph API calls in the 3.10.2 release, the return value of a merged duplicate function to get list of groups in the tenant was changed, thus causing a PHP error. I have fixed it in an emergency release 3.10.3 of the plugins.

Please download the new version and test again.

Sorry for the inconvenience caused.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-07-02 13:13
@weilai-irl I'm hoping to get it on our UAT instance today for testing, I'll let you know how it goes.

Many thanks for addressing this so quickly.

**Comment by mmulrthelp** [comment] 2021-07-06 18:25
@weilai-irl it still does not seem to be pulling through new accounts, it says the following in the scheduled task output

`......... Syncing user 19191919@student.blah.ac.uk
......... User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.`

Microsoft 365 Integration page, under Verify setup says:
Missing Application Permissions:
**Manage app permission grants and app role assignments**

Is this needed, the [docs does not mention that it is](https://docs.moodle.org/310/en/Microsoft_365#Configure_application)?

My versions are now showing:
auth_oidc | 3.10.2 2020110903
local_o365 | 3.10.3 2020110904

Do I have allow an extra part in Azure app registration, I've been upgrading the plugins since using it on Moodle 3.6.x

**Comment by mmulrthelp** [comment] 2021-07-06 18:31
Looks like I needed to run 'Cleanup User Sync Delta Tokens' in View Maintenance Tools... its running now

**Comment by weilai-irl** [comment] 2021-07-06 19:17
Hi @mmulrthelp,

Thank you for your confirmation, and I'm glad your issue has been resolved.

The upgrade of auth_oidc to release 3.10.2 should have clean the user sync delta token, I'm surprised that you had to do it yourself. I'll check again in the upgrade script to confirm it.

Regarding the messages shown under the "Verify setup" section, the 3.10.2 release of local_o365 plugin contains updated configuration checks following a thorough review of all the permissions required in all Microsoft 365 plugins for Moodle. It's in our plan to update the corresponding sections in the documentation to reflect this, which should help advanced users to have more control over app permissions depending on their specific needs. Unfortunately we have been extremely busy with many other projects so the documentation update still didn't happen. We expect this to be in place in the coming weeks. For the permission in your question, I can confirm that the "Manage app permission grants and app role assignments" permission is only required if you have the "Assign users to application during sync" option enabled in the user sync options, otherwise it's not required.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-07-06 20:55
Hi @weilai-irl I'll check in the morning if the new accounts are now coming through, it been running the 'full sync' now for over 2hrs

**Comment by mmulrthelp** [comment] 2021-07-07 07:05
@weilai-irl I've checked this morning, new accounts still are not being created. Is there any further logs / data I can get you to help?

The Azure AD sync is still doing the massive check of which accounts are no longer in AD all 36,000+ are marked as Suspended and the 12 midnight sync run is then slowly deleting these each night, 4804 of these deleted last night, there's now still a further 3964 suspended to be deleted - could this process still running stop any new accounts from being created?

**Comment by weilai-irl** [comment] 2021-07-07 08:20
@mmulrthelp, could you send me an email with your details? I can't spot anything obvious from the comments, so it may be a good idea to have a quick call.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-07-07 08:32
@weilai-irl email sent, many thanks

**Comment by weilai-irl** [comment] 2021-07-07 10:02
After a call with @mmulrthelp, we now have a better understanding of the issue.

The nature of the issue is like this:
 - the user in question "User A" is a direct member of a security group "Group X".
 - "Group X" is a member of another security group "Group Y".
 - The user creation restriction is configured to be "Microsoft 365 Group Membership" on "Group Y".
 - When running the user sync task, Moodle thinks "User A" doesn't meet the user creation restriction configured, despite the user is a (indirect) member of the group.

This is caused by the Graph API used for checking user group membership doesn't support transitive group memberships.

A fix will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-07-07 10:32
Hi @mmulrthelp,

The issue should be fixed in the linked PR. We will conduct testing on it, and once passed, include it in the next release. At the same time, feel free to apply the changes on your site and test it.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-07-12 12:33
Hi @weilai-irl I can confirm that your fix in https://github.com/microsoft/o365-moodle/pull/1721 bug fix for transitiveMemberOf is working as expected

Now seeing entries like this, in the Azure AD task log

`......... Syncing user 1123772@blah.uni.ac.uk`
`......... User doesn't exist in Moodle`
`......... Created user #355265`

**Comment by weilai-irl** [comment] 2021-07-12 15:04
Hi @mmulrthelp,

Thank you for your confirmation.

I'll leave this issue open until the fix is released.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-08-18 15:17
@weilai-irl we've gone live on our production with the above options, minus the delete the user. 

What appears to be happening (further investigation on our side is required) when 'Suspend previously synced accounts in Moodle when they are deleted from Azure AD' is ticked, it is not checking Within our Transitive / Nested AD groups and suspending all accounts as it cannot look whether the account exists within the control AD group used in the user creation restrictions.

Could this be happening in your code?

Slowly the daily sync was suspending more and more accounts as well as 'Re-enabling users' who had previously been suspended.

Many thanks,
Ray.

**Comment by kruithre** [comment] 2021-11-02 10:06
Hi Lai, following this issue with interest as we also have had this issue for quit a while. 
Does this mean that the latest version has changes that should fix this? (sorry but that is a bit unclear to me)

**Comment by weilai-irl** [comment] 2021-11-02 10:24
Hi @kruithre,

This the latest version released last week fixed this issue. Please upgrade to the latest version, and you are welcome to report back the outcomes back here.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2021-11-09 08:50
@weilai-irl I'm, testing whether the latest code now unsuspends accounts which got suspended by mistake by the pervious code release. I've a list of 40 odd accounts it occurred to and I'm watching these. 

The only problem is it only ever seems to unsuspend 26 or so accounts every run & these runs only occur every 24 hrs, so a final 'it works' results could be a long way off. Is there anyway of getting it to run more often than once every 24hrs?

This is what appears in my sync task log:

`...... Start suspend/delete users feature...`
`...... Suspending deleted users...`
`......... Could not find user 11111111@xx.xxx.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 22222222@xx.xxx.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 33333333@xx.xxx.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 44444444@xx.xxx.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 55555555@xx.xxx.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 66666666@xx.xxx.ac.uk in Azure AD. Suspending user...`
`...... Re-enabling suspended users...`
`......... Re-enabling user 10000001@xx.xxx.ac.uk...`
`......... Re-enabling user 10000002@xx.xxx.ac.uk...`
`......... Re-enabling user 10000003@xx.xxx.ac.uk...`
`......... Re-enabling user 10000004@xx.xxx.ac.uk...`
`......... Re-enabling user 10000005@xx.xxx.ac.uk...`
`......... Re-enabling user 10000006@xx.xxx.ac.uk...`
`......... Re-enabling user 10000007@xx.xxx.ac.uk...`
`......... Re-enabling user 10000008@xx.xxx.ac.uk...`
`......... Re-enabling user 10000009@xx.xxx.ac.uk...`
`......... Re-enabling user 10000010@xx.xxx.ac.uk...`
`......... Re-enabling user 10000011@xx.xxx.ac.uk...`
`......... Re-enabling user 10000012@xx.xxx.ac.uk...`
`......... Re-enabling user 10000013@xx.xxx.ac.uk...`
`......... Re-enabling user 10000014@xx.xxx.ac.uk...`
`......... Re-enabling user 10000015@xx.xxx.ac.uk...`
`......... Re-enabling user 10000016@xx.xxx.ac.uk...`
`......... Re-enabling user 10000017@xx.xxx.ac.uk...`
`......... Re-enabling user 10000018@xx.xxx.ac.uk...`
`......... Re-enabling user 10000019@xx.xxx.ac.uk...`
`......... Re-enabling user 10000020@xx.xxx.ac.uk...`
`......... Re-enabling user 10000021@xx.xxx.ac.uk...`
`......... Re-enabling user 10000022@xx.xxx.ac.uk...`
`......... Re-enabling user 10000023@xx.xxx.ac.uk...`
`......... Re-enabling user 10000024@xx.xxx.ac.uk...`
`......... Re-enabling user 10000025@xx.xxx.ac.uk...`
`......... Re-enabling user 10000026@xx.xxx.ac.uk...`
`...... Sync process finished.`

**Comment by weilai-irl** [comment] 2021-12-06 14:50
I'll close this issue.

The issue reported by @mmulrthelp can be dealt with in related issue #1771.

Regards,
Lai

**Closed by weilai-irl** 2021-12-06 14:50 UTC
Labels: Issue type - bug, Triaging status - triaged, Feature - user sync, Plugin - local_o365, Status - PR ready / pending release
