### ISSUE TITLE
Issue, Azure AD scheduled job sync only 100 users

### ISSUE THREAD

**Issue by ijazhussain2015** [microsoft/o365-moodle#1084] opened 2019-01-10 08:30 UTC
Hi
I am running sync schedule job ( \local_o365\task\usersync ) manually and getting only batch of 100 users sync each time instead of 1000 users . Our MS Azure AD have 3000+ users.

Moodle : Moodle 3.4.1+ (Build: 20180228)

Plugins
OpenID Connect : 3.4.0.1 ( 2017111301)
Microsoft Office 365 Integration : 3.4.0.2 ( 2017111302)

Sync output:

Sync users with Azure AD.
Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 11:39:01. Current memory use 12.9MB.
...... Starting sync
...... Using skiptoken (full)
...... Forcing full sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing skiptoken (full)
...... 100 users received. Syncing...

**Comment by KMESupport** [comment] 2019-02-05 20:17
Same here, but we use Moodle 3.5.4+ and Plugin Version 3.5.0.2

Also i noticed the following behaviour in terms of syncing:

If i activate only delta sync, no users are being synchronized at all, even there are new Users that could be matched within moodle. Only when i activate "perform a full sync each run", users are synced 100 by 100.

**Comment by gunnar-restorff** [comment] 2019-02-13 15:53
i have also this problem - only 100 users are synced each time. I have tried to search, but cannot find the reason. Did you resolve this?

**Comment by KMESupport** [comment] 2019-02-14 12:10
No news so far...

**Comment by jamesmcq** [comment] 2019-02-27 22:19
@gunnar-restorff @KMESupport To clarify - are you seeing all users looped through eventually? i.e. the problem is the sync is slow since it's doing batches of 100, but it does eventually get through all users? Or is the problem that one 100 users are being synced and the rest never get synced?

**Comment by gunnar-restorff** [comment] 2019-03-13 08:39
@jamesmcq Yes, it goes steadily through all the users eventually. I've set it up, so it runs the sync job every time the cron job runs, so it won't take too much time until a user is synced/created - so it is not a big deal anymore. But some times I want to speed it up by running it manually (often to try to solve or investigate some issue) - and see the response from system - and it is quite frustrating to have to run the job manually *quite often* before reaching the relevant user. [now I've set it up, so that I save all the outputs of the cronjobs to a logfile; this helps, since I can "grep -A 4 -B 4" the logfile for at certain user to see the latest runs - but for this I of course need ssh access]

**Comment by jamesmcq** [comment] 2019-03-29 07:14
@gunnar-restorff Have you had any success with delta sync? That will certainly speed up syncing. Otherwise unfortunately we're limited with how many users the API returns back. We used to call the API 5 times each time the task ran to try to get more users, but increasing the frequency of the task is better practice.

**Comment by gunnar-restorff** [comment] 2019-03-30 23:03
@jamesmcq I don't know what delta sync is. I tried to look for it in the admin menus, but didn't find anything. I also tried to google it together with moodle and/or microsoft - but I only found it in the data of some error reports.

**Comment by KMESupport** [comment] 2019-04-23 18:26
@jamesmcq I unterstand that increasing the frequency might be better practice, but it is pretty unhandy if you have to run the sync like 10x to get all your users synced if you have to test something. Of course we run delta sync for daily usage but if there is something wrong and we want to test it would be great to have the api return like at least 500 users at a time so it does not take that long. so if possible it would be great to change the mechanism back to call the api multiple times...

**Comment by KMESupport** [comment] 2019-04-23 18:27
@gunnar-restorff If you disable full sync option, you are running delta sync automatically...

**Comment by jamesmcq** [comment] 2019-04-26 06:15
@KMESupport The issue with calling the API multiple times is Moodle's move from longer, less frequent crons to quicker, more frequent crons. How frequently are you running the Moodle cron? Delta sync is definitely the best way to go to get fast updates but I'm interested in the "testing" use case you mentioned - is this a situation where you have a particular user you want synced? Would a tool to force sync for a certain user be useful?

**Comment by KMESupport** [comment] 2019-04-30 20:00
@jamesmcq I run aadsync task every 15min. Yes in general the purpose for me for running the full sync task is to sync a certain user, when testing something. so yes a tool like that could be usefull. But still, to me a full sync task in my opinion should retrieve and sync all users at once. Imagine a university with 2000 or more Students having to sync 20 times to do a full sync cycle is obviously unpractical.

**Comment by kkiiskin** [comment] 2019-05-02 10:56
If you have an "Office 365 group" usersync restriction and add a user to the group, it doesn't seem to arrive in Moodle. I'm assuming because the user hasn't really changed so the deltasync doesnt 'see' it?

What does the deltasync actually look for in Azure AD?

**Comment by jamesmcq** [comment] 2019-05-28 23:01
@KMESupport A tool to force sync a particular user is definitely something we can look at. Unfortunately it's not practical for us to sync all users at once. The Office 365 user data API is built to "page" users - to separate them into chunks and allow you to request the next "page". This is what we do with syncing at the moment - requesting the next page the next time the sync job runs. We want to be able to handle a theoretically very large number of users so trying to sync 2000 or more in a single job is not practical. For your setup I'd actually look at running the Moodle cron more frequently. Modern Moodle is designed to have the cron run very frequently, at least every 5 minutes or even every minute. Our sync process (and Moodle cron in general) is moving to performing smaller chunks or work more frequently instead of larger chunks less often.

@kkiiskin That's an interesting subject. Delta sync, I believe, only reports users that have had their profile information changed - it's quite possible group membership does not trigger that user to be included in delta sync. Can you create a new issue for that so we can discuss further?

**Comment by gunnar-restorff** [comment] 2019-05-29 08:52
> @gunnar-restorff Have you had any success with delta sync? That will certainly speed up syncing. Otherwise unfortunately we're limited with how many users the API returns back. We used to call the API 5 times each time the task ran to try to get more users, but increasing the frequency of the task is better practice.

I've tried that now, it gives around 180 users - but they appear in a somewhat random order - so when I want to examine the feedback for a certain user, it definitely doesn't help.

**Comment by gunnar-restorff** [comment] 2019-05-29 08:59
> @KMESupport The issue with calling the API multiple times is Moodle's move from longer, less frequent crons to quicker, more frequent crons. How frequently are you running the Moodle cron? Delta sync is definitely the best way to go to get fast updates but I'm interested in the "testing" use case you mentioned - is this a situation where you have a particular user you want synced? Would a tool to force sync for a certain user be useful?

I increased adsync to ASAP (which is every 2 or 5 min on my system). This helps in general. But sometimes there are problems with certain users, and then it sometimes helps to see the response of that particular user. Also some times we check things, when we change setups. Thus it would be convenient to force sync a certain user. 
I solved part of this problem by saving the output of a cron-jobs to a text file - one for each day. Then I can always go back to see what the latest response was for a certain user. It also helps in many other cases - e.g. problems with sending emails etc. But this requires ssh access (and the use of a terminal, which not all users love). But I can certainly recommend to save the outputs of the crons jobs!

**Comment by jamesmcq** [comment] 2019-06-13 19:53
@gunnar-restorff Glad to know increasing the frequency helped. Syncing a single user I think makes a lot of sense so I'm going to see what we can do in the near future. Thanks!

**Comment by jamesmcq** [comment] 2019-06-13 19:56
@gunnar-restorff I'm going to close this issue and refer you to #1120 for the single user sync feature. Thanks!

**Closed by jamesmcq** 2019-06-13 19:56 UTC

**Comment by pyhalov** [comment] 2019-08-16 10:40
@jamesmcq Is there any way to increase this '100 users' quota? Sometimes we have days when > 1000 users is added to AD, moodle should work for a day to suck them in.

**Comment by cb526** [comment] 2019-08-16 11:33
Hi @pyhalov 
In the Moodle scheduled tasks page, set the job to run every 2 minutes.
