### ISSUE TITLE
Error in full usersync: Error in API call : Causing catastrophe on Moodle

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#2048] opened 2022-05-12 09:54 UTC
Hi @weilai-irl ,

After yesterdays 'Sync users with Azure AD' run at 16:30 the code suspended 5,160 accounts as it claimed that they were no longer in our AD.

Possibly connected to previous issue of, nested AD groups : https://github.com/microsoft/o365-moodle/issues/1771

Snip from the sync log:

`...... Start suspend/delete users feature...`
`...... Error in full usersync: Error in API call.`
`...... Resetting skip and delta tokens.`
`...... Suspending deleted users...`
`......... Could not find user 55******@***.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 55******@***.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 55******@***.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 55******@***.ac.uk in Azure AD. Suspending user...`
`......... Could not find user 55******@***.ac.uk in Azure AD. Suspending user...`

Lines 2 & 3 of the above log snip from the log did not appear on the run the day before, Tuesday 10th of May was day one of installing the latest code. Nor have we seen the issues on two of our UAT sites where we tested the latest plugins for weeks prior to deploying to production. Of the 5,000 account it suspended all the site admins, thankfully I had a local admin account to login with.

Any ideas what could have caused the code to do something so catastrophic ? for the time being I've disabled the option 'Suspend previously synced accounts in Moodle when they are deleted from Azure AD'.

Could it be that when the Error occurred that the code it then moved to could not drill in to our Transitive / Nested AD security group to check if the users where still there and therefore suspended them ?

We are running the latest April code release 3.11.3 on Moodle 3.11.6

Many thanks for any help with this matter,
Ray Reid.

**Comment by weilai-irl** [comment] 2022-05-12 10:23
Hi @mmulrthelp,

I'm sorry to hear about the incident, and I hope you have a way to bulk un-suspend the accounts. I'd suggest you disabling the account suspension option for the moment until the issue is resolved.

After a review of the code related the feature to suspend Moodle accounts, I realised there is a situation in theory that could have caused this, but this this hasn't come up in any of our tests. This would happen when:

1. Delta sync is used for normal user sync, AND
2. Account suspension option is enabled, AND
3. A full user sync fails.

The last point is the key here. The output you pasted doesn't contain the delta user sync part, and I assume the delta sync managed to get user details successfully. So effectively this means delta user sync worked but full sync doesn't, which would be very strange, as the Graph API used in both features are quite similar and require the same set of permissions. They are:

- https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http
- https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http

To find what exact errors were thrown, if possible, please add debugging to https://github.com/microsoft/o365-moodle/blob/7262e83b4a5a31b1cd4109eb0f59c392eafc4f14/local/o365/classes/rest/unified.php#L828-L829, to var_dump the $endpoint and $response, and see if the response details contains any clue.

At the same time, I can add an extra check to ensure that no actual user suspension/deletion happens if anything unusual happens in the attempt to get full list of users.

Please let us know if you make progress on your troubleshooting.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2022-05-12 11:11
Many thanks @weilai-irl for the speedy response. I'll get the debugging added on our UAT site and see what that unveils & report back.

I did revert the issue for the users effected with a bulk csv taken from the task log output.

Here is a snip from the very top of the log, in case that helps as well :

`Execute scheduled task: Sync users with Azure AD (local_o365\task\usersync)`
`... started 16:30:01. Current memory use 19.9MB.`
`...... Starting sync`
`...... No skiptoken (delta) stored.`
`...... Using deltatoken.`
`...... Using delta sync.`
`...... Contacting Azure AD...`
`...... Got response from Azure AD`
`...... Storing deltatoken`
`...... Clearing skiptoken (delta) (none received)`
`...... 3725 users received. Syncing...`
`...... 3725 users in chunk. Syncing...`
`.........  `
`......... Syncing user 19xxxxxx@xxx.ac.uk`
`......... The user is already using OIDC for authentication.`
`......... User is now synced.`
`......... Updating Moodle user data from Azure AD user data.`
`......... User is now updated.`

Regards,
Ray.

**Comment by mmulrthelp** [comment] 2022-05-12 12:23
@weilai-irl slight update, this has occurred on one of our DEV environment on the 5th of May, I'll add the debugging to there now.

**Comment by mmulrthelp** [comment] 2022-05-13 11:21
Hi @weilai-irl mentioned above regarding debugging you've added it to the 3.9 stable branch, not the 3.11 stable branch, where I need it for.. so unsure where to add it ?

https://github.com/microsoft/o365-moodle/issues/2048#issuecomment-1124821485

Many thanks,
Ray.

**Comment by weilai-irl** [comment] 2022-05-13 13:59
Hi @mmulrthelp,

Please use this link https://github.com/microsoft/o365-moodle/blob/MOODLE_39_STABLE/local/o365/classes/rest/unified.php#L827-L829

Basically it's the call to the Graph API in the `get_users()` function in local/o365/classes/rest/unified.php. You will need to inspect the end point of the call, and the raw response. It will contain clues of why the call failed.

Your notes kind of suggest that this didn't fail every time, which is a bit concern for me. I'd prefer there's a way to reliably reproduce the issue.

Regardless, the update to prevent user suspension in case of any issue in getting full list of users can be implemented for the next release for sure.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2022-05-13 14:08
Hi @weilai-irl that is correct, its has failed on 2 of our 5 environments (PROD & DEV) but not the UAT ones.

I stopped the option to suspend on PROD so it could not do any further damage, I did not on DEV and the following day it did not fail and it reinstated the suspended users (in this case it had suspended 14,000 accounts)

Therefore even if I do add the debug, I cannot guarantee it is going to happen again, if it did it might take ages to do so.

Adding a catch preventing suspension will be wonderful.

Many thanks,
Ray.

**Comment by weilai-irl** [comment] 2022-06-21 11:15
Hi @mmulrthelp ,

In the latest release of the plugins from today, the logic relating to whether to run user suspension/deletion has been updated so that if full user sync fails, no user is to be suspended or deleted. This should solve the issue reported in your case.

I'll close this issue now.

Thank you again for reporting this.

Regards,
Lai

**Closed by weilai-irl** 2022-06-21 11:15 UTC
Labels: Issue type - bug, Issue type - help wanted, Status - In Progress, Feature - user sync, Plugin - local_o365
