### ISSUE TITLE
Scheduled task error

### ISSUE THREAD

**Issue by AndyNicolle** [microsoft/o365-moodle#1670] opened 2021-04-29 09:37 UTC
In Version 3.9.4 (2020071504), the scheduled task 'Clean up OIDC state and invalid token' (\auth_oidc\task\cleanup_oidc_state_and_token) fails to run and blocks all other scheduled tasks from running. When run from the command line the below error message is generated:

!!! Exception - Argument 3 passed to mysqli_native_moodle_database::delete_records_select() must be of the type array or null, int given, called in [dirroot]/auth/oidc/classes/task/cleanup_oidc_state_and_token.php on line 47 !!!

The only way to have all other scheduled tasks to run is to disable this task. We have this version of auth_oidc installed on two sites and they both produce this error.

Moodle versions are: 3.9.3 and 3.9.1

**Comment by weilai-irl** [comment] 2021-04-29 09:39
Hi @AndyNicolle,

This is a known issue and will be fixed in the next release in May 2021. The fix is in the related pull requests and can be applied manually before then.

Regards,
Lai

**Comment by AndyNicolle** [comment] 2021-04-29 10:48
Thank-you for the rapid response. I have applied the fix and the scheduled tasks are now running correctly.

**Comment by weilai-irl** [comment] 2021-05-28 08:50
This is duplicate of #1638. The fix pull requests are linked to the original reporting issue, and will be included in the next release (June 2021).

**Comment by weilai-irl** [comment] 2021-06-29 16:44
Hi all,

The fix to the issue has been included in the latest release (v3.9.5 and v3.10.2). This issue will be closed.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 16:44 UTC
Labels: triaged
