### ISSUE TITLE
Moodle - O365 Calendar sync problem

### ISSUE THREAD

**Issue by Faegiss** [Microsoft/o365-moodle#214] opened 2017-06-06 13:18 UTC
My only question is regarding the calendar options. I have a sync "by default" enabled from Moodle to the 365 calendar but I cannot make the inverse (from Office 365 to Moodle).

Any help ?

**Comment by nimojg-microsoft** [comment] 2018-05-01 20:56
@Faegiss It sounds like you're having trouble with the plugins. Here are a few preliminary things to check, and how to proceed:

-  Have you upgraded to the latest version of the plugins? Issues that encountered by others by already be fixed. Be sure to get the latest version of the plugins before anything else.
-  Does your system meet the server minimum requirements? The plugins have the same minimum requirements as core Moodle. Please ensure your environment meets these requirements.
-  Have you enabled the plugins you want? OpenID Connect and the Office 365 repository are not enabled by default. Be sure you have enabled these plugins through the Moodle administration interface.
-  Are your permissions in Azure AD correct? From time to time these permissions may change. Check the Setup section of these docs to get the current list. You can also run the Azure AD Setup verification tool on the "Setup" tab of the local plugin settings page.
-  Enable "Record debug messages" from the local plugin settings page then reproduce the error.   The "View recorded log messages." link from the "Record debug messages" setting will show you any recorded logs. These often contain useful information that may point to the problem.

Still having the issues? If so please respond with the following so we can investigate: 

Your Moodle version
Repro steps
The version of plugins you have installed (auth_oidc, local_o365, repository_office365 etc.)
Any debug messages recorded (see above).

**Comment by nimojg-microsoft** [comment] 2018-05-23 20:10
@Faegiss Any update on the above? We'd love to investigate but we'll need more information.  Thanks!

**Comment by jamesmcq** [comment] 2018-08-27 20:29
Closing this issue due to age and because we need more information. If you experience this again or have any additional information, please re-open or create a new issue. Thanks!

**Closed by jamesmcq** 2018-08-27 20:29 UTC
Labels: need more info
