### ISSUE TITLE
Error code: errorauthgeneral, for some users but not all after auth on Office365

### ISSUE THREAD

**Issue by skuti-is** [microsoft/o365-moodle#1164] opened 2019-10-22 09:16 UTC
Hi GitHub

I'm having trouble with Moodle and O365 auth.

Some users, but not all get errorauthgeneral error after succsessful login on login.microsoftonline.com.

After authcode.php line 476: $user = authenticate_user_login($username, null, true);
The $user variable is empty.

Debug info: 2
Error code: errorauthgeneral
Stack trace:
line 495 of /auth/oidc/classes/loginflow/authcode.php: moodle_exception thrown
line 269 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handlelogin()
line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
line 105 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()

I',m not sure how to debug this further.
Any ideas welcome.

Using all up2date software.
php 7.3
Moodle 3.7.2+ (Build: 20191018)
auth_oidc 3.7.0.1
repository_office365 3.7.0.0
local_o365 3.7.0.1
local_office365 3.7.0.0

**Comment by skuti-is** [comment] 2019-10-22 12:01
workaround
mysql: update mdl_user set auth='oidc' where auth='ldap';

**Comment by webframp** [comment] 2020-07-01 14:01
Seeing a similar problem with our Azure AD tenant, but we do not have any users configured to use ldap auth:

```
MySQL [moodle]> select count(*) from mdl_user where auth = 'ldap';
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

Any suggestions on what further info is useful to debug this?

**Comment by webframp** [comment] 2020-07-01 20:09
Not at all easy to debug and would love ideas if anyone has them, but we ended up deleting the specific users rows from the `auth_oidc_token` table and they were able to login again.

**Comment by weilai-irl** [comment] 2021-07-27 13:28
Hi all,

This could be caused by invalid records hanging in the `auth_oidc_token` table that contains userid value of "0". Release 3.9.3 (for Moodle 3.9) and 3.10.0 (for Moodle 3.10) contains improvements in handling such records, which should see this issue fixed.

Please upgrade to any version after the releases to confirm the issue is gone.

Since this issue should have been fixed in previous releases, I'll close the issue one month from today, unless it needs to be kept open. 

Regards,
Lai

**Closed** 2021-09-03 21:04 UTC
Labels: Issue type - bug, Plugin - auth_oidc, Status - released / will close soon, Feature - SSO
