### ISSUE TITLE
OIDC - Link to IdP and authentication configuration Error

### ISSUE THREAD

**Issue by pcrispimMT** [microsoft/o365-moodle#2193] opened 2022-10-08 12:07 UTC
When I go to https://moodlesite/admin/settings.php?section=authsettingoidc, in **Basic Settings**, I see a **_Redirect URI_** (with **https://moodlesite/auth/oidc/** setting that cannot be changed) and, right below, in **_IdP and authentication_**, a link to **IdP and authentication configuration** (that points to _https://moodlesite/auth/oidc/manageapplication.php_).

If I click on this link, I get a "**Missing basic settings**" error.

```
Section error
**More information about this error**

```
```
**Debug info:**
Error code: sectionerror

```
```
**Stack trace:**
- line 497 of /lib/setuplib.php: moodle_exception thrown
- line 26 of /admin/settings.php: call to print_error()

```

If I click on **More information about this error**, I get:

### error/admin/sectionerror
The error means that a new admin page 'foo' (the one you're developing right now) is not registered with the Admin menu. It is triggered with the call:
`admin_externalpage_setup('foo');`

The solution is to add a reference to the page in the appropriate file in admin/settings/XXX.php. Something like:
`$ADMIN->add("parent_section", new admin_externalpage('foo', "Foo Admin Component", "$CFG->wwwroot/$CFG->admin/foo.php"));
`

Important info that might help:
- I have Moodle 4.0.4+ (Build 20221007)
- I'm using Boost theme
- I don't have any other extensions installed behind Office365-Moodle integration full pack of plugins
- All Server checks (in Admin > Server > Environment) are OK (except for XMLRPC message, but with PHP 8, it should not appear such message because XMLRPC was discontinued)
- I have "DEVELOPER: extra Moodle debug messages for developers" active in Debugging
- I use AlmaLinux + SELinux + PHP 8.0 + PostgreSQL 14.5 + Nginx 1.22 

I'm stuck here, because I was going step-by-step with documentation in https://docs.moodle.org/400/en/Microsoft_365 but can not go further than point 4.1. of "**Plugin auth_oidc configuration - part 1**"

**Comment by Pedt487** [comment] 2022-10-11 14:45
Hey @weilai-irl 

we got the same exact issue
PHP Version 8.0.24
Moodle 4.0.4+ (Build: 20220930)

purging the cache did not help - settings.php looks fine to me

**Comment by pcrispimMT** [comment] 2022-10-11 15:54
Also purged the cache, but has no effect.
Settings.php also looks fine to me:
![image](https://user-images.githubusercontent.com/54676270/195140628-60c3a4ca-29e0-4176-a254-b9b824490568.png)

**Comment by pcrispimMT** [comment] 2022-10-11 15:56
> Hey @weilai-irl
> 
> we got the same exact issue PHP Version 8.0.24 Moodle 4.0.4+ (Build: 20220930)
> 
> purging the cache did not help - settings.php looks fine to me
> 
> ![2022-10-11 17_41_45-administrator@atinns1095_ _var_www_moodle_auth_oidc](https://user-images.githubusercontent.com/79634029/195137922-6e20f697-5d18-4ae1-ac61-d820663cdb80.png)

Do you use Nginx + PosgreSQL?

**Comment by weilai-irl** [comment] 2022-10-11 20:27
@Pedt487,

I think the last message from @pcrispimMT was for you. Could you confirm your web service and DB server please to see if they are related to the issue.

Our development/test/production environments are on Apache/MySQL server, but I can arrange an installation on nginx/PostgreSQL too to see if it's relevant. It may take a few days for our IT team so please bare with us. Also our testing so far has been performed on release version of Moodle 4.0.4 (2022041904). I'll try it on nightly build too.

Regards,
Lai

**Comment by Pedt487** [comment] 2022-10-12 07:42
@weilai-irl @pcrispimMT 
our environment is also Apache (2.4.52) and mysql - latest versions since we setup the server and the addon 2-3 days ago

**Comment by KeomaTMT** [comment] 2022-10-12 09:03
Same issue 

When I go to https://moodlesite/admin/settings.php?section=authsettingoidc, in Basic Settings, I see a Redirect URI (with https://moodlesite/auth/oidc/ setting that cannot be changed) and, right below, in IdP and authentication, a link to IdP and authentication configuration (that points to https://moodlesite/auth/oidc/manageapplication.php).

If I click on this link, I get a "Missing basic settings" error.

**Comment by weilai-irl** [comment] 2022-10-12 14:21
Hi all,

I acknowledge the issue. I'll try to push out a fix to the issue today.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-10-12 14:55
Hi all,

A new version of auth_oidc has been added to https://moodle.org/plugins/auth_oidc. It contains the same version number as the last release, but contains the fix to this issue. Please download this new version to see the fix. 

The root reason behind this issue was a redirect in the auth/oidc/manageapplication.php that was added in the development process. The redirect pointed to a non-existing page. This issue only affects sites with brand new auth_oidc installations, therefore wasn't captured by our test.

Please confirm if the issue has been fixed after upgrading to the latest version from today.

Regards,
Lai

**Comment by Pedt487** [comment] 2022-10-12 15:18
works great, thank you!

**Comment by pcrispimMT** [comment] 2022-10-12 17:49
> 

Thank you!

**Comment by dsn2019** [comment] 2022-10-13 06:07
We too were facing the same issues.  Thank you for the quick fix; very much appreciated.

Best Regards,
dsn

**Comment by weilai-irl** [comment] 2022-10-13 09:24
Hi all,

Thank you all for reporting the issue and confirm the fix worked, and sorry for introducing this issue in the first place.

Since the issue is fixed now, I'll close the issue.

Regards,
Lai

**Closed by weilai-irl** 2022-10-13 09:24 UTC
Labels: Issue type - help wanted, Status - need more info, Plugin - auth_oidc
