### ISSUE TITLE
No new users syncing from AAD

### ISSUE THREAD

**Issue by leonhedding** [Microsoft/o365-moodle#195] opened 2017-01-04 10:16 UTC
I am seeing the same issue as this person.
https://moodle.org/mod/forum/discuss.php?d=278647&parent=1374187

Anytime the sync cron job runs nothing is synced. It ends. No errors even with php debugging and the plugin debugging turned on.

I had it working for months. I don't know what is now causing this issue.

`[root@www cli]# php schedule_task.php --execute=\\local_o365\\task\\usersync
Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
No more users to sync.
Partial user sync completed. Saving place for next run.
... used 4 dbqueries
... used 0.8103551864624 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)`

This is a problem for us since no new users can be easily added to a course.

**Comment by petersercombe** [comment] 2017-01-22 20:33
I too am having this issue following an upgrade to Moodle 3.1 (and current version of plugin)

The workaround to run the following command on the database did get it going again:

`UPDATE mdl_config_plugins SET value = "" WHERE name = "task_usersync_lastskiptoken" AND plugin = "local_o365"`

The "upgrade" we applied including the running up of an entirely new server. Unsure whether this could be related.

**Comment by leonhedding** [comment] 2017-01-22 21:26
I did not do a new install. Just an inplace upgrade. Your SQL statement has fixed the problem.

**Comment by petersercombe** [comment] 2017-02-14 22:26
I've just had this issue reappear randomly. Updating the row in the mdl_config_plugins table will work sometimes, other times I'll get a "Cannot obtain cron lock" error. 

@leonhedding Out of curiosity, how often do you have your users set to sync in the Scheduled tasks?

**Comment by leonhedding** [comment] 2017-02-15 13:47
We run it every hour. Your cron lock error is another issue. See this article that explains it better than I ever could. https://moodle.org/mod/forum/discuss.php?d=274692

**Comment by jamesmcq** [comment] 2017-03-03 16:49
@petersercombe @leonhedding Do either of you have the Microsoft graph API enabled? I've seen this on a handful of installs and seems to be related to the legacy API.

**Comment by leonhedding** [comment] 2017-03-06 14:07
We do use the Graph API.

**Comment by petersercombe** [comment] 2017-03-06 22:37
Likewise, though our first instance of the o365 plugins run on our site were pre-graph API. 

We've not yet enabled application permission access as a replacement for the system API user, if that makes a difference.

**Comment by frathom** [comment] 2017-04-07 15:00
Same bug here with following message on cron logs.
"No more users to sync.
Partial user sync completed. Saving place for next run."
Despite the fact that there are many users left to sync. 
Cron running every hour. 
Moodle 3.1 with version 3.1.0.6 of local_o365
Microsoft Graph API enabled. Not working when disabled either.
Application permission enabled. Not working when disabled either.
Ran the following command : UPDATE mdl_config_plugins SET value = "" WHERE name = "task_usersync_lastskiptoken" AND plugin = "local_o365" on db with no effect.
Thank you for any advice.

**Comment by eabcdev** [comment] 2017-04-25 13:41
I have the same issue, Moodle 3.2, API graph.
It remains in
_Partial user sync completed. Saving place for next run._
without updating new users, users are created only when they login into Moodle.
First users batch where created until #2000 users where created ~
best

**Comment by jamesmcq** [comment] 2017-05-11 20:14
Hi all, just released a new version that contains a few fixes for the user sync feature. Please upgrade and let me know if the issue is resolved. Thanks!

**Comment by jamesmcq** [comment] 2017-05-24 05:02
Going to close this issue as fixes have been released that should solve this issue. If you continue to experience problems, please create a new issue. Thanks!

**Closed by jamesmcq** 2017-05-24 05:02 UTC
