### ISSUE TITLE
Course Groups not created in O365 - Error in API call: Invalid object identifier '{'. 

### ISSUE THREAD

**Issue by ml413** [microsoft/o365-moodle#1308] opened 2020-07-07 19:25 UTC
Hi,
We're running into a problem whenever we try to sync new courses with Teams. We've had 2 courses work successfully and the rest have failed. When I go to Teams Sync->Customize group and turn on syncing for a new course, nothing happens. If I go into the course page in Moodle and click the Course Group link in the Microsoft block, I see this message: "This Office 365 group will be created shortly, please try again later." It never actually gets created, though, even though the cron task is running every few minutes. If I use the "Resync users for groups in courses" option under Maintenance Tools, I'll see an error message like this for the course:

Syncing group membership for course #529
Syncing to group "{"
Could not sync course 529. Reason: Error in API call: Invalid object identifier '{'.

We're using Moodle 3.5 and version 2018051700 of the O365 plugin.

The sync has worked in a few courses, but we have not figured out why it's not working in all the others. I did confirm that users in the problematic courses have connected their Moodle accounts to O365 before attempting the sync. Most are using OpenID for authentication, though a few older accounts are manual and used the Microsoft block to connect their accounts.

In the database, I checked the mdl_local_0365_objects table, and the objectid value for the problematic courses is "{". It seems like the O365 group/Teams generation script is failing for some reason and mistakenly placing that value in the database.

We would love to have this working consistently as a number of our instructors are asking for it in their classes. Thanks for any help!

Matt

**Comment by avegys** [comment] 2020-07-09 10:09
Hi Matt,

This seems like an issue which was resolved in Moodle 3.7 and 3.8 (#1222). The cause of errors in those versions were mentioned by nenorojas - https://github.com/microsoft/o365-moodle/issues/1222#issuecomment-617029669.
You are getting "{" instead of object id because "{" is the beginning of error message that API is sending. After quick look at 3.5 plugin code, my guess would be that the description of course is longer than 1024 chars and this is causing the error for you.\

Best reagrds,
Andrius

**Comment by ml413** [comment] 2020-07-09 16:22
Thank you, Andrius! That's very helpful. It looks like some of the courses had multiple editing teachers, plus the instructors were not authenticating with OIDC (though they did connect their Moodle accounts to O365). We are hoping to migrate to 3.9 in August, so hopefully there will be a 3.9 version of the O365 plugin by then that will resolve the issues. Thanks again for your time.

Matt

**Closed** 2020-07-09 18:21 UTC
