### ISSUE TITLE
Unable to login from external AAD account

### ISSUE THREAD

**Issue by LukeDuffy98** [microsoft/o365-moodle#1738] opened 2021-07-24 13:33 UTC
Hi

I am trying to configure the OIDC plugin.

For user accounts in my tenant, it all works fine. For users in external tenants they are unable to login. 

I have done as much as I can in regards to trouble shooting
I have followed the error to the login request .I noticed in the browser the url to login in with includes the name of my tenant rather than the common url required. "https://login.microsoftonline.com/common/login"

![image](https://user-images.githubusercontent.com/31847926/126869778-ebd8d367-a305-4909-a368-1dee9262ada1.png)

and the error for the client is :
![image](https://user-images.githubusercontent.com/31847926/126869799-e423ceb4-abb6-4b37-acc2-ce058141f631.png)

which makes sense as it is trying to authenticate to the wrong AAD

After I remove the tenant information from the plugins - local - Microsoft 365 Integration,  I get the correct url and can in fact login
![image](https://user-images.githubusercontent.com/31847926/126869730-7066f1bf-b976-4f10-a7b8-7c307e9d931b.png)

![image](https://user-images.githubusercontent.com/31847926/126869667-2a75b1d4-6284-4cb7-a182-9757d7005fea.png)

Unfortunately I then get the following error after login

![image](https://user-images.githubusercontent.com/31847926/126869703-8d278942-2723-405c-bcf8-65bd45743a1a.png)

I can manually create them as a external user account and everything works for each individual account. 

So I am assuming these errors occur because the tenant information is missing.

Is their a flag or switch that needs to be set to pint the login requests to the common url "https://login.microsoftonline.com/common/login" or is this a bug ?

I am using Microsoft 365 Integration	2020071509

Thanks

**Comment by weilai-irl** [comment] 2021-07-26 11:30
Hi @LukeDuffy98,

I cannot reproduce the exact issue, but here are some general comments/suggestions that may help:
- The "Azure AD Tenant" setting always needs to be configured. You integration would be deemed as incomplete without it, and I'd expect many feature in the integration fail.
- In order to allow a user from a different Azure AD tenant to login, the user has to be added to your main tenant as a guest. https://docs.microsoft.com/en-us/azure/active-directory/external-identities/b2b-quickstart-add-guest-users-portal.
- In order to allow a user from a different Azure AD tenant to login, you will also need to enable the "Sync guest users" option in the "Sync users with Azure AD" section in the "Sync Settings" tab in the "Microsoft 365 Integration" page.
- For the "Authorization Endpoint" and "Token Endpoint" settings in auth_oidc plugin, you should be able to user either the "common" endpoints, or tenant specific ones. As long as the guest user is added to the tenant, they should both work.

Please review the comments and confirm if they help.

Regards,
Lai

**Comment by LukeDuffy98** [comment] 2021-07-27 01:57
Thanks for the reply Lai

Just to clarify, for the auth_oidc plugin to work, the users must exist in your AAD either as a regular user or as a guest.
Is that correct ?

The reason I may be a little confused is on the Multitenancy config page
/local/o365/acp.php?mode=tenants

It starts talking about allowing users from other tenants in. 
I have configure the AAD app to be multi tenant 
![image](https://user-images.githubusercontent.com/31847926/127082513-25e22c14-3d48-4a28-8d3a-354c1ec8459d.png)

and have no other tenants configured

![image](https://user-images.githubusercontent.com/31847926/127081977-6909a8c5-92bd-4235-a5b8-16345d08cb80.png)

Which is why I thought anyone with an Microsoft 365 (AAD) account would be able to access my moodle.

So I may just need clarification on the capabilities. The key question is :
Can I have external users login to my moodle system using the auth_oidc plugin, without them pre existing as a user (guest or normal)

Thanks 

Luke

**Comment by ranevaibhav95** [comment] 2022-03-08 07:36
I am also getting the same issue, if i change Azure AD tenant name to common it works but then the users are not synced to moodle. So every time we need to change the tenant and give admin consent and start sync for each tenant. This is causing too much of maintenance activity to be done. Is there any resolution someone can provide on this?

**Comment by weilai-irl** [comment] 2022-03-08 12:04
Hi all,

I confirm this was caused by a bug that was fixed in release 3.9.8, 3.10.5 and 3.11.2 releases of the plugins in December 2021. The pull requests are linked to this issue now.

Please upgrade your plugins and retest to confirm if it works.

Regards,
Lai

**Comment by ranevaibhav95** [comment] 2022-03-10 09:18
Hi @weilai-irl , thank you for your reply, i am able to login now, but there is still dependency of doing admin consent every now and then to sync new users from either of the tenant..in earlier versions both of the tenant used to sync automatically sometimes.

Is there a configuration change which i can make so that the users from both the tenants get synced regardless of what i enter in "Azure AD Tenant" field?

**Comment by weilai-irl** [comment] 2022-03-10 09:22
Hi @ranevaibhav95,

Could you explain why/how you need to giving admin consent "every now and then" please? 

Syncing users from additional tenant was never a feature in the integration, simply because the Azure app created for the hosting tenant A cannot access any data in additional tenant B. Maybe there are some misunderstanding regarding this feature?

Regards,
Lai

**Comment by ranevaibhav95** [comment] 2022-03-10 09:58
Giving admin consent "now and then" means i need to switch the "Azure AD tenant" everytime to sync new user from either of the tenants and to switch tenants means to give admin consent again.

Ohh and also about the second point of syncing users i don't know how but it used to sync users from both the tenants. If its not a feature then we need to automate it but giving admin consent is a concern everytime.

**Comment by weilai-irl** [comment] 2022-03-14 21:22
Hi @ranevaibhav95,

First of all, I confirm that if you make changes to the Azure app ID and secret configurations in the Microsoft plugins, you are expected to give admin consent again. The token stored in the Moodle database to be used for Graph API calls is intentionally deleted if a change in the Azure app ID configuration is detected, because the old token would only work with the old app ID.

In fact, there are other changes when Azure app ID configuration change is detected - all existing user mappings stored in the local_o365_objects table will be deleted too. This is mainly for the same reason - the Azure app ID change may indicate a change of tenant, and since the integration may not have access to any information about user in the old tenant. As a result of this, some Teams integration features may not work as expected too, because the user mappings are used to determine whether Moodle users need to be added to Teams.

That's basically to say that the way that you use the plugin (by "switching" between Azure apps) is not how the integration is designed. If you can describe how you would like to use the integration (and maybe why it is set up as is now), I may be able to see how this can be improved.

Regards,
Lai

**Closed** 2022-04-06 10:17 UTC
Labels: Issue type - help wanted, Status - In Progress, Feature - user sync, Plugin - auth_oidc
