### ISSUE TITLE
 Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'

### ISSUE THREAD

**Issue by robduncan1** [microsoft/o365-moodle#2183] opened 2022-09-20 16:00 UTC
Some Moodle courses are failing to sync with groups, on inspection we found that altough the group names where being truncated they where still one character over the limit, 
$coursepartmaxlength is set to 64 in /coursesync/utils.php 
this should be 63 

o365/classes/feature/coursesync/utils.php
line +381
###########################################################

 $coursepart = static::clean_up_group_mail_alias($coursepart);

      **$coursepartmaxlength = 64** - strlen($groupmailaliasprefix) - strlen($groupmailaliassuffix) - strlen($grouppart);
      if (strlen($coursepart) > $coursepartmaxlength) {
       $coursepart = substr($coursepart, 0, $coursepartmaxlength);
      }

      return $groupmailaliasprefix . $coursepart . $grouppart . $groupmailaliassuffix;
    }

**Comment by weilai-irl** [comment] 2022-09-27 10:12
Hi @robduncan1,

Thank you for reporting the issue. The issue is addressed in the linked PR, and will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-10-06 11:40
Hi all,

The fix to this bug has been included in the release from today. Please upgrade your plugins to the latest version to see the changes.

I'm going to close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2022-10-06 11:40 UTC
Labels: Issue type - bug, Status - In Progress, Feature - teams integration, Plugin - local_o365
