### ISSUE TITLE
Could not check reply url

### ISSUE THREAD

**Issue by Richardvi** [microsoft/o365-moodle#1092] opened 2019-02-11 10:13 UTC
This bug seems to be back:

![sharedscreenshot](https://user-images.githubusercontent.com/5486910/52556845-fa383f00-2ded-11e9-9f7a-16adf41dba0d.jpg)

Using Moodle 3.5 and latest plugin version 3.5.0.0 (2018051700)

**Comment by vinnystocker** [comment] 2019-02-15 09:09
I also have this on my site. As far as I can see everything is set up properly

**Comment by gd5t** [comment] 2019-02-18 16:24
Same here.
Also, Cron won't run using crontab anymore, stops at first step (local_o365\task\refreshsystemrefreshtoken), but runs manually.

**Comment by michael-LTS1** [comment] 2019-02-18 21:28
Same issue on Moodle 3.5.4+ / Plugin 3.5.0.2

**Comment by jamesmcq** [comment] 2019-02-26 01:26
Hi all - this can happen from time to time, but don't worry - it shouldn't affect your setup. We're looking at removing this check in the future as it's not as necessary as in the past. Thanks!

**Comment by ahmadm42** [comment] 2020-02-05 15:58
@jamesmcq, Hello. Any updates regarding this notice? Still not removed from Office 365 Plugin.

**Comment by jamesmcq** [comment] 2020-02-05 16:31
@ahmadm42 I am no longer the maintainer of this project. Please contact @weilai-irl

**Comment by ahmadm42** [comment] 2020-02-05 16:32
@jamesmcq. Thanks and sorry for the inconvenience.

**Comment by ahmadm42** [comment] 2020-02-05 16:33
@weilai-irl, FYI please. Thanks in advance.

**Comment by nenorojas** [comment] 2020-02-05 17:43
Hi @ahmadm42 , we have reopened this case and will evaluate the efforts to add in a future release.

**Comment by ahmadm42** [comment] 2020-02-05 18:23
@nenorojas , thanks in advance.

**Comment by bbusschots-mu** [comment] 2020-07-02 15:17
I'm having this same issue on the latest Moodle 3.5 LTS and the latest version of this plugin for Moodle 3.5.

**Comment by weilai-irl** [comment] 2020-07-16 12:00
Hi all,

A fix to the issue has been included in the latest release of the plugin suite for Moodle 3.7, 3.8 and 3.9 (release 3.7.0.7, 3.8.0.3, and 3.9.0 respectively). The root of the issue is the reply URL check was checking against an outdated version of server response, thus showing misleading warning messages. The check was updated now and would show no warning if the integration is configured correctly.

I'll close the issue now.

Regards,
Lai

**Closed by weilai-irl** 2020-07-16 12:00 UTC
Labels: In Progress, resolved - to be released

**Comment by jtyms** [comment] 2021-05-16 12:59
Hi guys, 

I have just updated to moodle 3.10+ and updated office365 integration (3.10) but it's giving me this error.

Thanks

![o365_error](https://user-images.githubusercontent.com/46805577/118398010-c224a400-b667-11eb-913f-60008c872ff0.PNG)

**Comment by weilai-irl** [comment] 2021-05-17 09:02
@jtyms,

I can confirm this is a separate issue as the one originally supported. Please create a new one in the future, or if you have any question about my answer below.

The reason you saw this is because the stored application token in your database was created for a different scope, possibly the legacy Azure AD API, rather than the new Graph API. To fix this, please check the following:
 - Ensure that "$CFG->local_o365_forcelegacyapi" is not set in the config.php in your wwwroot.
 - Delete stored app token or system API user token: in your database, run "`DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' AND name IN ('apptokens', 'systemtokens');`".
 - Delete stored Microsoft 365 setup status results: in your database, run "`DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' AND name = 'azuresetupresult';`".
 - Go back to the Microsoft 365 plugin configuration page, in step 3, click the button to grant admin consent.
 - Still on the Microsoft 365 plugin configuration page, in the "Verify setup" section, click the "update" button to verify settings.

This should remove any existing token, and create new ones.

Please give it a try. As I said, if this doesn't work, or if you have more questions, please create a new issue for it.

Regards,
Lai

**Comment by jtyms** [comment] 2021-05-18 03:34
@weilai-irl  

Thank you, I did the steps you have mentioned and it's now working. 

Regards,

J

**Comment by ssg1developer** [comment] 2022-08-30 08:00
hi, i'm using moodle 3.11 and OpenID connect 3.7.0.1 for office 365 authentication for our moodle site.
Suddenly there are problem when user sign in with their office 365 credential in our moodle site.
When we check in "Microsoft Office 365 Integration" menu, the Azure AD Setup cannot be done.

we try using the same application ID and key in our development site and there is no issue.


![image](https://user-images.githubusercontent.com/60211994/187382644-0b2fca77-4b7f-4937-832d-75109dd42c6f.png)

**Comment by weilai-irl** [comment] 2022-08-30 08:52
Hi @ssg1developer,

Please upgrade your auth_oidc plugin. 3.7.0.1 was from July 2019, and it has been out of support for very long time now. The latest release as of now is 3.11.4 can be downloaded at https://moodle.org/plugins/auth_oidc/3.11.4/26880 (auth_oidc)and https://moodle.org/plugins/local_o365/3.11.4/26886 (local_o365).

Regards,
Lai

**Comment by ssg1developer** [comment] 2022-08-30 17:58
Hi Lai, thanks for your respond.
we already follow your suggestion to update auth_oidc and local_o365 to latest version and now our client can login using office 365 authentication on our site.

**Comment by ssg1developer** [comment] 2024-02-12 09:10
Hi,
currently i'm using moodle 3.11.4 and update the OpenID plugin and local_o365 to version 3.11.5,
but when we try to verify setup, there is error message "There was an error checking legacy API settings.".
Any suggestion for me to check ?
