### ISSUE TITLE
Errors on usersync task

### ISSUE THREAD

**Issue by webframp** [microsoft/o365-moodle#1484] opened 2020-11-26 23:00 UTC
Hi @weilai-irl 

I am seeing these issues when running the user sync task with debug logs, is this a known issue or maybe something we need to cleanup in our data?

```
PHP Notice:  Undefined index: objectId in /www/local/o365/classes/feature/usersync/main.php on line 879
......... Azure AD user missing UPN (); skipping...
...... Checking deleted users list...
++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '1835595' found in column 'id'. ++
,* line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
,* line 1206 of /local/o365/classes/feature/usersync/main.php: call to mysqli_native_moodle_database->get_records_sql()
,* line 178 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->delete_users()
,* line 163 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()
++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '1835276' found in column 'id'. ++
,* line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
,* line 1206 of /local/o365/classes/feature/usersync/main.php: call to mysqli_native_moodle_database->get_records_sql()
,* line 178 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->delete_users()
,* line 163 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()
++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '1835799' found in column 'id'. ++
,* line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
,* line 1206 of /local/o365/classes/feature/usersync/main.php: call to mysqli_native_moodle_database->get_records_sql()
,* line 178 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->delete_users()
,* line 163 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()
++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '1828738' found in column 'id'. ++
,* line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
,* line 1206 of /local/o365/classes/feature/usersync/main.php: call to mysqli_native_moodle_database->get_records_sql()
,* line 178 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->delete_users()
,* line 163 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()
```
In the same sync run we see this error:
```
...... 97 users received. Syncing...
PHP Notice:  Undefined index: userPrincipalName in /www/local/o365/classes/feature/usersync/main.php on line 809
PHP Notice:  Undefined index: userPrincipalName in /www/local/o365/classes/feature/usersync/main.php on line 809
PHP Notice:  Undefined index: userPrincipalName in /www/local/o365/classes/feature/usersync/main.php on line 809
```

I'm also not sure if this is a data issue or plugin problem at this point.

Version info:
Plugin version 3.9.2 (release  Moodle 3.9: v20201123)
Moodle version: 3.9.3+ (Build: 20201121)
PHP Version: 7.3.25

**Comment by weilai-irl** [comment] 2021-01-07 16:24
Hi @webframp,

The first issue reported does seem to be a data error. Could you run the following query in your database, and see if it returns any value please.
```
SELECT a.*, b.*
FROM mdl_local_o365_objects a 
JOIN mdl_local_o365_objects b ON a.objectid = b.objectid
WHERE a.type = 'user'
AND b.type = 'user'
AND a.id < b.id
```
The query checks for duplicate records for the same office 365 user in the mdl_local_o365_objects table. If duplicates are found, you will need to remove the duplicates. Please compare moodleid field first before deleting anything. If duplicate records contain different moodleid, it may mean that an Office 365 user is matched with multiple Moodle users, in which case you will need to find out who are the Moodle users, and perform appropriate actions.


The second issue is relatively less concerning. The data processed at the line are taken directly from return values of Microsoft Graph API call to get users (line 328 in local/o365/classes/feature/usersync/main.php). It simply means that the user record returned doesn't have the "userPrincipalName" attribute, which can be caused by many reasons, e.g. user not fully set up etc. You can try to add debugging to show/save the raw return values, and find out which exact users are these, but I don't think this is absolutely necessary, and leave it as is wouldn't affect other part of the user sync task.

Regards,
Lai

**Comment by webframp** [comment] 2021-01-08 18:55
Thank you @weilai-irl! I'll try that query and investigate what we see with our data, that is helpful.

**Comment by mmulrthelp** [comment] 2021-02-10 10:59
Just to say that we are seeing these same issues which sometimes cause the sync to fail.

We only have 3 options set in the O365 plugin Sync settings:

- Create accounts in Moodle for users in Azure AD
- Update all accounts in Moodle for users in Azure AD
- Delete previously synced accounts in Moodle when they are deleted from Azure AD

Adding the 'Delete previously synced accounts in Moodle when they are deleted from Azure AD' seems to extend the sync runs out into nearly 5 hours from under 5 min. Any ideas why this might be @weilai-irl ?

Removing the duplicates fixes the issue where the sync occasionally stalls, but does not speed up the sync process.

We've yet to add the 'Delete previously synced accounts in Moodle when they are deleted from Azure AD' to our production site.

We are running: 
Moodle 3.8.7
local_o365 : 3.8.0.5 (2020020308)
PHP: 7.2.24-0ubuntu0.18.04.7

**Comment by weilai-irl** [comment] 2021-04-01 09:50
Hi all,

@webframp 
- The second issue in your report, which is about "Undefined index: userPrincipalName" has been addressed in pull requests - #1644 and #1645, and will be included in the May 2021 release.
Would you have and updates about the first issue?

@mmulrthelp,
- For the two issues covered by the original reporting, please see my other answers.
- Your comment mentioned another issue about performance when delete users option is enabled in user sync. I know what caused this, and have addressed it in pull requests #1644 and #1645, which are due to be released in May. The root of the issue was on how the task verifies status of existing users. The next release should improve the performance a lot.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-06-29 11:24
Hi all,

@webframp, the fix to the second issue has been included in the latest release of the plugins.
@mmulrthelp, the fix to the performance issue mentioned in your comments has been included in the latest release as well.

Please apply the latest release on your site to confirm they are working.

Regards,
Lai

**Closed by weilai-irl** 2021-06-29 11:24 UTC
Labels: triaged

**Comment by webframp** [comment] 2021-06-29 19:55
thank you @weilai-irl ! We'll test out these new versions as soon as possible.
