### ISSUE TITLE
Could not create team from group. Please check group exists and group has owner.

### ISSUE THREAD

**Issue by surazp** [microsoft/o365-moodle#1226] opened 2020-03-24 12:19 UTC
We are also having same issue

Execute scheduled task: Create user groups in Office 365 (local_o365\task\groupcreate)
All courses have a group recorded.
Attempting to create team for course #88...
Create team for course #88
Syncing to group "3f119b0f-e079-47d1-bff5-2a314a3e4838"
Could not create team for course #88. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #93...
Create team for course #93
Syncing to group "33d88f1a-c869-4663-8342-314b33c14bbb"
Could not create team for course #93. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #119...
Create team for course #119
Syncing to group "84717743-16e1-4bfb-8e47-75cf6826c169"
Could not create team for course #119. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #144...
Create team for course #144
Syncing to group "b4ca89a1-68e5-4f07-8eff-bf1ab19ac240"
Could not create team for course #144. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #145...
Create team for course #145
Syncing to group "4f97b3a7-f1a1-4b11-a76d-7a7fcb6de849"
Could not create team for course #145. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #159...
Create team for course #159
Syncing to group "6310cf27-3c84-412e-819f-743bbf7f1d5c"
Could not create team for course #159. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #160...
Create team for course #160
Syncing to group "4e914c65-8e9a-4985-ba8c-5c93c23c4188"
Could not create team for course #160. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #169...
Create team for course #169
Syncing to group "0719c66c-39df-4ae6-941f-9ea360f5ac4a"
Could not create team for course #169. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #181...
Create team for course #181
Syncing to group "24b47ef1-2dea-495a-904c-87662174aad4"
Could not create team for course #181. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #190...
Create team for course #190
Syncing to group "7bba8f23-dee2-4431-a827-a1f76b80d7ae"
Could not create team for course #190. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #998...
Create team for course #998
Syncing to group "9ff0b860-2967-446a-991d-83742d6e4652"
Could not create team for course #998. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #1757...
Create team for course #1757
Syncing to group "63cf4bf1-24e2-41f9-bf15-1a67aa87e743"
Could not create team for course #1757. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #1884...
Create team for course #1884
Syncing to group "d365b474-21d2-4e0a-b963-94e4642c161c"
Could not create team for course #1884. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2170...
Create team for course #2170
Syncing to group "9be0113a-5094-42f3-b381-b87ec9ebf612"
Could not create team for course #2170. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2232...
Create team for course #2232
Syncing to group "2ae5a81b-1bdf-4dd9-a0b1-8b8d6e1b9b08"
Could not create team for course #2232. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2233...
Create team for course #2233
Syncing to group "ae2d8b3a-b686-4240-b876-75c0607c6789"
Could not create team for course #2233. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2237...
Create team for course #2237
Syncing to group "ad90cff4-6fd3-4f34-a1d2-fd06b430743c"
Could not create team for course #2237. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2238...
Create team for course #2238
Syncing to group "704f8dc1-0017-4692-b294-3a8ebb9c6a85"
Could not create team for course #2238. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2239...
Create team for course #2239
Syncing to group "24657fbe-02ea-4b08-8de5-de53210066a5"
Could not create team for course #2239. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2240...
Create team for course #2240
Syncing to group "78ad793a-7ae7-43a5-ba59-b31995674ebd"
Could not create team for course #2240. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2244...
Create team for course #2244
Syncing to group "e28c552f-ef1d-48ef-8b3d-b43c04188f60"
Could not create team for course #2244. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2248...
Create team for course #2248
Syncing to group "044fbe6f-6d50-497b-a25c-f301c19937ee"
Could not create team for course #2248. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2249...
Create team for course #2249
Syncing to group "9bd39e40-a025-4b26-91ba-414c158335a5"
Could not create team for course #2249. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2250...
Create team for course #2250
Syncing to group "fc312ab6-f7b7-423a-9f04-9f29660b3415"
Could not create team for course #2250. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2256...
Create team for course #2256
Syncing to group "47d32d4f-0223-46c0-a580-88a5a38146ae"
Could not create team for course #2256. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2257...
Create team for course #2257
Syncing to group "885208be-985b-4d74-bc55-e78a5f6236fa"
Could not create team for course #2257. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2258...
Create team for course #2258
Syncing to group "ff09ecd5-022d-485e-9565-d06e7e58f64f"
Could not create team for course #2258. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2260...
Create team for course #2260
Syncing to group "47100b22-49a7-492a-9830-7e01c97e5b11"
Could not create team for course #2260. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2262...
Create team for course #2262
Syncing to group "85c69624-6573-4f6e-a8f4-7617f38a786e"
Could not create team for course #2262. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2263...
Create team for course #2263
Syncing to group "8447767f-4523-4a4a-a8a7-efbfe5d62711"
Could not create team for course #2263. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2264...
Create team for course #2264
Syncing to group "a521713b-3151-4a3a-a330-52dac54a8964"
Could not create team for course #2264. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2267...
Create team for course #2267
Syncing to group "879b03cf-62d2-44e3-9820-b8a1c0eec3f1"
Could not create team for course #2267. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2268...
Create team for course #2268
Syncing to group "25301938-d308-4f21-a83e-213a8511018a"
Could not create team for course #2268. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2269...
Create team for course #2269
Syncing to group "f32a1f7a-44fb-4e77-be41-8e1d0fd0689f"
Could not create team for course #2269. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2270...
Create team for course #2270
Syncing to group "6fe077ca-ff8a-4cbb-b8e8-529c22af7691"
Could not create team for course #2270. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2271...
Create team for course #2271
Syncing to group "f5cb401c-e8e8-427e-bfa7-2d7e47a6a147"
Could not create team for course #2271. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2272...
Create team for course #2272
Syncing to group "76c6b5d6-7706-47a9-945c-fbbebf128388"
Could not create team for course #2272. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2273...
Create team for course #2273
Syncing to group "83a74087-047b-454e-b193-6971473307e9"
Could not create team for course #2273. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2274...
Create team for course #2274
Syncing to group "2b8dd36a-2e51-426e-952b-854a1d7f1ebb"
Could not create team for course #2274. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2275...
Create team for course #2275
Syncing to group "92a22284-6ce5-4e11-a9cf-10c2491ccdd8"
Could not create team for course #2275. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2276...
Create team for course #2276
Syncing to group "27ed013a-67d5-4b0f-856a-27fba050087f"
Could not create team for course #2276. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2277...
Create team for course #2277
Syncing to group "d4b7023c-d19f-4e24-9ad7-299bba0032b8"
Could not create team for course #2277. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2278...
Create team for course #2278
Syncing to group "ff91aa07-dfa9-44e7-8c4c-bcddcc407162"
Could not create team for course #2278. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2279...
Create team for course #2279
Syncing to group "307b9d8c-d20c-4187-b50e-ccc213b18c74"
Could not create team for course #2279. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2280...
Create team for course #2280
Syncing to group "5cac86ff-5364-436a-a14c-ee450d925f54"
Could not create team for course #2280. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2281...
Create team for course #2281
Syncing to group "62697041-6d24-4c63-b7ac-a2f406fb1876"
Could not create team for course #2281. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2282...
Create team for course #2282
Syncing to group "0afc656e-f8af-4ec1-a917-61088e06a0f1"
Could not create team for course #2282. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2283...
Create team for course #2283
Syncing to group "3c3c21d1-8382-4fb7-b4a6-590591254f2a"
Could not create team for course #2283. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2284...
Create team for course #2284
Syncing to group "0dd45d68-5f79-481c-b2cf-351a1c69887e"
Could not create team for course #2284. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2285...
Create team for course #2285
Syncing to group "63f2ea4e-29fc-47c0-ab5f-75302cc6fa67"
Could not create team for course #2285. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2286...
Create team for course #2286
Syncing to group "624f3af5-1ba4-4b2a-a1cf-5dd983f24345"
Could not create team for course #2286. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2287...
Create team for course #2287
Syncing to group "fce86756-f8ec-4b65-bfa6-1df71374c1aa"
Could not create team for course #2287. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2288...
Create team for course #2288
Syncing to group "b9af8793-657b-4b22-bf23-0e87fe9b01e2"
Could not create team for course #2288. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2289...
Create team for course #2289
Syncing to group "465a57e8-538d-4024-847d-f245a09ab100"
Could not create team for course #2289. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2290...
Create team for course #2290
Syncing to group "9fc92797-709f-4616-8aaf-8719d0342973"
Could not create team for course #2290. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2291...
Create team for course #2291
Syncing to group "536bbd3b-3454-465b-8083-844cc317ea09"
Could not create team for course #2291. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2295...
Create team for course #2295
Syncing to group "85cce410-42e0-4f6b-a84e-ded5599cf0ca"
Could not create team for course #2295. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2297...
Create team for course #2297
Syncing to group "61f030ca-f8f5-4e45-923c-dbe283cb63dd"
Could not create team for course #2297. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2302...
Create team for course #2302
Syncing to group "df7b891c-b4aa-4ff8-a344-a4c9d71d4d06"
Could not create team for course #2302. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2305...
Create team for course #2305
Syncing to group "f83faa65-dfe3-4f9f-9898-49ed688e44a3"
Could not create team for course #2305. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2308...
Create team for course #2308
Syncing to group "e9ce1b27-38fa-4ff7-a361-61bf606abe4c"
Could not create team for course #2308. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2313...
Create team for course #2313
Syncing to group "ded88e23-e3a9-4d61-a492-9dc77fa9cf3e"
Could not create team for course #2313. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2315...
Create team for course #2315
Syncing to group "597a02c1-0935-44f5-b6ba-7db8d67e2200"
Could not create team for course #2315. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2318...
Create team for course #2318
Syncing to group "30114401-5683-411c-a648-ab720d2676e3"
Could not create team for course #2318. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2319...
Create team for course #2319
Syncing to group "82d712eb-bd5f-431b-96dd-56e107dc8fe6"
Could not create team for course #2319. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2320...
Create team for course #2320
Syncing to group "dfe096a3-a65c-45c1-b8c8-59e07df69fe0"
Could not create team for course #2320. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2322...
Create team for course #2322
Syncing to group "0df35e92-1d93-421a-907e-7da0589e3587"
Could not create team for course #2322. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2323...
Create team for course #2323
Syncing to group "c2c06898-c655-48a5-9bbd-fe6628298cbf"
Could not create team for course #2323. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2324...
Create team for course #2324
Syncing to group "b0b49c18-271d-4464-95fa-a79772082354"
Could not create team for course #2324. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2328...
Create team for course #2328
Syncing to group "9b4a796a-901d-4bb1-9023-eb32282f6417"
Could not create team for course #2328. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2329...
Create team for course #2329
Syncing to group "a2252730-efba-4e6b-a23c-fb8b361df782"
Could not create team for course #2329. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2330...
Create team for course #2330
Syncing to group "f759ca22-5717-4ed6-86cb-5489ca2c902e"
Could not create team for course #2330. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2331...
Create team for course #2331
Syncing to group "feee4242-b9a1-4726-9b55-63bea5adf3ad"
Could not create team for course #2331. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2364...
Create team for course #2364
Syncing to group "a2c50597-6f2e-46a4-8504-f040e29d1d1d"
Could not create team for course #2364. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2367...
Create team for course #2367
Syncing to group "6db2ef53-8230-4d28-8c83-9065bc599f0e"
Could not create team for course #2367. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2368...
Create team for course #2368
Syncing to group "179513eb-005c-440a-ae5e-aca3d8d71235"
Could not create team for course #2368. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2369...
Create team for course #2369
Syncing to group "068615dc-4588-4f2b-95d9-e45750b73306"
Could not create team for course #2369. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2370...
Create team for course #2370
Syncing to group "ecb9e85f-e124-4293-9130-7ace6f492c92"
Could not create team for course #2370. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2372...
Create team for course #2372
Syncing to group "23310015-0a7a-4229-b77d-a4a721921eba"
Could not create team for course #2372. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2375...
Create team for course #2375
Syncing to group "5a0d6bdc-05ce-4c0e-857b-d803fbc3ff53"
Could not create team for course #2375. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2381...
Create team for course #2381
Syncing to group "d9c7baa4-bf65-488b-b3f3-c1256c442dce"
Could not create team for course #2381. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2437...
Create team for course #2437
Syncing to group "a48f3b2f-71a1-424b-b96a-1861da451b18"
Could not create team for course #2437. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2442...
Create team for course #2442
Syncing to group "cbfd11b7-7cdb-473a-8d4a-67ae7606c4bf"
Could not create team for course #2442. Reason: Could not create team from group. Please check group exists and group has owner.
Attempting to create team for course #2443...
Create team for course #2443
Syncing to group "94e0172e-c25c-41b7-9578-68be4a4ce930"
Could not create team for course #2443. Reason: Could not create team from group. Please check group exists and group has owner.
... used 262 dbqueries
... used 64.724762916565 seconds
Scheduled task complete: Create user groups in Office 365 (local_o365\task\groupcreate)

_Originally posted by @protocol061 in https://github.com/microsoft/o365-moodle/issues/1222#issuecomment-603205513_

**Comment by shaunt-nait** [comment] 2020-07-23 14:56
I'm also experiencing this issue with 3.8. Can anyone provide a patch or work around?

**Comment by weilai-irl** [comment] 2020-07-23 15:08
@shaunt-nait @protocol061,

In general there are two things to try here.
1. Upgrade the plugins to the latest version. Release 3.7.0.7 (for Moodle 3.7) and 3.8.0.3 (for Moodle 3.8) have some changes that may help reducing number of courses that you see this message.
2. There is a known issue in the logic to determine course teachers - it currently only looks for roles with shortname "editingteacher" and "teacher", so if you use custom roles (or modified the default roles) for assigning teachers to the courses, they may be not picked up correctly. And if there is no teachers who are office365 users (determined by using auth_oidc authentication method), Teams cannot be created. This issue has been tracked in https://github.com/microsoft/o365-moodle/issues/1235, and will be fixed in the next release.
3. In some rare cases, we have seen issues caused by using "system API user" as connection method in the local_o365 settings. If your site uses it (rather than "application access"), you will need to make sure that the system API user in office365 has Teams license.

Regards,
Lai

**Comment by diddiminn** [comment] 2021-01-12 12:45
I have the same issue (and more):
[local_o365_task_groupcreate-7271805.log](https://github.com/microsoft/o365-moodle/files/5802100/local_o365_task_groupcreate-7271805.log)

My system:
**Moodle**: 3.9.3+ (Build: 20201217)
**database:** mariadb (5.5.5-10.5.8-MariaDB-1:10.5.8+maria~bionic)
**PHP** 7.4.13

**Authentication method:**
OpenID Connect
auth_oidc
3.9.2
2020071502

**Local plugins:**

Microsoft Office 365 Integration
local_o365
3.9.2
2020071504

Office 365 Integration
local_office365
3.9.2
2020071503

**Repositories:**
Office 365
repository_office365
3.9.2
2020071502
Disabled (hmm should it be enabled?)

**Comment by weilai-irl** [comment] 2024-10-22 10:54
I know this is a long shot, but the latest release from earlier this month (`[4.4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20241017_m404)`, `[4.3.6](https://github.com/microsoft/o365-moodle/releases/tag/v20241017_m403)`, `[4.2.8](https://github.com/microsoft/o365-moodle/releases/tag/v20241017_m402)` and `[4.1.9](https://github.com/microsoft/o365-moodle/releases/tag/v20241017_m401)`) contain some improvements in the course sync scheduled task, which would automatically detect groups that do no exist any more, and perform appropriate action, e.g. deleting invalid records and creating new ones.

I'll close this issue for this reason.

Regards,
Lai

**Closed by weilai-irl** 2024-10-22 10:54 UTC
Labels: Issue type - help wanted, Triaging status - triaged, Feature - teams integration, Plugin - local_o365, Status - queued / not yet started
