### ISSUE TITLE
Mass user deletion performed by office 365 sync task

### ISSUE THREAD

**Issue by CtanShard** [microsoft/o365-moodle#1650] opened 2021-04-02 16:25 UTC
A client site of ours has had two repeat instances of mass deletion in their Moodle site recently.  In both instances the office sync task began deleting user accounts during an Office 365 server connection failure.  The most recent outage was on April 1st and it can be seen here on down detector: https://downdetector.com/status/office-365/ ;  The sync has worked perfectly otherwise.  

This has been a serious setback for this client both times because it has forced them to revert to a previous snapshot of the site and costs many user's their progress in courses.  Why would the sync task believe it should delete users during a failure to connect to Microsoft's servers?.  

During the most recent event on April 1st, I was able to stop the deletions halfway through by removing the 'Delete previously synced' flag in the sync settings.  The task instead started to suspend accounts instead of deleting them.  

Any insight would be appreciated,
Robert

**Comment by mmulrthelp** [comment] 2021-04-08 15:16
@CtanShard We are testing this side before enabling it, so interested in the outcome. What versions of the Office365 plugins & Moodle are you seeing this happen on?

**Comment by CtanShard** [comment] 2021-04-09 14:25
Hi @mmulrthelp . The site we are observing this in has local_o365 version 3.7.0.6 .  The Moodle instance is 3.7.6 .

**Comment by mmulrthelp** [comment] 2021-04-09 15:04
@CtanShard Thank you for letting me know, I cannot imagine you will get a fix for it as Moodle 3.7.x is outside of the support window https://docs.moodle.org/dev/Releases#General_release_calendar

**Comment by weilai-irl** [comment] 2021-04-12 10:58
Hi @CtanShard,

This is a known issue as reported in #1325, and was fixed in November 2020 in release 3.8.0.5 and 3.9.2 for Moodle 3.8 and 3.9 respectively. Please see the explanation of the cause and the solution at https://github.com/microsoft/o365-moodle/issues/1325#issuecomment-722342214.

As @mmulrthelp pointed out, feature and bug fix support for plugin versions for Moodle 3.7 has ended, so the fix will not come to the release versions for the 3.7.x branches. Your best shot would be to upgrade your site to Moodle 3.9, or to backport the plugins versions that contains the fix (3.8.0.5 or later) to Moodle 3.7.

Regards,
Lai

**Closed by weilai-irl** 2021-04-12 10:58 UTC
