### ISSUE TITLE
Manager field not updated when logging in

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#2213] opened 2022-11-04 12:41 UTC
Hi

seems that user's Manager information is only brought to Moodle with usersync, but not when user is logging in.
Even tough userfield mapping is set to update "On creation, **every login**, and every user sync task run".

It should update also when logging in, because usersync is not used in every case.

**Comment by kkiiskin** [comment] 2022-11-07 12:49
Hi

actually none of the mapped fields seem to update to Moodle when user logs in?
I have Azure Ad email-field mapped to Moodle's email field, but it updates UPN to the Moodle email field when user logs in.
Usersync brings the actual email though.

We are running Moodle 3.9 so we have latest 3.9-versions of auth_oidc & local_o365 plugins.

**Comment by Mor-dev** [comment] 2022-11-18 15:30
I also experience above issue with Moodle: 3.11.10 (build: 20220912), local_o365 (2021051730), auth_oidc 2021051730. 

Also, when the user logs in, he loses his country value in the user information page. (the country value was there after \local_o365\task\usersyncc  )

Mapping:
![Selection_198](https://user-images.githubusercontent.com/84913715/202737329-394bb91e-b286-4c6d-a7cd-6198f6b2d25b.png)
Database user table:
![Selection_200](https://user-images.githubusercontent.com/84913715/202739992-d4b71192-092b-40dc-9359-6203f2289659.png)

**Comment by kkiiskin** [comment] 2022-11-22 08:10
@weilai-irl is there any information on this?
The general problem is that userfields don't update when loggin in, not just the manager field specifically.

We are running Moodle 3.9.18 and oidc & o365 plugins are version 3.9.11 (2020071560).

**Comment by Mor-dev** [comment] 2022-11-24 09:48
Any update on this.

We use the country field to assign users to a cohort, and it does not work when the country value goes empty when user login into Moodle.

Thank you in advance.

**Comment by weilai-irl** [comment] 2022-11-24 10:16
Hi all,

Sorry for the delay. We have been extremely busy recently and we haven't got a chance to review this.

I'll try to confirm the issue in the next week, and once confirmed, I'll try to provide a solution. Please bare with me.

Regards,
Lai

**Comment by kkiiskin** [comment] 2022-12-08 10:55
Hi @weilai-irl ,

have you had time to replicate this?

**Comment by weilai-irl** [comment] 2022-12-08 11:20
Hi @kkiiskin,

I have asked our test team to reproduce this issue but they didn't manage to reproduce it in our environment for Moodle 3.9. They did spot an issue with the sync of the field in Moodle 3.11 and 4.0 when using the new Microsoft Identity Platform v2 connection method which was introduced in the September release, but since you are on Moodle 3.9, this should be a separate issue.

I haven't got a chance a to look into the findings myself, and I'm quite busy at the moment and probably won't have availability for this until January. I'm afraid you may need to wait a bit. I apologise for the delay.

Regards,
Lai

**Comment by weilai-irl** [comment] 2023-03-03 16:55
Hi @kkiiskin

I can't reproduce the issue in any of the Moodle versions mentioned.

I have tested in the following environments:
 - Moodle 3.9.19 (Build: 20230116)
   - auth_oidc: release 3.9.11, version 2020071560
   - local_o365: release 3.9.11, version 2020071560
 - Moodle 3.11.12 (Build: 20230116)
   - auth_oidc: release 3.11.6, version 2021051735
   - local_o365: release 3.11.6, version 2021051735
 - Moodle 4.0.6 (Build: 20230116)
   - auth_oidc: release 4.0.3, version 2022041915
   - local_o365: release 4.0.3, version 2022041915
 - Moodle 4.1.1 (Build: 20230116)
   - auth_oidc: release 4.1.1, version 2022112805
   - local_o365: release 4.1.1, version 2022112805

Could you check if your Azure app has all the required permission in the local_o365 plugin configuration page please. I suspect it might be related, but if any permission is missing, the field wouldn't be sync in user sync task either, so it's likely not the root of your issue.

Could you also confirm if the user in question is using auth_oidc? I assume yes, but just to confirm.

Regards,
Lai

**Comment by kkiiskin** [comment] 2023-03-10 06:41
Hi @weilai-irl 

providing admin consent from local_o365 plugin settings page seemd to solve this problem, as described here
https://github.com/microsoft/o365-moodle/issues/2268

We have only granted admin consent from Azure AD in the App "API permissions" page, because everything seems to work fine (until now) with only that  and I didn't know that granting them from Moodle's side would also fetch/update the aadtenantid to Moodle's database.

We also use minimum Api permission in our implementations - mainly user.read.all and directory.read.all - which may affect this. But as I said, granting the consent from Moodle seemd to fix this at least in 3.9-versions.

**Comment by weilai-irl** [comment] 2023-03-10 09:26
Hi @kkiiskin 

Thank you for your confirmation, and I'm glad the issue is resolved.

Admin consent is indeed required from both places - Azure portal and Moodle configuration page. Otherwise the plugin may not be able to get a token to be able to communicate with Graph API endpoint.

I'll close this issue now.

Regards,
Lai

**Closed by weilai-irl** 2023-03-10 09:26 UTC
Labels: Issue type - help wanted, Status - In Progress, Feature - user sync, Plugin - auth_oidc, Plugin - local_o365

**Comment by kkiiskin** [comment] 2023-08-23 06:07
Hi @weilai-irl

that admin consent from Moodle is proving to be a bit troublesome. 

We need client's Azure AD global admin account to provide it OR we have to give Moodle admin account (temporarily) to someone who has the global admins. And in one case the AAD admin refused to do the admin consent from Moodle for 'security reasons'.

When it comes to Azure AD tenant id, could we just insert it straight to database?
To the table mdl_config_plugins, plugin local_o365 and name aadtenantid
