### ISSUE TITLE
Email coming from the UPN in Azure AD - Connected to other issues

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#2066] opened 2022-05-25 14:54 UTC
Hi @weilai-irl 

We've spotted an issue which we think has only just come about in the latest code release 3.11.3 for Moodle 3.11

In Azure AD (I'll use my record as an example) - My UPN is my institution ID @ domain , not my email address which allows me to authenticate with systems, such as Moodle.
![image](https://user-images.githubusercontent.com/16646247/170289146-4edf4eba-668f-4019-93cd-b893c1874f17.png)

In the above record you can see that my email address is different to my UPN.

'Sync users with Azure AD' scheduled task has started to sync in the UPN as the email for all users in our Moodle.
![image](https://user-images.githubusercontent.com/16646247/170291396-fd7e7342-158a-4042-9733-90ed9201ec1f.png)

Currently we do not have this switched on 
![image](https://user-images.githubusercontent.com/16646247/170291581-430f2f6a-58ed-4a51-993d-168bc5789b76.png)

On testing on our UAT environment, ticking this slowly brings back the email address as the email within Moodle.
On UAT after ticking the above, the sync is showing 
![image](https://user-images.githubusercontent.com/16646247/170293238-dbe9675a-6937-4080-b2cc-91b62d7979a1.png)

Is this a bug or is it the way it is supposed to be, as I know many place authenticate to Microsoft using the email address as their UPN, we do not.

This is causing our LTI integrations to fail where it has already created an account on the other end as the email address supplied by Moodle, which was the email address not the UPN.

This is possible connected to other mentioned issues #1987 & #1974 

Many thanks for any further information.
Ray Reid.

**Comment by mmulrthelp** [comment] 2022-05-26 09:24
@weilai-irl this is still an issue, a full sync has reverted us back to email as email. But on the next non full sync run it has reverted it back to using the UPN for email.

Any ideas why this is and how to fix ?

**Comment by weilai-irl** [comment] 2022-06-08 09:05
Hi @mmulrthelp,

Could you confirm the options in the "email" section of the "Data mapping" part in your auth_oidc configuration please. There has been a change in this part in the last release in April 2022 - instead of allowing the email profile field to be not mapped or mapped to any remote field, the options was limited to "UPN" and "email" only, and not mapped is no longer an option. This effectively means if your previous setting was to not map the email field, is would start mapping it now.

To avoid this - you can try to set the "Update local (Email address)" setting to "On creation". This will skip the logic to update Moodle user email profile field on user login and user sync task. Please give this a try after confirming that all Moodle users have correct email addresses.


Separately, regarding the fact that full user sync and delta user sync gave different results - this might be related to how the delta token used in delta sync works. The delta token itself contains the list of profile fields to be returned, and you can't add new fields to it without creating a new delta token. So what might have happened was when your delta token was initially created, the email field was not on the list of fields, so only UPN was returned. When processing the results, since the email field was not included, it uses the UPN field. You can delete the delta token from the database to force resetting the list of fields. Note this will effectively make your next delta sync a full sync, but after that delta sync should work the same way. The SQL to run is:
`DELECT FROM mdl_config_plugins WHERE plugin = "local_o365" AND name = "task_usersync_lastdeltatoken";`

Regards,
Lai

**Comment by mmulrthelp** [comment] 2022-06-08 15:21
Thanks for getting back to me @weilai-irl , I've asked our hosting partner to delete the delta token via the SQL above to trigger a full sync. Does this page not do the same thing ? /local/o365/acp.php?mode=maintenance_cleandeltatoken

I've now set the email option to "On creation", this to my knowledge has always been set to "On creation, every login, and every user sync task run". Since we first had these plugins in place from 2019
![image](https://user-images.githubusercontent.com/16646247/172653779-f540cdef-cf8f-4371-8a1e-49de77f1e195.png)

I'll let you know how I get on. There are times when email addresses for users could be updated, like when their name changes by marriage or the like, so I'd like to be able to set and keep this to "On creation, every login, and every user sync task run".

Regards,
Ray.

**Comment by weilai-irl** [comment] 2022-06-09 10:56
Hi @mmulrthelp,

The tool you referred achieve the same effect. I forgot there was an existing tool doing just that. Sorry for the confusion.

Regarding the sync settings, previously it was possible to not map the email profile field with a remote field, which caused issues on many new sites using the plugin to create user accounts on first login. The change in the April release limited the available remote fields, and removed the ability to not map the email field. This may force a field mapping change and I agree this may cause issues on sites previously not configured to map email fields.

The "On creation" setting in the "Update local" field should do the trick in your case. I'll see if a better solution is possible.

Regards,
Lai

**Comment by mmulrthelp** [comment] 2022-06-21 09:29
Hi @weilai-irl I've had some trouble doing a successful full sync, which I've now cracked to see if when "On Creation" is set in "Update local (Email address)" in OIDC settings whether that then bring in the 'Email' as the 'Email' to the user profile. But it still does not. Therefore I've created the following 4 minute video to hopefully better explain what is happening. I would really appreciate your opinion on this.

https://mmutube.mmu.ac.uk/media/UPN+as+Email+address/1_6dqh707t

**Comment by mmulrthelp** [comment] 2022-07-07 07:18
Sorry to pester @weilai-irl any thoughts when you watch the above video as to what we are seeing and how to fix?

**Comment by weilai-irl** [comment] 2022-07-26 20:26
After some investigation, we eventually found out the cause of the issue in this one.

- The site was created some time ago, and it somehow missed a required step in one of the recent upgrade, which requires Azure admin to click the "Provide admin consent" button in the local_o365 configuration page. As a result, the site doesn't have a site config "aadtenantid" for plugin local_o365.
- The "aadtenantid" config of local_o365 is used by auth_oidc to compare to the tenant ID in the ID token of the logged user, in order to determine if the user is from the hosting tenant. The auth_oidc plugin will only attempt to get user profiles from Microsoft 365 via Graph API calls if the user is from the hosting tenant, because the Azure app wouldn't have permission to make the call to any other tenant rather than the hosting one.
- Because "aadtenantid" config of local_o365 is missing, none logged in users are treated as from the hosting tenant, therefore no Graph API calls are made to get their profile.
- For users from non-hosting tenant, auth_oidc would use their ID token claims for field mapping. The "email" claim can be missing from the ID token claims, and in cases like this, auth_oidc has a logic to use UPN claim, which is always available, as the email. This resulted in the UPN to be used as email and replacing the Moodle email profile for users on login.
- Note that running the user sync task doesn't check for "aadtenantid" config to match users, so it would get user details from Graph API, resulting in fetching the correct emails.

The issue is fixed after Azure admin provided admin consent from local_o365 configuration page.

@mmulrthelp, please confirm the above.

If everything is fixed, can we close this issue?

Regards,
Lai

**Comment by mmulrthelp** [comment] 2022-07-27 07:26
The above sums it up perfectly.

Many thanks for your help in solving this @weilai-irl 

Regards,
Ray.

**Closed** 2022-07-27 07:26 UTC
Labels: Issue type - help wanted, Status - need more info, Feature - user sync, Plugin - auth_oidc, Plugin - local_o365
