### ISSUE TITLE
usersync task definition inconsistent with description in settings

### ISSUE THREAD

**Issue by ak4t0sh** [microsoft/o365-moodle#1442] opened 2020-10-21 08:38 UTC
- Plugin : **local_o365**
- Release : **3.9.1 (2020071502)**
- Setting URL : **https://mymoodle/admin/settings.php?section=local_o365&s_local_o365_tabs=1**

https://github.com/microsoft/o365-moodle/blob/7a4000afea2127a56602ae3839bf6b44c6da1b5a/local/o365/lang/en/local_o365.php#L284

> By default, this runs once per day at 1:00 AM in the time zone local to your server. 

But default is to run each minute between 01:00 and 02:00.
https://github.com/microsoft/o365-moodle/blob/7a4000afea2127a56602ae3839bf6b44c6da1b5a/local/o365/db/tasks.php#L35-L41

IMO by default it should only run once at 01:00 but what is the intended behavior ?

**Comment by weilai-irl** [comment] 2020-10-23 09:08
Hi @ak4t0sh,

I confirm this is intended behaviour. Moodle scheduled tasks need to be triggered by Moodle cronjob run. The task will be triggered on the first Moodle cronjob run after the configured time, so in effect, it will be the first run after 1am by default.

Moodle 3.9 recommend running Moodle cron every minute, so unless there are other tasks taking long time to finish, this should always run at 1am.

For more information on Moodle scheduled tasks, please refer to Moodle Docs at https://docs.moodle.org/39/en/Scheduled_tasks.

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-03 17:05
@ak4t0sh,

I apologise for the confusion in my last note. This is indeed a bug in the code. A fix to the issue will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-18 14:42
Hi @ak4t0sh ,

We have fixed the issue in the latest release (3.8.0.5 and 3.9.2) of the plugins. Thank you again for reporting the issue.

Regards,
Lai

**Closed by weilai-irl** 2020-11-18 14:42 UTC
