### ISSUE TITLE
SSO for Teams App

### ISSUE THREAD

**Issue by Zhuich** [microsoft/o365-moodle#1550] opened 2021-01-22 10:44 UTC
I have moodle with O365 integration. I add into Teams app personal tab, which linked to my moodle. It's work perfect with password auth, but, when i click on Open ID Connect auth - i see black screen in Teams tab. Please, help me!

**Comment by nenorojas** [comment] 2021-01-27 17:53
Hi @Zhuich ,

What's the Moodle version you are and what's the version of the plugins auth_oidc and local_o365 you are using?

Regards

**Comment by Zhuich** [comment] 2021-01-27 20:44
Hi @nenorojas!
We use Moodle 3.9.3, local_o365 moodle39 (2020071504) and auth_oidc moodle39(2020071502).

**Comment by nenorojas** [comment] 2021-01-28 11:12
Hi @Zhuich ,

Have you created the application on Azure using the PowerShell script? If yes, please double check if you have performed the extra manual steps needed on the application listed here: https://docs.moodle.org/310/en/Office365#3.8.0.4_and_3.9.1_release

![image](https://user-images.githubusercontent.com/3680797/106130281-10657400-6159-11eb-870f-ecf926895887.png)

And after it's done, please download a new manifest file and update your custom app on the Teams admin page: https://admin.teams.microsoft.com > Teams apps > Manage apps.

![image](https://user-images.githubusercontent.com/3680797/106130421-38ed6e00-6159-11eb-97bc-21cdc25902de.png)

We are releasing a new version of plugins for Moodle 3.9 and first version for 3.10, if you would like to upgrade your plugins as well to latest version, that should contain other bug fixes.

Regards

**Comment by klovsb** [comment] 2021-03-15 19:58
@nenorojas  I had reported similar problem months ago and had since keeping the suite of plugin uptodate.  I am seeing new report of the issue and frankly none of the fixes mentioned in different threads work.  The Team-Moodle integration worked beautifully on version 3.8.0.4 but right after that the Login to Microsoft 365 failed.

Anyway, we are now on local 365 version 3.9.3 on Moodle version 3.9+.  The latest troubleshoot points me to an uncaught error as followed.  I managed to capture this on Chrome's Dev tool.  Behavior of Login to Microsoft 365 on desktop Team app or on browser is similar.  I just can't capture any error mesage on the desktop app.  We are on Azure.
----
teams_tab_configuration.php:95 Uncaught ReferenceError: config is not defined
    at Object.successCallback (teams_tab_configuration.php:95)
    at r.GlobalVars.handlers.authentication.authenticate.success (MicrosoftTeams.min.js:1)
    at c (MicrosoftTeams.min.js:1)
    at Object.n.processMessage (MicrosoftTeams.min.js:1)
    at t (MicrosoftTeams.min.js:1)

**Comment by klovsb** [comment] 2021-03-15 20:00
Clarification: We are on Microsoft Office 365.  The Moodle server is on premise.

**Comment by klovsb** [comment] 2021-03-15 20:15
I reported this on #1466 .

**Comment by weilai-irl** [comment] 2021-03-15 21:47
Hi @klovsb,

I have made pull requests for 3.9 and 3.10 to fix the exact issue that you mentioned in your note https://github.com/microsoft/o365-moodle/issues/1550#issuecomment-799711295, in which it reports "config is not defined". This will be included in the upcoming release, but feel free to apply the code change manually to see if it works.

My feeling is the issue is somewhere else, e.g. Azure app configuration, permissions etc. In normal use cases, SSO should work silently, without requiring users to click on the manual login buttons. But if the button was shown and clicked, I confirm the last release (3.9.3 and 3.10.0) was missing a config variable, and the pull request should fix it.

Please give it a try (or wait until the release) to let us know.

Regards,
Lai

**Comment by klovsb** [comment] 2021-03-16 16:59
@weilai-irl  I have already tried that.  No effect.  I also noticed a warning about CSP blocking https://teams.microsoft.com/_ .  Directive base-uri.  Source location: 0-angular-jquery.min-eee9041.js:1.  I added it to our IIS Custom HTTP Respond (without the trailing /_).  Reset IIS and tried again.   I then get error refused to set the document's base URI to 'https://teams.microsoft.com/#/sc********' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".  Then another error POST https://teams.microsoft.com/api/me/amer/beta/users/fetchFederated 403.

**Comment by klovsb** [comment] 2021-03-16 17:07
It is still not working.  All these errors are in the browser console.  Nothing moves on the login page.  

We always have the manual login button though.  I didn't turn that off so that I can use the admin account.  The manual login button would always let me in either with OIDC or manual login but it won't let me finish adding a course tab.

Would the older version 3.8.0.3 still work if I roll back on a Moodle 3.9.*?  That would be my last resort.

Johnny

**Comment by weilai-irl** [comment] 2021-03-16 17:20
@klovsb, 

What login flow are you using in the auth_oidc settings on the Moodle site? We noticed recently that "Resource Owner Password Credentials Grant" doesn't work with Teams SSO.

Regards,
Lai

**Comment by klovsb** [comment] 2021-03-16 18:14
We have been using the recommended Authorization Code Flow since 3.8.0.3.

**Comment by klovsb** [comment] 2021-03-16 18:18
Team-Moodle has worked beautifully on 3.8.0.3 and before.  I am not sure starting from which one, 3.8.0.4 or 3.8.0.5, that it stopped working.  To troubleshoot Azure tenant setting I need to get the Office 365 supervisor to do it so I like to make sure I have truly exhausted the Moodle application and server site troubleshooting before I make another request.

**Comment by weilai-irl** [comment] 2021-03-16 19:32
@klovsb,

As explained on the wiki page, there was a major upgrade of the Teams SSO feature from 3.8.0.3 to 3.8.0.4. The updated version was implemented in line with the latest guidelines from Microsoft on how to authenticate apps in Teams. It was aimed at improving the user experience, obviously, rather than breaking it.

It's in our plan to improve the documentation particularly about the Teams SSO, and maybe introduce a FAQ section or separate FAQ page on the wiki. Clearly many factors on either Microsoft 365 or Moodle side can affect the normal operation of Teams SSO. With that in mind, if you email me (in my profile) your contact details, I can look at setting up a quick call with you after the March release to see if I can spot the cause of the issue, with a view to gather common issues to be included in the documentation.

Regards,
Lai

**Comment by klovsb** [comment] 2021-03-17 18:17
I had our Office365 supervisor updated the app with the steps listed above.  It still does not work.  I am attaching the browser console error log here. All domain names and ID are masked for privacy.  I have tried adding base-uri directives in CSP but was refused due to a violation.

0-angular-jquery.min-eee9041.js:1 Refused to set the document's base URI to 'https://teams.microsoft.com/_#/school/conversations/General?threadId=1*****************************@thread.skype&ctx=channel' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".
k.parseHTML @ 0-angular-jquery.min-eee9041.js:1
i.updateSearchString @ 3.1-app.min-74276cf.js:1
i.setConversationId @ 3.1-app.min-74276cf.js:1
t.updateEditorHandlers @ 3.2-app.min-5dc2fb6.js:1
t.initEditor @ 3.2-app.min-5dc2fb6.js:1
link @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:76
ka @ 0-angular-jquery.min-eee9041.js:76
n @ 0-angular-jquery.min-eee9041.js:62
g @ 0-angular-jquery.min-eee9041.js:54
(anonymous) @ 0-angular-jquery.min-eee9041.js:53
(anonymous) @ 0-angular-jquery.min-eee9041.js:58
d @ 0-angular-jquery.min-eee9041.js:55
l @ 0-angular-jquery.min-eee9041.js:59
(anonymous) @ 0-angular-jquery.min-eee9041.js:270
$digest @ 0-angular-jquery.min-eee9041.js:140
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:93
x @ 0-angular-jquery.min-eee9041.js:97
w.onload @ 0-angular-jquery.min-eee9041.js:98
load (async)
(anonymous) @ 0-angular-jquery.min-eee9041.js:98
r @ 0-angular-jquery.min-eee9041.js:94
g @ 0-angular-jquery.min-eee9041.js:91
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:270
dispatch @ 0-angular-jquery.min-eee9041.js:1
v.handle @ 0-angular-jquery.min-eee9041.js:1
_#/school/conversations/General?threadId=19:e06bdf6b31b74cd1bac284969d0366ee@thread.skype&ctx=channel:1 Invalid 'X-Frame-Options' header encountered when loading 'https://********.*****.***.**/': 'ALLOW-FROM https://********.******.******' is not a recognized directive. The header will be ignored.
0-angular-jquery.min-eee9041.js:114 2021-03-17T17:22:53.620Z AUTHMSAL: Event: adal:tokenRenewFailure, code: invalid_resource|AADSTS500011: The resource principal named api://********.*****.***.**/moodle-path/************************************ was not found in the tenant named ************************************. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 6cbda6ca-7348-4e02-ad55-93f681f6a600
Correlation ID: 1b00375e-fc22-4ebb-9ddc-f4ae55d9633a
Timestamp: 2021-03-17 17:22:53Z, resource: api://********.*****.***.**/moodle-path/************************************, action: resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.logTokenResponse @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
0-angular-jquery.min-eee9041.js:114 2021-03-17T17:22:53.621Z AUTHMSAL: Attempting to handle auth response: error:invalid_resource|AADSTS500011: The resource principal named api://********.*****.***.**/moodle-path/************************************ was not found in the tenant named ************************************. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:api://********.*****.***.**/moodle-path/************************************, error mapped to action:resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.handleAuthError @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
0-angular-jquery.min-eee9041.js:114 2021-03-17T17:22:53.621Z AUTHMSAL: Attempting to handle auth response: error:invalid_resource|AADSTS500011: The resource principal named api://********.*****.***.**/moodle-path/************************************ was not found in the tenant named ************************************. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:api://********.*****.***.**/moodle-path/************************************, error mapped to action:resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.handleAuthError @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
0-angular-jquery.min-eee9041.js:114 2021-03-17T17:22:53.622Z ExtensionTabService: getAuthTokenForApp: Failed with error - resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
adal.min.js:2 Uncaught TypeError: Cannot read property 'displayCall' of undefined
    at new AuthenticationContext (adal.min.js:2)
    at Object.successCallback (teams_tab_configuration.php:99)
    at r.GlobalVars.handlers.authentication.authenticate.success (MicrosoftTeams.min.js:1)
    at c (MicrosoftTeams.min.js:1)
    at Object.n.processMessage (MicrosoftTeams.min.js:1)
    at t (MicrosoftTeams.min.js:1)
AuthenticationContext @ adal.min.js:2
successCallback @ teams_tab_configuration.php:99
r.GlobalVars.handlers.authentication.authenticate.success @ MicrosoftTeams.min.js:1
c @ MicrosoftTeams.min.js:1
n.processMessage @ MicrosoftTeams.min.js:1
t @ MicrosoftTeams.min.js:1
postMessage (async)
g @ MicrosoftTeams.min.js:1
l @ MicrosoftTeams.min.js:1
n.processMessage @ MicrosoftTeams.min.js:1
t @ MicrosoftTeams.min.js:1
teams_tab_configuration.php:105 Error getting cached id token. This should never happen.
successCallback @ teams_tab_configuration.php:105
r.GlobalVars.handlers.authentication.authenticate.success @ MicrosoftTeams.min.js:1
c @ MicrosoftTeams.min.js:1
n.processMessage @ MicrosoftTeams.min.js:1
t @ MicrosoftTeams.min.js:1
postMessage (async)
g @ MicrosoftTeams.min.js:1
l @ MicrosoftTeams.min.js:1
n.processMessage @ MicrosoftTeams.min.js:1
t @ MicrosoftTeams.min.js:1
_#/school/conversations/General?threadId=19:e06bdf6b31b74cd1bac284969d0366ee@thread.skype&ctx=channel:1 Invalid 'X-Frame-Options' header encountered when loading 'https://********.*****.***.**/': 'ALLOW-FROM https://********.*****.***.**' is not a recognized directive. The header will be ignored.

**Comment by weilai-irl** [comment] 2021-06-29 11:20
Hi @Zhuich and @klovsb,

Please check out the latest release of the local_o365 plugin which contains major improvements of Moodle and Teams integration, and confirm if the issues are fixed.

The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by weilai-irl** [comment] 2021-07-30 20:15
Issue closed one month after release.

**Closed by weilai-irl** 2021-07-30 20:15 UTC
Labels: Feature - Teams SSO, Issue type - bug, Plugin - local_o365, Status - released / will close soon, Triaging status - triaged
