### ISSUE TITLE
User picture is synchronised only once

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1898] opened 2021-11-30 14:27 UTC
Hi,

we are using Moodle 3.9.9 and local_o365-plugin set (3.9.6, 2020071509). We set o365-plugin settings to "Sync Microsoft 365 profile photos to Moodle on login". It works fine - user pictures will be synchronised from Azure AD to Moodle during the login, but only once. In some cases the user picture will not be synchronised anymore:
- if the users themselves change or delete their synchronised user picture in the user profile settings in Moodle
- if a new user picture will be stored in Azure AD

I'm not shure if this problem also exists in new plugin/Moodle versions - actually I'm not able to test ist.

br, Anton

**Comment by weilai-irl** [comment] 2021-11-30 14:34
Hi @AntonT76,

User profile photos are synced at most once every 24 hours. The original purpose of the this arrangement is to avoid throttling. Could you confirm if the user profile gets updated after 24 hours please.

Regards,
Lai

**Comment by AntonT76** [comment] 2021-11-30 15:07
Hi @weilai-irl 

thank you for the quick reply. I noticed it a few days ago, unfortunately nothing has changed even after 24 hours.
Note: we synchronise the user picture only at login and during the cron job (due to performance issues during synchronising via cron job).

br, Anton

**Comment by weilai-irl** [comment] 2021-12-02 15:07
Hi @AntonT76,

I think you will need to add the Microsoft block to the landing page after user login (e.g. dashboard page) to trigger the user profile sync. The sync is triggered by a logic in the block code, rather than by the user login event.

It is something we would like to change, but didn't get a chance yet.

Please give it a try and see if it works.

Regards,
Lai

**Comment by AntonT76** [comment] 2021-12-02 16:42
Dear @weilai-irl 

Thanks for this information. I have been using the Microsoft block for a while (e.g. on the landing page and also in the dashboard). The Microsoft block shows "you are currently connected to Microsoft 365", but unfortunately synchronisation does not work.

br, Anton

**Comment by AntonT76** [comment] 2021-12-06 07:27
Dear @weilai-irl 

maybe it is interesting for you: we also did some tests with setting "Sync Microsoft 365 profile photos to Moodle in cron job" and "Perform a full sync each run". The user picture was also not updated.

br, Anton

**Comment by weilai-irl** [comment] 2021-12-10 11:24
Hi @AntonT76,

I verified the logics in the latest version of the plugins (for Moodle 3.9 the latest release is 3.9.8) again and confirmed everything is working as expected:
 - If the "Sync Microsoft 365 profile photos to Moodle on login" option is enabled, Moodle will try to sync profile photo (and user timezone) the first time the Microsoft block loads its content on every login. Note there is no limit to how many times the profile photo is synced every 24 hours, i.e. if you logout from Moodle, and log back in immediately, Moodle will try to sync the photo again.
 - If the "Sync Microsoft 365 profile photos to Moodle in cron job" option is enabled, when running the usersync scheduled task, for each user received, Moodle will try to check when the profile photo of the user was last synced, and if it was before the expiry time, it will try to sync it again. The expiry time is defined by the "Profile photo refresh time" setting in the advanced tab of the plugin configuration page. If no value is provided, it defaults to 24 hours.
 - After a profile photo sync of a user, the details of the sync, including reference to the photo synced and the time of the sync, are recorded in "mdl_local_o365_appassign" table. Search by the "muserid" field using your Moodle user ID, and the "photoupdated" field should contain the timestamp when the profile photo was last updated, either from login or the scheduled task; and the "photoid" field would contain the reference to the profile photo.
 - The function that actually performs the photo sync is get_photo_metadata() in /local/o365/classes/rest/unified.php. The app permission required by the Graph API call is "User.Read.All" or "User.ReadWrite.All", which is quite basic and I assume they are given and consented in your case.

With the explanation above, could you check what could went wrong in your situation please. In particular, could you check your "mdl_local_o365_appassign" table to see if there was attempt to update the profile photo of the user in question.

Also, I'd suggest you upgrade to the latest release version of the plugins, as my investigation was only performed on the latest release version (Release 3.9.8).

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-02-23 15:00
Hi @AntonT76,

Just wondering if you have made some progress in the investigation of this one?

Just a thought when I revisited this issue - the function to sync user profile photos uses the user's personal token cached in Moodle database, which may expire after sometime. This is normally 90 days after user's last login. This may cause issue when trying to sync user profile photos from the user sync scheduled task, but should be irrelevant when using syncing user photo on login. 

FYI, there will be a change to the photo sync feature on login in the next release. Instead of triggering the profile photo sync from the content of the Microsoft block, it will be triggered by an observer function, listening for user logged in event. The implementation of the function that fetches the profile photo is unchanged though.

Regards,
Lai

**Comment by AntonT76** [comment] 2022-02-23 16:02
Dear @weilai-irl 

thank you for asking. I did some changes and tests:
- adpation of the Azure AD-interface (allow permission: User.Read.All / User.ReadWrite.All)
- check table local_o365_appasign table

Result: as I can see in the table that during login the timestamp "photoupdated" will be updated, but the user picture itself will not be updated. I did the test with the newest microsoft plugin-releases for Moodle 3.9.

I have also seen your issue (https://github.com/microsoft/o365-moodle/issues/1945) which should be published in March 2022 - I think I will wait for this release and try to test it again.

br, Anton

**Comment by weilai-irl** [comment] 2022-04-08 14:38
Hi @AntonT76,

The release I mentioned in my previous note is out now. For Moodle 3.9, it's [3.9.9 release](https://github.com/microsoft/o365-moodle/releases/tag/v20220408_m39), and can be downloaded from Moodle plugins directory.

Could you upgrade your plugins to this version and see if it makes any difference please.

Regards,
Lai

**Comment by AntonT76** [comment] 2022-04-13 10:59
Dear @weilai-irl 

I did some tests again on Moodle 3.9.12+ and 3.11.6+ and the latest version of Microsoft plugin set. Unfortunately it doesn't work yet.
- after first login the user picture will be synchronised from Azure AD
- after login I changed/deleted my user picture in Moodle
- logout and login again - user picture will not be synchronised
- change Profile photo refresh time (variable: local_o365 | photoexpire) to = 1
- also resynch users with Azure AD (task: \local_o365\task\usersync)
- login after a few hours - user picture will not be synchronised

I also have a look at table "mdl_local_o365_appassign" - field: "photoupdated" - after login the field will always be updated, but the user picture will not be changed.
I also have edited the table "mdl_local_o365_appassign" - field: "photoid" and deleted the value. And then after login, the user picture will be synchonised again (it is independent of whether I have previously changed or deleted my user picture in Moodle).
PS: the value "photoid" did not change - it has the same value before and after I have deleted this value directly in the database.

I'm not sure if the issue is a Moodle-issue or Azure-AD-issue. Attached you can find the Microsoft Graph permissions, maybe you can see some issues which we have to set in Azure AD?

![graph-permissions](https://user-images.githubusercontent.com/66412602/163166078-d1987731-2396-43bb-b7ec-effd678367b5.png)

I will also post a question in the Moodle Authentication user forum (https://moodle.org/mod/forum/view.php?id=42), maybe some other Moodle users have the same problem and can give me a hint.

br, Anton

**Comment by weilai-irl** [comment] 2022-04-13 15:22
Hi @AntonT76,

I see the issue here - in your step 2, you deleted / updated Moodle user profile photo, this action will not update the value of  `photoid` field  in  the `local_o365_appassign` table, so as far as the the integration is concerned, the user has the same user profile photo from the previous successful profile photo sync. The next time it tries to update user profile, it will first check if the new profile photo has the same `photoid` as the `photoid` in record, and skip the update if they are the same.

A solution is to drop the check against photoid and perform a profile photo sync regardless.

I'll prepare a PR and link it here when ready.

I'll move this issue to the next release.

Regards,
Lai

**Comment by Ecrofirt** [comment] 2022-04-20 19:55
Hi there @weilai-irl I just wanted to report that we're having a similar issue at our school. We're using Moodle through a hosting provider, so getting direct access to the database is difficult.

I wanted to comment that we're experiencing a similar issue that I think ultimately falls back to this problem.

Many of our users are showing up with a default silhouette image after previously showing a proper ID photo. Attempting to sync during CRON or login hasn't resolved the issue, and it's been going on for about a year now.

In our case, I think the issue happened when we had a network outage. Our hosting provider syncs users in via external database and during login of the user the external database is checked to find user enrolments. The external db is hosted in our datacenter with a VPN tunnel set up between our hosting provider and us. At one point we had a network outage which caused users in the external db to not be found during login, and since then anyone affected has had no photo.

I was able to check for our affected users, and they appear to have valid photoupdated times that are all less than 24 hours old, and in many cases they have a value in the photoid field.

I suspect that during our network outage, the user's real photo was deleted in Moodle's database, but the photoid field was left in tact. The users have no updated their photos since then out at Microsoft 365.

Following the logic in your post above, would I be correct in guessing that this is the basic logic for photo updates?
If (photoupdated is older than photo_refresh_time)
  if (existing photoid != new photoid)
    sync photo
  end if
end if

And we've found ourselves in a pickle of the photoid matching (even though it's been deleted) so the photo isn't re-synced?

**If so, would it be acceptable to truncate either the entire mdl_local_o365_appassign table, or to specifically delete the records where this is an issue?**

We think there is a link to the mdl_user table having a picture value of 0 on all of the potentially affected users.

**Comment by Ecrofirt** [comment] 2022-04-21 20:18
Hi @weilai-irl you'll have to excuse me a bit. I'm brand new to github and I'm not a native PHP programmer. I looked at the pull requests you made, and I'm a little worried that while the solution works, it's like a sledgehammer for the problem. If I'm understanding your changes correctly, this is going to forcibly download new photos for everyone.

I'm not sure if the assign_photo() method call happens during a CRON sync, but if it does I'm considering the use case for my school, where we have several thousand users that would have their photos downloaded and updated at once. To that end, I would wager that the eTag check was much more elegant, but ran into some potential issues.

I've got two suggestions that could change things a bit while avoiding an unnecessary forced download of photos for all users.

In the first suggestion, you could change the processing to blank out the photoid value if the user's picture value is empty, and then continue on with your normal processing. This would then cause you to compare a valid etag to a blank photoid, which would cause a new download of a photo. This should solve the issue of manually deleted user photos on Moodle getting appropriately resynced. I have pseudocode for that below.

For the second suggestion, perhaps it would be possible to add a "Force full photo sync on next run" option to the sync settings. if that option is synced, on the next CRON run, it would forcibly update all user photos without checking for etag differences. At the end of the CRON job, the checkbox would get turned back off, as there would be no need to forcibly resync everyone's photo again. This is effectively the code you've got in your pull request, though I don't know how you'd go about checking if the box is checked and unchecking it at the end.

Here's the pseudocode for the first suggestion I made above:
```
//OLD process

size = get_photo_metadata()

if (size is empty) { 
//file was deleted at Office 365
	if (user->photo value isn't empty) { 
	//photo not deleted in Moodle DB, so it must be deleted
		delete moodle photo
	}
} else if (size->etag !== photoid) {
//stored etag does not match current etag, so new photo needs to be downloaded
	download user photo from Office 365
	set the user's photo in the Moodle DB
	update photoid variable
}

if (record is empty) {
//There was no local_o365_appassign record for the user
	create a new record
}
update record->photoid
insert or update the record in the local_o365_appassign table

//---------------


//Suggested new process - Add this just before getting the size metadata
if (user->photo is empty)
{
	//Blank out the photoid value again, because the photo was deleted in Moodle
	photoid = ''
}

//everything below this is the same

size = get_photo_metadata()
if (size is empty) { 
//file was deleted at Office 365
	if (user->photo value isn't empty) { 
	//photo not deleted in Moodle DB, so it must be deleted
		delete moodle photo
	}
} else if (size->etag !== photoid) {
//stored etag does not match current etag, so new photo needs to be downloaded
	download user photo from Office 365
	set the user's photo in the Moodle DB
	update photoid variable
}
if (record is empty) {
//There was no local_o365_appassign record for the user
	create a new record
}
update record->photoid
insert or update the record in the local_o365_appassign table
```

**Comment by weilai-irl** [comment] 2022-06-21 11:05
Hi @Ecrofirt,

The latest release from today contains a fix to the issue supported. Please check it out and confirm if it works for you.

I'll keep the issue open for another month and close it if no more reporting of the issue.

Regards,
Lai

**Comment by weilai-irl** [comment] 2022-08-02 20:27
Closed one month after release.

**Closed by weilai-irl** 2022-08-02 20:27 UTC
Labels: Issue type - help wanted, Feature - user sync, Status - PR ready / pending release, Plugin - block_microsoft
