### ISSUE TITLE
usersync suspending valid Azure AD accounts 

### ISSUE THREAD

**Issue by LDGreg** [microsoft/o365-moodle#1325] opened 2020-07-23 19:23 UTC
New to Moodle so please bare with me. Recently we upgraded to Moodle 3.9.1+ (Build: 20200717) and I also upgraded all the Office Plugins to the 3.9 version. The usersync plugin in particular is: 3.9.0 (Build: 2020071500). I had troubles with the Cron script executing the command after the upgrade but that just turned out to be too low an idle timeout on MySQL. The connection would get closed while usersync waited to hear back from AzureAD on deleted accounts for example. Once that was raised the task started running fine. I ran it several times via command line on it's own using the admin tools. I did get some php errors having to do with variables not defined for function calls and a few MySQL index errors however I checked the DB schema and even optimized the o365 tables and they all came back clean. The errors still happen but not on every account update, just the odd one. 

What was really strange was when I put the task back into the regular Cron process and it ran Thursday morning at the scheduled time. All of a sudden about 1200 legitimate accounts we're suspended as they weren't found in Azure AD. That made no sense as all the accounts suspended are legitimate and setup and correct in Azure AD. We also couldn't find any difference between the suspended and unsuspended accounts to cause it to happen. I batch updated all the suspended accounts to unsuspended but I have not idea why it happened in the first place.  I'm concerned it will happen again next Thursday as well but I'm also wondering if this is just a side affect of the jobs not running on a proper schedule? Also in some cases when the account is suspended it's also been deleted which impacts the users course history as well. 

I've tried purging the sync tokens as well just in case that was causing problems via the Advanced tab. 

Any help is appreciated and I'll pull up whatever diags you need but may need a little direction on where to look.

Here's the plugin diag:
{"moodlecfg":{"dbtype":"mysqli","debug":15,"debugdisplay":"0","debugdeveloper":false,"auth":"oidc","timezone":"America\/Vancouver","forcetimezone":"99","authpreventaccountcreation":"0","alternateloginurl":"","release":"3.9+ (Build: 20200704)","version":"2020061500.04","localo365forcelegacyapi":0},"plugin_data":{"auth_oidc":{"version":"2020071500","enabled":1,"authendpoint":"https:\/\/login.microsoftonline.com\/common\/oauth2\/authorize","tokenendpoint":"https:\/\/login.microsoftonline.com\/common\/oauth2\/token","oidcresource":"https:\/\/graph.microsoft.com","autoappend":"","domainhint":"","loginflow":"authcode","debugmode":"0"},"block_microsoft":{"version":"2020071500","enabled":1,"showo365download":"1","settings_showonenotenotebook":"1","settings_showoutlooksync":"0","settings_showpreferences":"1","settings_showo365connect":"1","settings_showmanageo365conection":"0","settings_showcoursespsite":"1"},"filter_oembed":{"version":"2019112600","enabled":1,"o365video":null,"officemix":null,"sway":null,"provider_docsdotcom_enabled":null},"local_microsoftservices":{"version":"null","enabled":0},"local_msaccount":{"version":"null","enabled":0},"local_o365":{"version":"2020071500","enabled":0,"aadsync":"create,update,delete,match,matchswitchauth,appassign,photosync,photosynconlogin","aadtenant":"londondrugslimited.onmicrosoft.com","azuresetupresult":"O:8:\"stdClass\":3:{s:9:\"legacyapi\";O:8:\"stdClass\":2:{s:12:\"missingperms\";a:4:{s:30:\"Windows Azure Active Directory\";a:3:{s:18:\"Directory.Read.All\";s:19:\"Read directory data\";s:26:\"Directory.AccessAsUser.All\";s:42:\"Access the directory as the signed-in user\";s:13:\"User.Read.All\";s:29:\"Read all users' full profiles\";}s:28:\"Office 365 SharePoint Online\";a:6:{s:13:\"AllSites.Read\";s:34:\"Read items in all site collections\";s:14:\"AllSites.Write\";s:44:\"Read and write items in all site collections\";s:15:\"AllSites.Manage\";s:54:\"Read and write items and lists in all site collections\";s:20:\"AllSites.FullControl\";s:41:\"Have full control of all site collections\";s:12:\"MyFiles.Read\";s:15:\"Read user files\";s:13:\"MyFiles.Write\";s:25:\"Read and write user files\";}s:26:\"Office 365 Exchange Online\";a:1:{s:19:\"Calendars.ReadWrite\";s:29:\"Read and write user calendars\";}s:7:\"OneNote\";a:2:{s:15:\"Notes.ReadWrite\";s:33:\"View and modify OneNote notebooks\";s:12:\"Notes.Create\";s:33:\"Create pages in OneNote notebooks\";}}s:8:\"haswrite\";b:0;}s:7:\"appdata\";O:8:\"stdClass\":0:{}s:10:\"unifiedapi\";O:8:\"stdClass\":4:{s:6:\"active\";b:1;s:15:\"missingappperms\";a:0:{}s:8:\"apptoken\";b:1;s:12:\"missingperms\";a:0:{}}}","chineseapi":"0","createteams":"oncustom","debugmode":"1","enableunifiedapi":null,"disablegraphapi":null,"fieldmap":"a:8:{i:0;s:26:\"givenName\/firstname\/always\";i:1;s:23:\"surname\/lastname\/always\";i:2;s:17:\"mail\/email\/always\";i:3;s:16:\"city\/city\/always\";i:4;s:22:\"country\/country\/always\";i:5;s:28:\"department\/department\/always\";i:6;s:29:\"preferredLanguage\/lang\/always\";i:7;s:37:\"employeeId\/profile_field_EmpID\/always\";}","odburl":"londondrugslimited-my.sharepoint.com","photoexpire":"24","usersynccreationrestriction":"a:3:{s:11:\"remotefield\";s:17:\"userPrincipalName\";s:5:\"value\";s:0:\"\";s:8:\"useregex\";b:0;}","sharepoint_initialized":null,"task_usersync_lastskiptoken":null,"unifiedapiactive":"1"},"local_office365":{"version":"null","enabled":0},"local_onenote":{"version":"null","enabled":0},"assignsubmission_onenote":{"version":"null","enabled":0},"assignfeedback_onenote":{"version":"null","enabled":0},"repository_office365":{"version":"2020071500","enabled":1},"repository_onenote":{"version":"null","enabled":0}}}

Thanks in advance,
Greg Martin

**Comment by LDGreg** [comment] 2020-07-27 16:05
Ok now it's deleted thousands of users and their history. Please any help would be nice.

**Comment by webframp** [comment] 2020-07-27 21:06
Currently I see this exact same behavior for several hundred Azure AD "guest" accounts that are invited to our tenant. 

The specific moodle task responsible is `\core\task\delete_unconfirmed_users_task` according to task logs:

![image](https://user-images.githubusercontent.com/774378/88591181-f58b3900-d029-11ea-9d2e-a6dd3f1f0dfe.png)

And we confirmed timing by checking events in the database with the following query:

<pre>
SELECT l.eventname, l.action, u.username, FROM_UNIXTIME(l.timecreated), l.origin FROM mdl_logstore_standard_log as l JOIN mdl_user u ON l.objectid = u.id
WHERE l.objecttable = 'user' AND l.action = 'deleted' AND u.username LIKE '%fake_guest.org%' ORDER BY l.timecreated ASC LIMIT 0, 2000;

+--------------------------+---------+--------------------------------------------------------------------+------------------------------+--------+
| eventname                | action  | username                                                           | FROM_UNIXTIME(l.timecreated) | origin |
+--------------------------+---------+--------------------------------------------------------------------+------------------------------+--------+
| \core\event\user_deleted | deleted | dreyese301@fake_guest.org.1835191@unknownemail.invalid.1593003176 | 2020-06-24 12:52:56          | web    |
| \core\event\user_deleted | deleted | 10bbert@fake_guest.org.1594405125                                 | 2020-07-10 18:18:47          | cli    |
| \core\event\user_deleted | deleted | 10dlanulo@fake_guest.org.1594405212                               | 2020-07-10 18:20:29          | cli    |
| \core\event\user_deleted | deleted | 10elsap001@fake_guest.org.1594405278                              | 2020-07-10 18:21:36          | cli    |
| \core\event\user_deleted | deleted | 10mako005@fake_guest.org.1594405446                               | 2020-07-10 18:24:23          | cli    |
| \core\event\user_deleted | deleted | 10rdna21@fake_guest.org.1594405555                                | 2020-07-10 18:26:13          | cli    |
| \core\event\user_deleted | deleted | 11adip@fake_guest.org.1594405750                                  | 2020-07-10 18:29:28          | cli    |
| \core\event\user_deleted | deleted | 11adogo@fake_guest.org.1594405768                                 | 2020-07-10 18:29:31          | cli    |
| \core\event\user_deleted | deleted | 11bmoldov1@fake_guest.org.1594405804                              | 2020-07-10 18:30:22          | cli    |
| \core\event\user_deleted | deleted | 12bdun@fake_guest.org.1594405950                                  | 2020-07-10 18:32:32          | cli    |
| \core\event\user_deleted | deleted | 12beric@fake_guest.org.1594405974                                 | 2020-07-10 18:33:11          | cli    |
| \core\event\user_deleted | deleted | 12fsorf@fake_guest.org.1594406015                                 | 2020-07-10 18:33:52          | cli    |
| \core\event\user_deleted | deleted | 15dwnt@fake_guest.org.1594406463                                  | 2020-07-10 18:41:21          | cli    |
| \core\event\user_deleted | deleted | basqueaf@fake_guest.org.1594915610                                | 2020-07-16 16:06:53          | cli    |
| \core\event\user_deleted | deleted | brambf@fake_guest.org.1594915714                                  | 2020-07-16 16:08:52          | cli    |
| \core\event\user_deleted | deleted | bruno17@fake_guest.org.1594915733                                 | 2020-07-16 16:08:55          | cli    |
| \core\event\user_deleted | deleted | bcasti19@fake_guest.org.1594915796                                | 2020-07-16 16:09:59          | cli    |
| \core\event\user_deleted | deleted | bcgovern15@fake_guest.org.1595343155                              | 2020-07-21 14:52:59          | cli    |
| \core\event\user_deleted | deleted | cancarlo@fake_guest.org.1595343241                                | 2020-07-21 14:54:04          | cli    |
| \core\event\user_deleted | deleted | 17snleadmon@fake_guest.org.1595343349                             | 2020-07-21 14:55:52          | cli    |
| \core\event\user_deleted | deleted | 1georgeore@fake_guest.org.1595343353                              | 2020-07-21 14:56:12          | cli    |
| \core\event\user_deleted | deleted | 1jesspep@fake_guest.org.1595343372                                | 2020-07-21 14:56:15          | cli    |
| \core\event\user_deleted | deleted | 1nlsonal@fake_guest.org.1595343375                                | 2020-07-21 14:56:33          | cli    |
| \core\event\user_deleted | deleted | 5shan10@fake_guest.org.1595343395                                 | 2020-07-21 14:56:52          | cli    |
| \core\event\user_deleted | deleted | 8sarppa@fake_guest.org.1595343414                                 | 2020-07-21 14:57:12          | cli    |
| \core\event\user_deleted | deleted | aidgomez17@fake_guest.org.1595343553                              | 2020-07-21 14:59:16          | cli    |
| \core\event\user_deleted | deleted | albiouwauni9@fake_guest.org.1595343581                            | 2020-07-21 14:59:43          | cli    |
| \core\event\user_deleted | deleted | armand2@fake_guest.org.1595343613                                 | 2020-07-21 15:00:32          | cli    |
| \core\event\user_deleted | deleted | asharbi56@fake_guest.org.1595343809                               | 2020-07-21 15:03:31          | cli    |
+--------------------------+---------+--------------------------------------------------------------------+------------------------------+--------+
</pre>

**Comment by webframp** [comment] 2020-08-12 12:47
Any updates on this issue?

**Comment by weilai-irl** [comment] 2020-08-12 12:51
Hi @webframp,

The work requested in this issue hasn't started yet. It will be reviewed in due course, and will be included in the next release (~Sep 20) or the one after it (~Nov 20).

Regards,
Lai

**Comment by webframp** [comment] 2020-08-13 17:51
That's great to hear @weilai-irl 

Do you have any suggested workaround or extra debugging steps that we can do in the meantime?  Thanks!

**Comment by LDGreg** [comment] 2020-09-22 16:36
If it helps for my setup it is not "guest" accounts that are being deleted. It's non-discriminatory in terms of the account.

**Comment by webframp** [comment] 2020-09-22 22:16
@weilai-irl hello! How is it looking for a release this month? Any more ideas on the frequent user mismatch issues so many seem to be reporting that could be the root of all of this?

**Comment by weilai-irl** [comment] 2020-09-23 08:09
@webframp,

The September release will come next week, but unfortunately fix to this issue will not be part of this one. We will try to include this in the next one in November.

Regards,
Lai

**Comment by ak4t0sh** [comment] 2020-10-21 08:13
facing same issue.
Hope you can make it for next release :)

**Comment by asneyap** [comment] 2020-10-28 20:06
Hi,
I'm in the same situation. My moodle is not usable anymore and I had to restore from a backup. Don't know why we receive a "Could not find user xxxx in Azure AD" while that is not true.

I've disabled sync setting to remove users from Moodle if they were removed from Azure AD. Hope it is solved soon.

Thanks.

**Comment by weilai-irl** [comment] 2020-11-05 12:17
Hi everyone,

We made some progress in this issue.

The most probable cause of the account deletion is in the implementation of the delete_users() function of the main class in local/o365/classes/feature/usersync/main.php. The current logic works like this:
 1.1 Get all Office 365 users deleted in the last 30 days from Office 365.
 1.2 Find matching Moodle accounts for each of them, and suspend these accounts.
 2.1 Find all Moodle accounts that are matched to Office 365 users, but not included in the suspended users list in step 1.2.
 2.2 For each of the Moodle account found in step 2.1, try to get details of the user from Office 365.
 2.2.1 If user details can be fetched from Office 365, the Office 365 account is deemed active, and nothing will happen to the Moodle account.
 2.2.2 If user details cannot be fetched from Office 365 for whatever reason (i.e. any exception is returned in this Graph API call to get user details), the plugin will treat the Office 365 account to be deleted, and will try to delete the Moodle account in two steps:
 2.2.2.1 If the Moodle account is not suspended already, suspend the account.
 2.2.2.2 If the Moodle account is already suspended, delete the account.

I think the biggest issue is in the logic to determine if an Office 365 account is deleted in step 2.2.2 - Graph API call to get user details can potentially fail for many different reasons, and it's simply too broad to treat all exceptions to be the indicator for Office 365 account deletion.


The solution that will be put in place in the upcoming November release is to check the error message in the exception, and only proceed to step 2.2.2.1 and 2.2.2.2 if the error message in the exception matches the expected error message when an Office 365 account is actually deleted.

The change will mean that:
 - In a normal use case, where the option is enabled and not changed, and an Office 365 account is deleted:
   - Their matching Moodle account will be suspended on the first task run after Office 365 account deletion;
   - The Moodle account will be deleted on the first run 30 days after their Office 365 account deletion.
 - In case the option to delete Moodle users is changed from disabled to enabled:
   - If the deletion of the Office 365 account happened before 30 days:
     - The matching Moodle account will be suspended on the first task run after the configuration change is made.
     - The Moodle account will be deleted on the second task run after the configuration change is made.
   - If the deletion of the Office 365 account happened within 30 days:
     - The matching Moodle account will be suspended on the first task run after the configuration change is made.
     - The Moodle account will be deleted on the first run 30 days after their Office 365 account deletion.

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-05 12:25
@webframp,

In relation to your comment at https://github.com/microsoft/o365-moodle/issues/1325#issuecomment-664638497, the issue you described in the comment seems to be different. I checked the logic in both auth_oidc and local_o365, and I confirm that Moodle users created from both sources would have "confirmed" field set to 1, which will exclude them from the "delete unconfirmed users task". The issue you have may be down to how the users are created, e.g. maybe using CSV upload?

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-18 12:48
Hi all,

The fix to the issue according to my comment in https://github.com/microsoft/o365-moodle/issues/1325#issuecomment-722342214 has been included in the 3.8.0.5 and 3.9.2 release. Please check it out.

Regards,
Lai

**Closed by weilai-irl** 2020-11-18 12:48 UTC
Labels: triaged

**Comment by ak4t0sh** [comment] 2020-12-03 16:31
Thanks @weilai-irl I can confirm it fixed the issue on my side :+1:
