### ISSUE TITLE
User sync setting for "on creation" ignored and updates users on every other login

### ISSUE THREAD

**Issue by jtsafran** [microsoft/o365-moodle#1349] opened 2020-08-20 20:12 UTC
Moodle version: Moodle 3.8.3 (Build: 20200511)
Plugin version: 3.8.0.2 (2020020302)
Looks to exist in most recent 3.9 version, but not verified (code examples below are from the 3.9 branch)

When a user logs in, if the sync settings for given name/first name (and possibly others) are set to "on creation", the login will overwrite the user's first name with the AAD value.  This happens on every other login.

If I am following the in https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/observers.php#L260 correctly, it looks like both $userdata and $updateduser are populated with values from AAD.  https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/feature/usersync/main.php#L358 defines that second stdClass to be the Moodle user and not AAD.

I tried a quick fix of replacing $updateduser with $updateduser = \core_user::get_user($userid);.  It works great on logins for existing users, but for ones that do not exist, it prompts the user to type in values for any field that are set to "on creation".  I'm a bit lost as to why that is.

Thoughts?

**Comment by weilai-irl** [comment] 2020-08-20 20:47
Hi @jtsafran,

I confirm this is a kind of known issue. The actual logic to upload user information is in the function get_userinfo() at https://github.com/microsoft/o365-moodle/blob/master/auth/oidc/classes/loginflow/base.php#L91, in which first name, last name, and email of user is always updated according to ID token claims. A custom patch that comments out the logic will help.

Regards,
Lai

**Comment by jtsafran** [comment] 2020-08-20 22:30
Lai,

Thank you for the fast reply.  I will take a close look tomorrow and see what I can find/do.  

Once patched, would you like this change merged back in?

-Jesse

**Comment by jtsafran** [comment] 2020-10-05 14:12
Sorry for my delay here.  

It looks like both locations need changed:

/auth/oidc/classes/loginflow/base.php - get_userinfo function

`    public function get_userinfo($username) {
        global $DB;

        $tokenrec = $DB->get_record('auth_oidc_token', ['username' => $username]);
        if (empty($tokenrec)) {
            return false;
        }

        $idtoken = \auth_oidc\jwt::instance_from_encoded($tokenrec->idtoken);

        // Get user info from Moodle DB
        $userinfo = $DB->get_record('user',array('username'=>$username));
        $userinfo = json_decode(json_encode($userinfo), true);

        // Extract basic information from the IDToken if it doesn't exist in Moodle.  This should only happen on a first login
        if (empty($userinfo['firstname'])) {
            $userinfo['firstname'] = $idtoken->claim('given_name');
        }

        if (empty($userinfo['lastname'])) {
            $userinfo['lastname'] = $idtoken->claim('family_name');
        }

        if (empty($userinfo['email'])) {
            $userinfo['email'] = $idtoken->claim('email');
        }

        //if both Moodle and Azure email are empty, default to UPN
        if (empty($userinfo['email'])) {
            $aademail = $idtoken->claim('upn');
            if (!empty($aademail)) {
                $aademailvalidateresult = filter_var($aademail, FILTER_VALIDATE_EMAIL);
                if (!empty($aademailvalidateresult)) {
                    $userinfo['email'] = $aademail;
                }
            }
        }

        // O365 provides custom field mapping. Perform that mapping now if it's installed.
        $o365installed = $DB->get_record('config_plugins', ['plugin' => 'local_o365', 'name' => 'version']);
        if (!empty($o365installed)) {
            $apiclient = \local_o365\utils::get_api($tokenrec->userid);
            $userdata = $apiclient->get_user($tokenrec->oidcuniqid);
            $updateduser = \local_o365\feature\usersync\main::apply_configured_fieldmap($userdata, (object)$userinfo, 'login');
            $userinfo = (array)$updateduser;
        }

        return $userinfo;
    }`


and /local/o365/classes/observers.php - get_additional_user_info up to the apply_configured_fieldmap call:

`    public static function get_additional_user_info($userid, $eventtype) {
        global $DB;

        try {
            // Azure AD must be configured for us to fetch data.
            if (\local_o365\rest\azuread::is_configured() !== true) {
                return true;
            }

            $o365user = \local_o365\obj\o365user::instance_from_muserid($userid);
            if (empty($o365user)) {
                // No OIDC token for this user and resource - maybe not an Azure AD user.
                return false;
            }

            $idtoken = \auth_oidc\jwt::instance_from_encoded($o365user->get_idtoken());
            $apiclient = \local_o365\utils::get_api($userid);
            $userdata = $apiclient->get_user($o365user->objectid);
            // Azuread users objectid, unified uses id.
            if (\local_o365\rest\unified::is_configured() && empty($userdata['objectId']) && !empty($userdata['id'])) {
                $userdata['objectId'] = $userdata['id'];
            }

            // Get user info from Moodle DB
            $updateduser = new \stdClass;
            $updateduser = \core_user::get_user($userid);

            // Extract basic information from the IDToken if it doesn't exist in Moodle.  This should only happen on a first login
            if (empty($updateduser->firstname)) {
                $updateduser->firstname = $idtoken->claim('given_name');
            }

            if (empty($updateduser->lastname)) {
                $updateduser->lastname = $idtoken->claim('family_name');
            }

            if (empty($updateduser->email)) {
                $updateduser->email = $idtoken->claim('email');
            }

            //if both Moodle and Azure email are empty, default to UPN
            if (empty($updateduser->email)) {
                $aademail = $idtoken->claim('upn');
                if (!empty($aademail)) {
                    $aademailvalidateresult = filter_var($aademail, FILTER_VALIDATE_EMAIL);
                    if (!empty($aademailvalidateresult)) {
                        $updateduser->email = $aademail;
                    }
                }
            }

            // Then apply the custom field map.
            $updateduser = \local_o365\feature\usersync\main::apply_configured_fieldmap($userdata, $updateduser, $eventtype);`

**Comment by weilai-irl** [comment] 2020-10-05 14:36
Hi @jtsafran,

I confirm the issue. I fixed it recently on a local dev instance. I'll need to arrange more testing on it, before merging it to the release version.

Regards,
Lai

**Comment by weilai-irl** [comment] 2020-11-18 15:16
Hi @jtsafran 

The issue is fixed in the latest release of the plugin (3.8.0.5 and 3.9.2). Thank you again for your contribution.

Regards,
Lai

**Closed by weilai-irl** 2020-11-18 15:16 UTC
